/* 1001 Jazz — 艺术家小传数据
 * 键 = 专辑数据里的英文 artist 字符串（务必完全一致）。
 * 字段：zh 译名 · born/died 生卒（在世者省略 died；乐队改用 life 活跃年）
 *       country 国别 · role 身份/乐器 · bio 中文小传。
 * 缺省优雅降级：没有词条的艺术家仍正常显示作品列表，只是不显示小传卡。
 */
window.ARTIST_BIOS = {
  "Miles Davis":{zh:"迈尔斯·戴维斯",born:1926,died:1991,country:"美国",role:"小号 · 作曲 · 乐队领袖",bio:"二十世纪最重要的爵士革新者，没有之一。从比波普到冷爵士、调式爵士、再到电气化融合，他一次次亲手推翻自己缔造的风格，把整支乐队带向下一个时代。《Kind of Blue》《Bitches Brew》是两座永远绕不开的里程碑。"},
  "John Coltrane":{zh:"约翰·柯川",born:1926,died:1967,country:"美国",role:"萨克斯 · 作曲",bio:"用十年时间把萨克斯吹成一种灵性追问。从硬波普的‘音墙’到《A Love Supreme》的虔诚祈祷，再到晚期自由爵士的狂喜，他把即兴推向技术与精神的双重极限，深刻影响了此后所有管乐手。"},
  "Herbie Hancock":{zh:"赫比·汉考克",born:1940,country:"美国",role:"钢琴 · 键盘 · 作曲",bio:"从迈尔斯五重奏的和声魔术师，到《Maiden Voyage》的现代经典，再到放克、电子与嘻哈的弄潮儿，他始终站在爵士与流行的交界处。一曲《Rockit》让黑胶刮碟登上主流舞台。"},
  "Hank Mobley":{zh:"汉克·莫布利",born:1930,died:1986,country:"美国",role:"次中音萨克斯 · 作曲",bio:"被乐评家形容为‘次中音萨克斯里的中量级冠军’——音色不张扬却分寸极佳。他是 Blue Note 硬波普的中坚，《Soul Station》被公认为最圆熟的硬波普专辑之一。"},
  "Lee Morgan":{zh:"李·摩根",born:1938,died:1972,country:"美国",role:"小号 · 作曲",bio:"硬波普时代最炽热的小号天才，十八岁已是录音室常客。《The Sidewinder》的灵魂爵士律动让 Blue Note 大卖。三十三岁在纽约俱乐部台前被情人枪杀，生涯戛然而止。"},
  "Sonny Rollins":{zh:"桑尼·罗林斯",born:1930,country:"美国",role:"次中音萨克斯 · 作曲",bio:"‘萨克斯巨人’，以无伴奏独奏的叙事能力和对主题的即兴重构著称。《Saxophone Colossus》中的《St. Thomas》尽显其加勒比节奏底色。曾两度隐退苦修，留下在威廉斯堡大桥上独练的传奇。"},
  "Weather Report":{zh:"气象报告（乐队）",life:"活跃 1970–1986",country:"美国",role:"融合爵士乐队",bio:"由键盘手乔·扎维努尔与萨克斯手韦恩·肖特创立，是融合爵士的旗舰。贝斯手雅科·帕斯托留斯加入后达到巅峰，《Heavy Weather》中的《Birdland》成为跨界标准曲。"},
  "Duke Ellington":{zh:"杜克·艾灵顿",born:1899,died:1974,country:"美国",role:"钢琴 · 作曲 · 大乐队领袖",bio:"美国音乐史上最伟大的作曲家之一，把大乐队当作自己的‘乐器’写了半个世纪。他为每位团员量身定制声部，《Ellington at Newport》的现场更点燃了爵士复兴。"},
  "Ornette Coleman":{zh:"奥奈特·科尔曼",born:1930,died:2015,country:"美国",role:"中音萨克斯 · 作曲",bio:"自由爵士的开创者。1959 年的《The Shape of Jazz to Come》抛开固定和弦框架，提出‘和声旋律’（harmolodics）理念，一度引发巨大争议，却永久改变了即兴的可能性。"},
  "Bud Powell":{zh:"巴德·鲍威尔",born:1924,died:1966,country:"美国",role:"钢琴 · 作曲",bio:"把帕克式比波普语汇移植到钢琴上的第一人，右手单音线条快如疾风，左手只点和弦。他奠定了现代爵士钢琴的范式，却一生饱受精神疾病与电击治疗之苦。"},
  "Charlie Parker":{zh:"查理·帕克",born:1920,died:1955,country:"美国",role:"中音萨克斯 · 作曲",bio:"绰号‘大鸟’（Bird），比波普革命的灵魂人物。他以闪电般的速度、复杂的和声替换重写了即兴语言，影响延续至今。三十四岁早逝时，验尸官误判其年龄超过五十。"},
  "Dexter Gordon":{zh:"德克斯特·戈登",born:1923,died:1990,country:"美国",role:"次中音萨克斯",bio:"把帕克的比波普语言带入次中音萨克斯的关键人物，音色宽厚、节奏从容偏后。旅居欧洲多年，晚年主演电影《午夜旋律》获奥斯卡提名，成为爵士传奇的银幕化身。"},
  "Stan Getz":{zh:"斯坦·盖茨",born:1927,died:1991,country:"美国",role:"次中音萨克斯",bio:"以‘如丝般’的甜美音色闻名，人称‘The Sound’。1960 年代他把巴西波萨诺瓦带入北美，《Getz/Gilberto》中的《伊帕内玛的女孩》风靡全球。"},
  "Wayne Shorter":{zh:"韦恩·肖特",born:1933,died:2023,country:"美国",role:"萨克斯 · 作曲",bio:"爵士史上最深邃的作曲家之一，先后效力爵士信使、迈尔斯五重奏，又共同创立气象报告。《Speak No Evil》中的乐曲如谜语般含蓄而开阔，影响了几代作曲者。"},
  "Cecil Taylor":{zh:"塞西尔·泰勒",born:1929,died:2018,country:"美国",role:"钢琴 · 作曲",bio:"自由爵士钢琴的极端先锋，把钢琴当作‘八十八面定音鼓’来敲击。他的音乐密度惊人、能量爆裂，融合古典前卫与非洲节奏，是即兴音乐里最难也最纯粹的存在。"},
  "Charles Mingus":{zh:"查尔斯·明格斯",born:1922,died:1979,country:"美国",role:"贝斯 · 作曲 · 乐队领袖",bio:"暴烈而深情的天才，把布鲁斯、福音、艾灵顿与集体即兴熔于一炉。《Mingus Ah Um》《The Black Saint and the Sinner Lady》既是音乐，也是对种族不公的呐喊。"},
  "Grant Green":{zh:"格兰特·格林",born:1935,died:1979,country:"美国",role:"吉他",bio:"Blue Note 的招牌吉他手，以单音线条的清晰与布鲁斯味十足的律动著称，从不滥用和弦。他横跨硬波普、灵魂爵士与放克，是后世爵士吉他与采样文化的常青源头。"},
  "Horace Silver":{zh:"霍勒斯·西尔弗",born:1928,died:2014,country:"美国",role:"钢琴 · 作曲",bio:"硬波普与‘灵魂爵士’（soul jazz）的奠基人，把福音和布鲁斯的烟火气注入比波普。《Song for My Father》的拉丁律动是一代人的爵士入门。"},
  "Joe Henderson":{zh:"乔·亨德森",born:1937,died:2001,country:"美国",role:"次中音萨克斯 · 作曲",bio:"音色辛辣、构思缜密的次中音大师，游走于硬波普与前卫之间。《Page One》《Inner Urge》尽显其作曲功力；1990 年代凭致敬专辑重获大众瞩目。"},
  "Scott Joplin":{zh:"斯科特·乔普林",born:1868,died:1917,country:"美国",role:"钢琴 · 作曲",bio:"‘拉格泰姆之王’，把这种切分钢琴音乐写成可登大雅之堂的作品。《枫叶拉格》传遍全美，他甚至写了拉格泰姆歌剧。其音乐是爵士节奏的直接前身。"},
  "Art Blakey & the Jazz Messengers":{zh:"阿特·布雷基与爵士信使",life:"活跃 1954–1990",country:"美国",role:"硬波普乐队",bio:"鼓手阿特·布雷基领衔的硬波普‘黄埔军校’，三十余年里源源不断地培养出莫布利、摩根、肖特、马萨利斯等大批新星。《Moanin'》是硬波普的标准范本。"},
  "Bill Evans":{zh:"比尔·埃文斯",born:1929,died:1980,country:"美国",role:"钢琴 · 作曲",bio:"现代爵士钢琴最具诗意的声音，以印象派和声、内省触键和三重奏的对话式互动重塑了钢琴三重奏。《Sunday at the Village Vanguard》是即兴室内乐的典范。"},
  "Cannonball Adderley":{zh:"加农炮·阿德利",born:1928,died:1975,country:"美国",role:"中音萨克斯 · 乐队领袖",bio:"音色明亮、洋溢喜悦的中音萨克斯手，曾参与《Kind of Blue》。他领衔的乐队把灵魂爵士推向流行榜，《Mercy, Mercy, Mercy》成为跨界金曲。"},
  "Dizzy Gillespie":{zh:"迪兹·吉莱斯皮",born:1917,died:1993,country:"美国",role:"小号 · 作曲 · 乐队领袖",bio:"与帕克并肩缔造比波普的小号巨人，标志是鼓起的双腮和向上弯折的喇叭口。他还把古巴节奏引入爵士，开创了‘拉丁爵士’（Afro-Cuban jazz）。"},
  "Donald Byrd":{zh:"唐纳德·伯德",born:1932,died:2013,country:"美国",role:"小号 · 作曲",bio:"学院派出身的硬波普小号手，后大胆拥抱放克与节奏布鲁斯。《Black Byrd》成为 Blue Note 史上最畅销专辑之一，也成为日后嘻哈采样的富矿。"},
  "Freddie Hubbard":{zh:"弗雷迪·哈伯德",born:1938,died:2008,country:"美国",role:"小号 · 作曲",bio:"技术华丽、音色灿烂的小号巨匠，硬波普与前卫的双栖好手，参与了《Free Jazz》《Maiden Voyage》等众多里程碑。《Red Clay》是其融合时期的代表作。"},
  "Jackie McLean":{zh:"杰基·麦克莱恩",born:1931,died:2006,country:"美国",role:"中音萨克斯 · 作曲",bio:"音色尖锐、略带‘走音’张力的中音萨克斯手，从硬波普一路探入前卫领域。《Let Freedom Ring》标志着他向自由爵士的勇敢跨越，晚年更是杰出的爵士教育家。"},
  "McCoy Tyner":{zh:"麦考伊·泰纳",born:1938,died:2020,country:"美国",role:"钢琴 · 作曲",bio:"柯川经典四重奏的钢琴基石，以雷霆般的左手五度和弦与汹涌的调式音阶定义了一种全新的钢琴语汇。单飞后《The Real McCoy》延续了这股磅礴气势。"},
  "Return to Forever":{zh:"重返永恒（乐队）",life:"活跃 1971–1977",country:"美国",role:"融合爵士乐队",bio:"奇克·科里亚创立的融合名团，早期带巴西色彩，后转向高能电气化。与气象报告、大慈悲管弦乐团并称 1970 年代融合爵士三巨头。"},
  "Sun Ra":{zh:"太阳·拉",born:1914,died:1993,country:"美国",role:"钢琴 · 键盘 · 大乐队领袖",bio:"自称来自土星的宇宙哲人，率领‘阿凯斯特拉’大乐队跨越摇摆、自由爵士与早期电子音乐。华丽的太空戏服与超前的合成器实验，使他成为非洲未来主义的鼻祖。"},
  "Albert Ayler":{zh:"阿尔伯特·艾勒",born:1936,died:1970,country:"美国",role:"次中音萨克斯 · 作曲",bio:"自由爵士最炽烈的呐喊者，用进行曲、灵歌与民谣式旋律包裹尖啸的多重泛音。《Spiritual Unity》如灵魂出窍般狂喜。三十四岁离奇溺亡于东河。"},
  "Antonio Carlos Jobim":{zh:"安东尼奥·卡洛斯·裘宾",born:1927,died:1994,country:"巴西",role:"作曲 · 钢琴 · 吉他",bio:"波萨诺瓦之父，巴西最伟大的作曲家。《伊帕内玛的女孩》《Desafinado》等作品把里约的慵懒阳光写成全世界的旋律，深刻影响了爵士标准曲库。"},
  "Bobby Hutcherson":{zh:"鲍比·哈奇森",born:1941,died:2016,country:"美国",role:"颤音琴 · 马林巴",bio:"把颤音琴从摇摆时代带入现代爵士的革新者，音色晶莹、和声前卫。他参与了多张 Blue Note 前卫经典，《Components》《Dialogue》尽显其作曲胸襟。"},
  "Charlie Haden":{zh:"查理·海登",born:1937,died:2014,country:"美国",role:"贝斯 · 作曲",bio:"奥奈特·科尔曼革命乐队的贝斯基石，把民谣的质朴与政治关怀注入自由爵士。他创立的‘解放音乐管弦乐团’把抗议歌曲谱成宏大编制，深沉而温暖。"},
  "Count Basie":{zh:"康特·贝西",born:1904,died:1984,country:"美国",role:"钢琴 · 大乐队领袖",bio:"摇摆大乐队的两大支柱之一，以堪萨斯城式的强劲律动、精简到极致的钢琴‘点彩’和无与伦比的节奏组著称。他证明：摇摆的秘诀是‘少即是多’。"},
  "Eric Dolphy":{zh:"埃里克·多尔菲",born:1928,died:1964,country:"美国",role:"中音萨克斯 · 低音单簧管 · 长笛",bio:"多管奇才，把跳跃的大音程和近乎说话的‘人声化’语汇带入即兴，是连接硬波普与自由爵士的桥梁。《Out to Lunch!》是前卫爵士的孤峰。三十六岁因误诊糖尿病猝逝。"},
  "Jimmy Smith":{zh:"吉米·史密斯",born:1925,died:2005,country:"美国",role:"哈蒙德风琴",bio:"把哈蒙德 B-3 风琴变成爵士主角的第一人，用脚踏贝斯、滚烫的布鲁斯乐句定义了‘灵魂爵士’的声音，掀起此后席卷酒吧的风琴热潮。"},
  "Stanley Turrentine":{zh:"斯坦利·特伦廷",born:1934,died:2000,country:"美国",role:"次中音萨克斯",bio:"音色温暖、布鲁斯味浓郁的次中音萨克斯手，绰号‘Mr. T’。他与风琴手希尔弗·斯科特等合作的灵魂爵士，是慵懒夜晚的最佳配乐。"},
  "Keith Jarrett":{zh:"基思·贾勒特",born:1945,country:"美国",role:"钢琴 · 作曲",bio:"当代最伟大的即兴钢琴家之一，能把整场独奏会从虚空中即兴成形。《The Köln Concert》是史上最畅销的钢琴独奏专辑；他的‘标准曲三重奏’亦是教科书。2018 年中风后几近无法演奏，留下无尽惋惜。"},
  "Andrew Hill":{zh:"安德鲁·希尔",born:1931,died:2007,country:"美国",role:"钢琴 · 作曲",bio:"Blue Note 阵中最具个性的作曲家之一，音乐结构暧昧、和声游移，介于调性与自由之间。《Point of Departure》是 1960 年代前卫爵士被低估的杰作。"},
  "Cal Tjader":{zh:"卡尔·杰德",born:1925,died:1982,country:"美国",role:"颤音琴 · 拉丁爵士领袖",bio:"非拉美裔却最成功的拉丁爵士领袖之一，以颤音琴的轻盈音色融合曼波、波萨诺瓦与硬波普。《Soul Sauce》让拉丁爵士登上流行榜。"},
  "Chet Baker":{zh:"切特·贝克",born:1929,died:1988,country:"美国",role:"小号 · 演唱",bio:"西海岸冷爵士的忧郁偶像，小号与歌声同样轻柔脆弱、楚楚动人。俊美的外表与毒瘾交织成一段悲剧传奇，最终在阿姆斯特丹坠楼离世。"},
  "Chick Corea":{zh:"奇克·科里亚",born:1941,died:2021,country:"美国",role:"钢琴 · 键盘 · 作曲",bio:"风格百变的钢琴巨匠，从迈尔斯电气乐队到融合名团‘重返永恒’，再到西班牙色彩的原声作品。《Now He Sings, Now He Sobs》《Return to Forever》皆为经典，一生横扫格莱美。"},
  "Coleman Hawkins":{zh:"科尔曼·霍金斯",born:1904,died:1969,country:"美国",role:"次中音萨克斯",bio:"次中音萨克斯的奠基之父，把这件原本不起眼的乐器立为爵士主角。1939 年的《Body and Soul》以大胆的和声即兴预告了比波普的到来。"},
  "Dave Brubeck":{zh:"戴夫·布鲁贝克",born:1920,died:2012,country:"美国",role:"钢琴 · 作曲",bio:"以不规则拍子实验闻名的冷爵士钢琴家。《Time Out》中 5/4 拍的《Take Five》成为史上最畅销的爵士单曲之一，把复杂节拍带进了千家万户。"},
  "Django Reinhardt":{zh:"让戈·莱因哈特",born:1910,died:1953,country:"法国",role:"吉他",bio:"吉普赛爵士的开山祖师，欧洲第一位真正意义上的爵士巨星。一场大火烧伤左手，他却以两根手指创造出令人眩目的吉他技艺，与小提琴手共创‘热力俱乐部五重奏’。"},
  "George Benson":{zh:"乔治·本森",born:1943,country:"美国",role:"吉他 · 演唱",bio:"师承韦斯·蒙哥马利的吉他名家，技艺精湛又极具流行亲和力。1976 年《Breezin'》大获成功，他以吉他与人声同步的‘scat’唱法跨入主流，成为爵士与节奏布鲁斯的桥梁。"},
  "Gerry Mulligan":{zh:"格里·马利根",born:1927,died:1996,country:"美国",role:"上低音萨克斯 · 作曲 · 编曲",bio:"把笨重的上低音萨克斯吹得轻盈如歌的西海岸代表人物。他参与了迈尔斯《Birth of the Cool》的编曲，又以‘无钢琴’的四重奏开创冷爵士的清透织体。"},
  "Kenny Dorham":{zh:"肯尼·多勒姆",born:1924,died:1972,country:"美国",role:"小号 · 作曲",bio:"被严重低估的硬波普小号诗人，音色含蓄抒情。他写下的《Blue Bossa》成为最常被演奏的爵士标准曲之一，作曲才华远胜其生前的名气。"},
  "Lou Donaldson":{zh:"卢·唐纳森",born:1926,died:2024,country:"美国",role:"中音萨克斯",bio:"帕克门徒里布鲁斯味最足的一位，后转向灵魂爵士与放克。《Alligator Boogaloo》律动十足，成为嘻哈采样的常客；他活到九十八岁高龄。"},
  "Louis Armstrong":{zh:"路易斯·阿姆斯特朗",born:1901,died:1971,country:"美国",role:"小号 · 演唱 · 乐队领袖",bio:"爵士史上第一位伟大的独奏家，亲手把这门音乐从集体即兴推向个人表达。沙哑温暖的歌声和‘Hot Five/Seven’的录音奠定了爵士的语言，影响无远弗届。"},
  "Mahavishnu Orchestra":{zh:"大慈悲管弦乐团（Mahavishnu）",life:"活跃 1971–1976",country:"美国",role:"融合爵士乐队",bio:"英国吉他手约翰·麦克劳克林领衔的高能融合名团，把摇滚的音量、印度音乐的灵性与超复杂节拍熔于一炉。《The Inner Mounting Flame》是融合摇滚的炸裂宣言。"},
  "Modern Jazz Quartet":{zh:"现代爵士四重奏",life:"活跃 1952–1974",country:"美国",role:"室内爵士四重奏",bio:"以颤音琴、钢琴、贝斯、鼓的精致编制著称，把巴洛克对位与赋格引入爵士，举止优雅如穿燕尾服演奏。‘第三流派’（Third Stream）的代表，证明了爵士的室内乐潜质。"},
  "Mongo Santamaria":{zh:"蒙戈·圣塔玛利亚",born:1917,died:2003,country:"古巴",role:"康加鼓 · 拉丁爵士领袖",bio:"古巴打击乐大师，把非洲–古巴节奏带入美国爵士主流。他翻奏汉考克的《Watermelon Man》大获成功，让拉丁爵士的律动渗入流行乐。"},
  "Pharoah Sanders":{zh:"法老·桑德斯",born:1940,died:2022,country:"美国",role:"次中音萨克斯",bio:"柯川晚期乐队的灵性搭档，以撕裂般的多重泛音和超验的能量著称。晚年风格转向宁静空灵，2021 年与电子音乐人合作的《Promises》成为绝唱级杰作。"},
  "Sonny Clark":{zh:"桑尼·克拉克",born:1931,died:1963,country:"美国",role:"钢琴 · 作曲",bio:"音色干净、律动摇摆的硬波普钢琴家，深受日本爵士迷崇拜。《Cool Struttin'》是 Blue Note 最受欢迎的专辑之一。三十一岁因毒瘾英年早逝。"},
  "Thelonious Monk":{zh:"塞隆尼斯·蒙克",born:1917,died:1982,country:"美国",role:"钢琴 · 作曲",bio:"爵士史上最独特的作曲家与钢琴家，以不协和音、错落的休止与古怪的触键自成一派。《'Round Midnight》《Straight, No Chaser》是被演奏最多的爵士原创曲，生前被误解，身后封神。"},
  "Wes Montgomery":{zh:"韦斯·蒙哥马利",born:1923,died:1968,country:"美国",role:"吉他",bio:"用大拇指拨弦、以平行八度奏旋律的吉他天才，温暖圆润的音色无人能仿。从硬波普到大获成功的流行跨界，他重新定义了爵士吉他的可能。"},
  "Wynton Marsalis":{zh:"温顿·马萨利斯",born:1961,country:"美国",role:"小号 · 作曲 · 乐队领袖",bio:"古典与爵士双修的小号名家，1980 年代‘新古典主义’（neo-bop）的旗手。作为林肯中心爵士乐团的掌舵人和教育者，他既被尊为传统守护者，也引发不少争议。"},
  "Anthony Braxton":{zh:"安东尼·布拉克斯顿",born:1945,country:"美国",role:"萨克斯 · 作曲 · 理论家",bio:"芝加哥 AACM 出身的前卫巨匠与作曲理论家，以图形化标题和庞杂的体系著称。《For Alto》是史上首张无伴奏中音萨克斯独奏专辑，把即兴推向作曲与哲学的交界。"},
  "Archie Shepp":{zh:"阿奇·谢普",born:1937,country:"美国",role:"次中音萨克斯 · 作曲",bio:"自由爵士的政治良心，把黑人民权抗争、诗歌与布鲁斯的根脉熔铸成炽热的呐喊。《Fire Music》《Attica Blues》既是音乐，也是时代的檄文。"},
  "Art Blakey":{zh:"阿特·布雷基",born:1919,died:1990,country:"美国",role:"鼓 · 乐队领袖",bio:"硬波普的‘发动机’，以雷鸣般的滚奏和标志性的‘press roll’驱动乐队。作为爵士信使的领袖，他三十余年如一日发掘年轻才俊，是爵士史上最伟大的伯乐。"},
  "Art Ensemble of Chicago":{zh:"芝加哥艺术合奏团",life:"活跃 1969 起",country:"美国",role:"前卫爵士乐队",bio:"AACM 旗下最著名的集体，口号是‘从古至今的伟大黑人音乐’。他们涂面彩、用上百件乐器，把自由即兴、戏剧表演与非洲根源融为一场仪式。"},
  "Art Pepper":{zh:"阿特·佩珀",born:1925,died:1982,country:"美国",role:"中音萨克斯",bio:"西海岸冷爵士最动人的中音萨克斯手，抒情中藏着撕裂的痛感。一生与毒瘾、牢狱缠斗，晚年复出愈发炽烈，自传《Straight Life》坦诚得令人心碎。"},
  "Benny Goodman":{zh:"本尼·古德曼",born:1909,died:1986,country:"美国",role:"单簧管 · 大乐队领袖",bio:"‘摇摆之王’，把爵士送上主流舞台的关键人物。1938 年卡内基音乐厅的传奇演出让爵士登堂入室，他也是最早公开起用黑人乐手的白人领班之一。"},
  "Brad Mehldau":{zh:"布拉德·梅尔道",born:1970,country:"美国",role:"钢琴 · 作曲",bio:"当代爵士钢琴的领军人物，以严密的对位、左右手独立的复调思维和对流行歌曲的深度改编著称。他翻奏电台司令与披头士，把爵士三重奏带向新的内省深度。"},
  "Branford Marsalis":{zh:"布兰福德·马萨利斯",born:1960,country:"美国",role:"萨克斯 · 乐队领袖",bio:"马萨利斯家族长子，技艺全面的萨克斯手，游走于硬波普传统与流行跨界之间。他曾任斯汀乐队与电视深夜秀乐队成员，把爵士带给更广的听众。"},
  "Clifford Brown":{zh:"克利福德·布朗",born:1930,died:1956,country:"美国",role:"小号 · 作曲",bio:"硬波普最纯净灿烂的小号声音，技术与抒情兼备，且洁身自好、远离毒品。与鼓手罗奇的五重奏正值巅峰时，他在二十五岁因车祸骤逝，成为爵士史最痛的‘如果’。"},
  "Don Cherry":{zh:"唐·切利",born:1936,died:1995,country:"美国",role:"袖珍小号 · 作曲",bio:"奥奈特·科尔曼革命乐队的小号搭档，自由爵士的核心人物。他更是‘世界音乐’的先驱，融入印度、非洲与中东元素，背着袖珍小号浪迹全球。"},
  "Ella Fitzgerald":{zh:"埃拉·菲茨杰拉德",born:1917,died:1996,country:"美国",role:"演唱",bio:"‘歌曲第一夫人’，音准完美、音色清澈，拟声唱法（scat）无人能及。她录制的《Songbook》系列系统梳理了美国流行歌曲宝库，是爵士演唱的最高标准之一。"},
  "James Scott":{zh:"詹姆斯·斯科特",born:1885,died:1938,country:"美国",role:"钢琴 · 作曲",bio:"与乔普林、约瑟夫·兰姆并称‘古典拉格泰姆三巨头’。他的拉格泰姆技巧繁难、织体华丽，《Grace and Beauty》展现了这门音乐在结构上的精致巅峰。"},
  "Jelly Roll Morton":{zh:"杰利·罗尔·莫顿",born:1890,died:1941,country:"美国",role:"钢琴 · 作曲 · 乐队领袖",bio:"自称‘爵士发明者’的新奥尔良钢琴家，虽夸大其词，却确是第一位伟大的爵士作曲与编曲家。他的‘红辣椒’乐队录音把集体即兴写成了精密的乐章。"},
  "Jimmy Giuffre":{zh:"吉米·朱弗里",born:1921,died:2008,country:"美国",role:"单簧管 · 萨克斯 · 作曲",bio:"安静的革新者，从西海岸冷爵士的室内乐写作，一路走到 1960 年代无鼓、近乎室内乐的自由即兴三重奏。《Free Fall》在当时无人问津，如今被奉为先知之作。"},
  "Joe Lovano":{zh:"乔·洛瓦诺",born:1952,country:"美国",role:"次中音萨克斯 · 作曲",bio:"当代次中音萨克斯的多面手，音色厚重、根基扎实又乐于实验。他扎根传统却不断与前卫对话，是 1990 年代以来 Blue Note 的中流砥柱。"},
  "Joshua Redman":{zh:"约书亚·雷德曼",born:1969,country:"美国",role:"次中音萨克斯 · 作曲",bio:"哈佛毕业却选择音乐的当代萨克斯明星，音色圆熟、旋律感极强。作为萨克斯名宿杜威·雷德曼之子，他成为 1990 年代爵士复兴的青年门面。"},
  "Lester Young":{zh:"莱斯特·扬",born:1909,died:1959,country:"美国",role:"次中音萨克斯",bio:"绰号‘Prez’（总统），以轻盈飘逸、旋律优先的乐句颠覆了霍金斯式的厚重传统，直接启发了冷爵士与比波普。他与歌手比莉·哈乐黛的合作堪称天作之合。"},
  "Lionel Hampton":{zh:"莱昂内尔·汉普顿",born:1908,died:2002,country:"美国",role:"颤音琴 · 大乐队领袖",bio:"把颤音琴确立为爵士独奏乐器的第一人，也是古德曼乐队打破种族界限的成员。他领衔的大乐队活力四射，舞台魅力延续了半个多世纪。"},
  "Pat Metheny":{zh:"帕特·麦席尼",born:1954,country:"美国",role:"吉他 · 作曲",bio:"当代最受欢迎的爵士吉他家，音色温暖辽阔，融合美国乡村的开阔感与巴西节奏。从前卫即兴到电影配乐式的大编制，他几乎拿遍了爵士格莱美。"},
  "Pat Metheny Group":{zh:"帕特·麦席尼乐队",life:"活跃 1977–2010s",country:"美国",role:"现代爵士乐队",bio:"麦席尼与键盘手莱尔·梅斯共同主导的招牌乐队，以辽阔的音景、合成吉他与世界音乐织体著称。《Still Life (Talking)》《Letter from Home》定义了一种‘电影感’的当代爵士。"},
  "Roy Hargrove":{zh:"罗伊·哈格罗夫",born:1969,died:2018,country:"美国",role:"小号 · 作曲",bio:"新生代硬波普的杰出代表，音色甜美、根基深厚，又积极拥抱嘻哈与新灵魂乐。他的 RH Factor 项目连接了爵士与当代黑人流行乐，四十九岁因肾病早逝令人扼腕。"},
  "Sergio Mendes":{zh:"塞尔吉奥·门德斯",born:1941,died:2024,country:"巴西",role:"钢琴 · 乐队领袖",bio:"把巴西波萨诺瓦与桑巴包装成全球流行的关键推手。其‘Brasil '66’乐队翻唱的《Mas Que Nada》风靡世界，让巴西节奏成为几代人的夏日记忆。"},
  "Sidney Bechet":{zh:"西德尼·贝谢",born:1897,died:1959,country:"美国",role:"高音萨克斯 · 单簧管",bio:"新奥尔良早期的传奇，把高音萨克斯立为独奏乐器的先驱，颤音宽阔而炽烈。他与阿姆斯特朗同为最早的伟大独奏家，晚年在法国被奉为国宝级人物。"},
  "Sonny Stitt":{zh:"桑尼·斯蒂特",born:1924,died:1982,country:"美国",role:"中音/次中音萨克斯",bio:"比波普语汇最流利的传人之一，一生背负‘帕克模仿者’的标签，遂转攻次中音以自立门户。无论何时何地都能即兴如流，是巡演舞台上的常胜将军。"},
  "Stanley Clarke":{zh:"斯坦利·克拉克",born:1951,country:"美国",role:"电贝斯 · 原声贝斯 · 作曲",bio:"融合爵士时代把贝斯推上独奏前台的先锋，‘重返永恒’的核心成员。他炫目的电贝斯技巧重新定义了这件乐器的角色，《School Days》成为贝斯手的必修课。"},
  "Wardell Gray":{zh:"沃德尔·格雷",born:1921,died:1955,country:"美国",role:"次中音萨克斯",bio:"连接摇摆与比波普的次中音好手，乐句流畅、布鲁斯味浓，与德克斯特·戈登的‘萨克斯对决’录音风靡一时。三十四岁离奇横死于沙漠，至今成谜。"},

  "Art Tatum":{zh:"阿特·塔图姆",born:1909,died:1956,country:"美国",role:"钢琴",bio:"公认技术最华丽的爵士钢琴家，几近全盲却以惊人的速度、繁复的和声重新装点旋律，连古典大师都为之叹服。"},
  "Earl Hines":{zh:"厄尔·海因斯",born:1903,died:1983,country:"美国",role:"钢琴",bio:"现代爵士钢琴的奠基者之一，以‘小号式’右手单音线条突破早期的节奏型弹法，与阿姆斯特朗的合作堪称经典。"},
  "Fats Waller":{zh:"法茨·沃勒",born:1904,died:1943,country:"美国",role:"钢琴 · 演唱 · 作曲",bio:"‘跨步钢琴’（stride）大师与天才词曲作者，以诙谐演唱与华丽左手风靡一时，《Ain't Misbehavin'》传唱至今。"},
  "Teddy Wilson":{zh:"泰迪·威尔逊",born:1912,died:1986,country:"美国",role:"钢琴",bio:"摇摆时代最优雅的钢琴家，古德曼三重奏成员（最早打破种族界限的组合之一），是哈乐黛经典录音的灵魂搭档。"},
  "Fletcher Henderson":{zh:"弗莱彻·亨德森",born:1897,died:1952,country:"美国",role:"编曲 · 大乐队领袖",bio:"大乐队编曲的奠基者，把铜管与簧管分声部对答的写法立为摇摆范式，他为古德曼所写的编曲点燃了整个摇摆时代。"},
  "Eddie Condon":{zh:"埃迪·康登",born:1905,died:1973,country:"美国",role:"班卓琴 · 吉他 · 乐队领袖",bio:"芝加哥风格迪克西兰的核心组织者，以连珠炮般的现场与热爵士聚会闻名，是传统爵士的旗手。"},
  "Red Norvo":{zh:"瑞德·诺沃",born:1908,died:1999,country:"美国",role:"颤音琴 · 木琴",bio:"最早把木琴／颤音琴立为爵士独奏乐器的先驱，其无鼓三重奏轻盈精巧，是冷爵士室内乐的早期雏形。"},
  "Bessie Smith":{zh:"贝西·史密斯",born:1894,died:1937,country:"美国",role:"演唱",bio:"‘布鲁斯皇后’，1920 年代最伟大的女歌手，嗓音雄浑深情，把古典布鲁斯唱进了爵士的血脉。"},
  "Billie Holiday":{zh:"比莉·哈乐黛",born:1915,died:1959,country:"美国",role:"演唱",bio:"‘Lady Day’，爵士演唱史上最具感染力的声音，以独特的节奏处理把歌词唱成自传；《Strange Fruit》是控诉私刑的不朽之作。"},

  "Fats Navarro":{zh:"法茨·纳瓦罗",born:1923,died:1950,country:"美国",role:"小号",bio:"比波普小号的关键人物，音色饱满圆润、乐句典雅，是克利福德·布朗等后辈的直接楷模，二十六岁因肺结核与毒瘾早逝。"},
  "Max Roach":{zh:"马克斯·罗奇",born:1924,died:2007,country:"美国",role:"鼓 · 作曲",bio:"比波普鼓的奠基人，把鼓从单纯节拍提升为旋律性的对话。政治意识强烈，《We Insist!》是民权运动的鼓上宣言。"},
  "Clifford Brown & Max Roach":{zh:"克利福德·布朗与马克斯·罗奇",life:"活跃 1954–1956",country:"美国",role:"硬波普五重奏",bio:"小号手布朗与鼓手罗奇共同领衔的传奇五重奏，是硬波普的完美范本，因布朗 1956 年车祸骤逝而戛然而止。"},
  "Hampton Hawes":{zh:"汉普顿·霍斯",born:1928,died:1977,country:"美国",role:"钢琴",bio:"西海岸比波普钢琴的代表，乐句明快、布鲁斯感强烈，是帕克体系在钢琴上最自然的延伸之一。"},
  "Shorty Rogers":{zh:"肖蒂·罗杰斯",born:1924,died:1994,country:"美国",role:"小号 · 编曲",bio:"西海岸冷爵士的核心组织者与编曲家，把比波普语汇编织成清爽明亮的加州声音。"},
  "Charlie Byrd":{zh:"查理·伯德",born:1925,died:1999,country:"美国",role:"吉他",bio:"指弹古典吉他出身的爵士吉他手，与斯坦·盖茨合作的《Jazz Samba》把巴西波萨诺瓦引入美国，掀起热潮。"},
  "Curtis Counce":{zh:"柯蒂斯·康斯",born:1926,died:1963,country:"美国",role:"贝斯 · 乐队领袖",bio:"西海岸硬波普的贝斯手与领袖，其五重奏录音强劲而被低估，是 1950 年代洛杉矶爵士硬朗的一面。"},
  "Gene Ammons":{zh:"吉恩·阿蒙斯",born:1925,died:1974,country:"美国",role:"次中音萨克斯",bio:"绰号‘Jug’，音色宽厚多情的次中音大师，是灵魂爵士与‘对吹’（tenor battle）传统的代表，布鲁斯味十足。"},
  "Johnny Griffin":{zh:"约翰尼·格里芬",born:1928,died:2008,country:"美国",role:"次中音萨克斯",bio:"绰号‘小巨人’，以惊人速度著称的硬波普萨克斯手，与蒙克合作的现场录音淋漓尽致，后旅居欧洲。"},
  "Blue Mitchell":{zh:"布鲁·米切尔",born:1930,died:1979,country:"美国",role:"小号",bio:"音色温暖明亮的硬波普小号手，长期搭档霍勒斯·西尔弗，独奏作品布鲁斯味十足、亲切耐听。"},
  "Ike Quebec":{zh:"艾克·魁北克",born:1918,died:1963,country:"美国",role:"次中音萨克斯",bio:"音色温暖醇厚的次中音萨克斯手，也是 Blue Note 的星探，晚期《Blue and Sentimental》尽显其抒情之美。"},
  "Tina Brooks":{zh:"蒂娜·布鲁克斯",born:1932,died:1974,country:"美国",role:"次中音萨克斯 · 作曲",bio:"被严重低估的硬波普作曲家与萨克斯手（本名 Harold，‘Tina’为绰号），《True Blue》是 Blue Note 的隐藏珍宝，生前大量录音未能发行。"},
  "Horace Parlan":{zh:"霍勒斯·帕兰",born:1931,died:2017,country:"美国",role:"钢琴",bio:"幼年小儿麻痹使右手受限，他却发展出独特的左手主导、布鲁斯味浓郁的钢琴风格，是明格斯乐队与 Blue Note 的可靠基石。"},
  "Red Garland":{zh:"瑞德·加兰",born:1923,died:1984,country:"美国",role:"钢琴",bio:"迈尔斯第一伟大五重奏的钢琴手，以晶莹的‘块状和弦’与优雅律动著称，是 1950 年代硬波普钢琴的标志音色。"},
  "Paul Chambers":{zh:"保罗·钱伯斯",born:1935,died:1969,country:"美国",role:"贝斯",bio:"迈尔斯第一伟大五重奏的贝斯基石，以稳健的行走低音和开创性的拉弓独奏著称，《Kind of Blue》等无数经典皆有他坐镇。"},
  "Philly Joe Jones":{zh:"费城乔·琼斯",born:1923,died:1985,country:"美国",role:"鼓",bio:"迈尔斯第一伟大五重奏的鼓手，以标志性的‘鼓边敲击’和强劲律动推动乐队，是硬波普鼓的典范。"},
  "The Three Sounds":{zh:"三重音（乐队）",life:"活跃 1956–1970s",country:"美国",role:"灵魂爵士三重奏",bio:"以钢琴手吉恩·哈里斯为核心的三重奏，亲切讨喜的布鲁斯律动，是 Blue Note 灵魂爵士最受欢迎的声音之一。"},

  "Lee Konitz":{zh:"李·科尼茨",born:1927,died:2020,country:"美国",role:"中音萨克斯",bio:"冷爵士的独立声音，师从特里斯塔诺，以清冷干燥的音色和不断重塑旋律的态度自成一格，七十年如一日地探索。"},
  "Phil Woods":{zh:"菲尔·伍兹",born:1931,died:2015,country:"美国",role:"中音萨克斯",bio:"帕克衣钵最杰出的传人之一，炽热流畅、根基扎实，也以比利·乔尔《Just the Way You Are》的萨克斯独奏为大众所知。"},
  "Rahsaan Roland Kirk":{zh:"拉桑·罗兰·柯克",born:1935,died:1977,country:"美国",role:"萨克斯 · 多管齐奏",bio:"失明的奇才，能同时吹奏三支管乐器，并以循环呼吸不间断演奏，把马戏般的技艺与深厚的爵士传统熔于一炉。"},
  "Grachan Moncur III":{zh:"格拉昌·蒙库尔三世",born:1937,died:2022,country:"美国",role:"长号 · 作曲",bio:"前卫长号手与作曲家，游走于硬波普与自由爵士之间，《Evolution》是 1960 年代 Blue Note 前卫浪潮中被低估的杰作。"},
  "Marion Brown":{zh:"马里恩·布朗",born:1931,died:2010,country:"美国",role:"中音萨克斯",bio:"自由爵士的抒情声音，参与了柯川的《Ascension》，其作品却更偏向温柔的田园冥想，《Afternoon of a Georgia Faun》别具一格。"},
  "Sam Rivers":{zh:"萨姆·里弗斯",born:1923,died:2011,country:"美国",role:"萨克斯 · 长笛 · 作曲",bio:"前卫多管乐手与作曲家，1970 年代纽约‘阁楼爵士’运动的核心，作品兼具自由的能量与缜密的结构。"},
  "Paul Bley":{zh:"保罗·布雷",born:1932,died:2016,country:"加拿大",role:"钢琴",bio:"自由爵士钢琴的先知，最早演绎奥奈特·科尔曼乐曲的人之一，又是最早拥抱合成器的爵士钢琴家，录音满是空间与留白。"},
  "Alice Coltrane":{zh:"爱丽丝·柯川",born:1937,died:2007,country:"美国",role:"钢琴 · 竖琴 · 作曲",bio:"约翰·柯川的遗孀与音乐伙伴，以竖琴与管风琴营造灵性氛围，把印度灵修与自由爵士融为冥想之声，《Journey in Satchidananda》是代表作。"},
  "Air":{zh:"空气（乐队）",life:"活跃 1971–1986",country:"美国",role:"前卫爵士三重奏",bio:"由亨利·思雷吉尔领衔的前卫三重奏，把拉格泰姆、布鲁斯与自由即兴重新拼贴，《Air Lore》以现代手法重读乔普林与莫顿。"},

  "Sarah Vaughan":{zh:"莎拉·沃恩",born:1924,died:1990,country:"美国",role:"演唱",bio:"绰号‘神音’（Sassy），拥有歌剧般音域与器乐化即兴能力的爵士女声，把每首歌都唱成华丽炫技与深情的并存。"},
  "Carmen McRae":{zh:"卡门·麦克雷",born:1920,died:1994,country:"美国",role:"演唱",bio:"以精准咬字、钢琴家般的乐句和略带辛辣的诠释著称的爵士女声，与菲茨杰拉德、沃恩并称同代三大歌后。"},
  "Nat King Cole":{zh:"纳特·金·科尔",born:1919,died:1965,country:"美国",role:"演唱 · 钢琴",bio:"先是顶尖的爵士钢琴三重奏领袖，后以丝绒般的嗓音成为流行巨星，钢琴影响了一代人，歌声则跨越了种族藩篱。"},
  "Frank Sinatra":{zh:"弗兰克·辛纳屈",born:1915,died:1998,country:"美国",role:"演唱",bio:"二十世纪最伟大的流行／爵士男声，以无可挑剔的乐句与叙事感重新定义了‘演唱专辑’，与里德尔合作的作品是美国歌曲的巅峰。"},
  "Mel Tormé":{zh:"梅尔·托梅",born:1925,died:1999,country:"美国",role:"演唱 · 作曲",bio:"绰号‘天鹅绒之雾’，以丝滑音色和高超拟声唱法著称的男声，也是《The Christmas Song》的作者。"},

  "Tony Williams":{zh:"托尼·威廉姆斯",born:1945,died:1997,country:"美国",role:"鼓",bio:"十七岁加入迈尔斯第二伟大五重奏的鼓坛神童，以爆发力与自由的节奏概念革新了爵士鼓，后创立融合名团 Lifetime。"},
  "Jaco Pastorius":{zh:"雅科·帕斯托留斯",born:1951,died:1987,country:"美国",role:"电贝斯",bio:"史上最具革命性的电贝斯手，以无品贝斯的歌唱音色、泛音与和弦彻底改写了这件乐器，气象报告时期达到巅峰，三十五岁悲剧离世。"},
  "Billy Cobham":{zh:"比利·科巴姆",born:1944,country:"美国",role:"鼓",bio:"大慈悲管弦乐团的鼓手，以双底鼓的雷霆技巧与精准的复杂节拍定义了融合爵士的鼓语言，《Spectrum》是鼓手必听。"},
  "John McLaughlin":{zh:"约翰·麦克劳克林",born:1942,country:"英国",role:"吉他",bio:"融合爵士吉他的旗手，参与迈尔斯电气乐队、创立大慈悲管弦乐团，又以原声三重奏 Shakti 融合印度古典，是横跨多种传统的吉他思想家。"},
  "Larry Coryell":{zh:"拉里·科里尔",born:1943,died:2017,country:"美国",role:"吉他",bio:"被誉为‘融合教父’的吉他先驱，最早把摇滚能量与爵士即兴结合，为后来的融合吉他铺平道路。"},
  "Al Di Meola":{zh:"阿尔·迪·梅奥拉",born:1954,country:"美国",role:"吉他",bio:"以惊人速度与拉丁／地中海色彩著称的融合吉他名家，‘重返永恒’成员，与麦克劳克林、德卢西亚的原声吉他三重奏风靡一时。"},
  "Jean-Luc Ponty":{zh:"让-吕克·庞蒂",born:1942,country:"法国",role:"小提琴",bio:"把电小提琴带入融合爵士的先驱，曾效力扎帕与大慈悲管弦乐团，以效果器处理的滑亮音色开拓了弦乐在爵士中的新角色。"},
  "Jeff Beck":{zh:"杰夫·贝克",born:1944,died:2023,country:"英国",role:"吉他",bio:"摇滚吉他巨匠，1970 年代以《Blow by Blow》转向器乐融合，用拨片与摇把唱出人声般的乐句，跨界影响深远。"},
  "Airto":{zh:"艾尔托·莫雷拉",born:1941,country:"巴西",role:"打击乐",bio:"巴西打击乐大师，把繁复的巴西节奏与人声效果带入迈尔斯电气乐队与‘重返永恒’，是融合爵士不可或缺的色彩。"},
  "Grover Washington Jr.":{zh:"格罗弗·华盛顿（小）",born:1943,died:1999,country:"美国",role:"萨克斯",bio:"流畅爵士（smooth jazz）的奠基人之一，《Winelight》中的《Just the Two of Us》成为跨界金曲，把爵士萨克斯带入千家万户。"},

  "João Gilberto":{zh:"若昂·吉尔贝托",born:1931,died:2019,country:"巴西",role:"演唱 · 吉他",bio:"波萨诺瓦之父之一，以近乎耳语的演唱和独创的切分吉他节奏（batida）定义了这种音乐，《Getz/Gilberto》让它风靡全球。"},
  "Stan Getz & João Gilberto":{zh:"斯坦·盖茨与若昂·吉尔贝托",life:"录于 1963",country:"美国／巴西",role:"波萨诺瓦合作",bio:"萨克斯手盖茨与巴西吉他歌手吉尔贝托的历史性合作，《Getz/Gilberto》把波萨诺瓦推向全球，《伊帕内玛的女孩》成为永恒标准曲。"},
  "Milton Nascimento":{zh:"米尔顿·纳西门托",born:1942,country:"巴西",role:"演唱 · 作曲",bio:"巴西音乐的灵魂人物，空灵的假声与米纳斯山区的旋律深深打动了韦恩·肖特等大师，合作专辑《Native Dancer》是跨界经典。"},
  "Gato Barbieri":{zh:"加托·巴比耶里",born:1932,died:2016,country:"阿根廷",role:"次中音萨克斯",bio:"阿根廷萨克斯手，以撕裂炽热的音色把自由爵士与拉美民族色彩结合，电影《巴黎最后的探戈》配乐让他名声大噪。"},
  "Eddie Palmieri":{zh:"埃迪·帕尔米耶里",born:1936,country:"美国",role:"钢琴 · 拉丁爵士领袖",bio:"波多黎各裔的萨尔萨与拉丁爵士巨匠，以激烈的蒙图诺钢琴和先锋编曲把拉丁律动推向新高度，多次问鼎格莱美。"},
  "Tito Puente":{zh:"蒂托·普恩特",born:1923,died:2000,country:"美国",role:"定音鼓 · 拉丁爵士领袖",bio:"‘曼波之王’，波多黎各裔的定音鼓（timbales）大师，把拉丁爵士与曼波推向主流，《Oye Como Va》经桑塔纳翻唱风靡世界。"},
  "Ray Barretto":{zh:"雷·巴雷托",born:1929,died:2007,country:"美国",role:"康加鼓 · 拉丁爵士领袖",bio:"波多黎各裔的康加鼓大师，是无数硬波普名盘的打击乐手，也以萨尔萨与拉丁爵士乐队闻名，《Acid》是拉丁灵魂的经典。"},

  "Vince Guaraldi":{zh:"文斯·瓜拉尔迪",born:1928,died:1976,country:"美国",role:"钢琴 · 作曲",bio:"以《花生漫画》动画配乐家喻户晓的旧金山钢琴家，《Linus and Lucy》旋律深入人心，把爵士钢琴的温情带给了几代人。"},
  "Ramsey Lewis":{zh:"拉姆齐·刘易斯",born:1935,died:2022,country:"美国",role:"钢琴",bio:"把爵士钢琴三重奏带上流行榜的灵魂爵士名家，《The In Crowd》大获成功，亲切的律动让爵士走向更广的听众。"},
  "Kenny Burrell":{zh:"肯尼·布雷尔",born:1931,country:"美国",role:"吉他",bio:"音色温暖、品味无瑕的爵士吉他典范，艾灵顿最爱的吉他手，《Midnight Blue》是布鲁斯味爵士吉他的标杆。"},
  "Kenny Barron":{zh:"肯尼·巴伦",born:1943,country:"美国",role:"钢琴",bio:"当代最受敬重的爵士钢琴大师与教育家，触键优雅、和声丰盈，是无数经典录音的中流砥柱与年轻乐手的导师。"},
  "Roy Haynes":{zh:"罗伊·海恩斯",born:1925,died:2024,country:"美国",role:"鼓",bio:"横跨七十余年的鼓坛常青树，从帕克、蒙克到柯川都有他的鼓声，律动灵动现代，是连接各时代的活历史，享年九十九岁。"},

  "Tom Harrell":{zh:"汤姆·哈雷尔",born:1946,country:"美国",role:"小号 · 短号 · 作曲",bio:"音色温润、抒情深邃的小号大师与作曲家，长年与精神分裂症共处，舞台下静默、举号即化为最动人的乐句。"},
  "Marcus Roberts":{zh:"马库斯·罗伯茨",born:1963,country:"美国",role:"钢琴",bio:"失明的钢琴家，温顿·马萨利斯乐队的早期成员，深耕拉格泰姆、跨步与早期爵士传统，并以全新方式重构三重奏的角色。"},
  "Terence Blanchard":{zh:"特伦斯·布兰查德",born:1962,country:"美国",role:"小号 · 作曲",bio:"新奥尔良的小号手与电影配乐大师，长期为斯派克·李配乐，又是首位作品登上大都会歌剧院的非裔作曲家。"},
  "Nicholas Payton":{zh:"尼古拉斯·佩顿",born:1973,country:"美国",role:"小号",bio:"新奥尔良出身的小号多面手，技艺精湛又勇于争论，提出以‘BAM（黑人美国音乐）’重新命名爵士，是当代最具思辨性的乐手之一。"},
  "Christian McBride":{zh:"克里斯蒂安·麦克布莱德",born:1972,country:"美国",role:"贝斯 · 乐队领袖",bio:"当代最炙手可热的贝斯手与乐队领袖，技艺全面、律动扎实，横跨原声爵士、放克与跨界合作，多次斩获格莱美。"},
  "Diana Krall":{zh:"戴安娜·克瑞儿",born:1964,country:"加拿大",role:"演唱 · 钢琴",bio:"当代最畅销的爵士女声之一，慵懒低回的嗓音与扎实的钢琴功底相得益彰，把标准曲唱得既经典又亲密。"},
  "Cassandra Wilson":{zh:"卡桑德拉·威尔逊",born:1955,country:"美国",role:"演唱",bio:"低沉烟嗓的当代爵士女声，把布鲁斯、民谣与流行重新编织成幽暗性感的声景，《Blue Light 'Til Dawn》开创了一种新的演唱美学。"},
  "Kenny G":{zh:"肯尼·基",born:1956,country:"美国",role:"高音萨克斯",bio:"史上最畅销的器乐演奏家，流畅爵士的标志人物。尽管在爵士圈饱受争议，他甜美悠长的高音萨克斯却是无数人的入门旋律。"},
  "Spyro Gyra":{zh:"Spyro Gyra（乐队）",life:"活跃 1974 起",country:"美国",role:"流畅爵士乐队",bio:"流畅爵士／融合的长青乐队，旋律明快、制作精良，《Morning Dance》是这一风格的代表作。"},

  "Kenny Garrett":{zh:"肯尼·加勒特",born:1960,country:"美国",role:"中音萨克斯 · 作曲",bio:"迈尔斯晚期乐队的中音萨克斯手，音色炽烈、律动强劲，融合放克与世界节奏，是当代最具能量的萨克斯之声。"},
  "Joseph Lamb":{zh:"约瑟夫·兰姆",born:1887,died:1960,country:"美国",role:"作曲 · 钢琴",bio:"‘古典拉格泰姆三巨头’中唯一的白人，也是乔普林的门生，作品结构精致、和声丰富，为拉格泰姆增添了细腻的抒情色彩。"},
  "Quincy Jones":{zh:"昆西·琼斯",born:1933,died:2024,country:"美国",role:"编曲 · 制作 · 乐队领袖",bio:"从比波普编曲家到流行音乐巨擘的传奇，制作了迈克尔·杰克逊《Thriller》；他的爵士大乐队作品同样气派非凡，影响横跨半个世纪。"},

  "Cecile McLorin Salvant":{zh:"塞西尔·麦克洛林·萨尔万特",born:1989,country:"美国",role:"演唱",bio:"当代最受瞩目的爵士女声，音域宽广、戏剧性十足，擅长挖掘被遗忘的老歌并赋予机智的当代解读，已数获格莱美。"},
  "Esperanza Spalding":{zh:"埃斯佩兰萨·斯波尔丁",born:1984,country:"美国",role:"贝斯 · 演唱 · 作曲",bio:"集贝斯、演唱与作曲于一身的天才，2011 年击败众多流行巨星夺得格莱美最佳新人，把爵士、灵魂与艺术流行熔于一炉。"},
  "Robert Glasper":{zh:"罗伯特·格拉斯珀",born:1978,country:"美国",role:"钢琴 · 制作",bio:"连接爵士与新灵魂、嘻哈的关键人物，《Black Radio》系列屡获格莱美，重新定义了爵士与当代黑人流行乐的关系。"},
  "Vijay Iyer":{zh:"维杰·艾耶尔",born:1971,country:"美国",role:"钢琴 · 作曲",bio:"印度裔的钢琴家与作曲家，物理学博士出身，以节奏的数学结构和跨文化视野著称，是当代最具知识分子气质的爵士声音之一。"},
  "Christian Scott":{zh:"克里斯蒂安·斯科特",born:1983,country:"美国",role:"小号 · 作曲",bio:"新奥尔良出身的小号革新者（又名 aTunde Adjuah），以‘伸展音乐’理念融合嘻哈、电子与各族裔节奏，是当代爵士的先锋之声。"},
  "Makaya McCraven":{zh:"马卡亚·麦克雷文",born:1983,country:"美国",role:"鼓 · 制作",bio:"芝加哥的鼓手兼制作人，把现场即兴录音剪辑重组为嘻哈式的‘节拍科学’，是当代爵士与采样文化交汇处的代表。"},
  "Kamasi Washington":{zh:"卡马西·华盛顿",born:1981,country:"美国",role:"次中音萨克斯 · 作曲",bio:"洛杉矶的萨克斯巨匠，以宏大编制、灵性氛围与嘻哈血脉掀起新一代爵士复兴，三小时巨制《The Epic》是当代爵士的现象级作品。"},

  "Snarky Puppy":{zh:"Snarky Puppy（乐队）",life:"活跃 2004 起",country:"美国",role:"融合爵士集体",bio:"由迈克尔·里格领衔的大型器乐集体，融合放克、世界音乐与融合爵士，以高能现场和多次格莱美把器乐爵士带给年轻一代。"},
  "BadBadNotGood":{zh:"BadBadNotGood（乐队）",life:"活跃 2010 起",country:"加拿大",role:"爵士／嘻哈乐队",bio:"多伦多的年轻四人组，从翻奏嘻哈节拍起家，把爵士、放克与电子嫁接，常与说唱歌手合作，是新一代跨界爵士的代表。"},
  "GoGo Penguin":{zh:"GoGo Penguin（乐队）",life:"活跃 2009 起",country:"英国",role:"原声电子三重奏",bio:"曼彻斯特的钢琴三重奏，以电子舞曲式的律动、极简主义动机和缜密编排打造‘原声电子’声音，深受新生代听众喜爱。"},
  "The Cinematic Orchestra":{zh:"电影感管弦乐团（乐队）",life:"活跃 1999 起",country:"英国",role:"爵士／电子乐队",bio:"杰森·斯温斯科领衔的英国乐团，把爵士现场与电子制作、弦乐编排融成电影般的氛围，《To Build a Home》广为流传。"},
  "Jazzanova":{zh:"Jazzanova（乐队）",life:"活跃 1995 起",country:"德国",role:"Nu-Jazz 制作团体",bio:"柏林的 DJ／制作人集体，是 2000 年代‘新爵士’（nu-jazz）与浩室爵士的代表，把碎拍、桑巴与灵魂乐缝合成都市夜色。"},
  "St Germain":{zh:"圣日耳曼",born:1969,country:"法国",role:"浩室爵士制作人",bio:"法国制作人卢多维克·纳瓦尔的化名，把深浩室、爵士采样与布鲁斯缝合，《Tourist》是‘house 爵士’的里程碑。"},
  "Sons of Kemet":{zh:"Sons of Kemet（乐队）",life:"活跃 2011–2023",country:"英国",role:"新爵士乐队",bio:"萨克斯手沙巴卡·哈钦斯领衔的伦敦四人组，编制为萨克斯、大号与双鼓，把加勒比律动与政治呐喊熔成炽热的现场能量。"},
  "Ezra Collective":{zh:"以斯拉合奏团（乐队）",life:"活跃 2012 起",country:"英国",role:"新爵士乐队",bio:"伦敦新爵士浪潮的领军乐队，融合 Afrobeat、雷鬼与嘻哈的炽热律动，2023 年凭《Where I'm Meant to Be》成为首支夺得水星奖的爵士专辑。"},
  "Nubya Garcia":{zh:"努比亚·加西亚",born:1991,country:"英国",role:"次中音萨克斯",bio:"伦敦新爵士浪潮的代表萨克斯手，把加勒比、Afrobeat 与精神爵士的根脉编织进深沉宽广的音色，《Source》广受赞誉。"}
};
