/* 1001 Jazz — 艺术家小传数据
 * 键 = 专辑数据里的英文 artist 字符串（务必完全一致）。
 * 字段：zh 译名 · born/died 生卒（在世者省略 died；乐队改用 life 活跃年）
 *       country 国别 · role 身份/乐器 · bio 中文小传。
 * 缺省优雅降级：没有词条的艺术家仍正常显示作品列表，只是不显示小传卡。
 */
window.ARTIST_BIOS = {
  "Miles Davis":{zh:"迈尔斯·戴维斯",born:1926,died:1991,country:"美国",role:"小号 · 作曲 · 乐队领袖",bio:"二十世纪最重要的爵士革新者，没有之一。从比波普到冷爵士、调式爵士、再到电气化融合，他一次次亲手推翻自己缔造的风格，把整支乐队带向下一个时代。《Kind of Blue》《Bitches Brew》是两座永远绕不开的里程碑。"},
  "John Coltrane":{zh:"约翰·柯川",born:1926,died:1967,country:"美国",role:"萨克斯 · 作曲",bio:"用十年时间把萨克斯吹成一种灵性追问。从硬波普的‘音墙’到《A Love Supreme》的虔诚祈祷，再到晚期自由爵士的狂喜，他把即兴推向技术与精神的双重极限，深刻影响了此后所有管乐手。"},
  "Herbie Hancock":{zh:"赫比·汉考克",born:1940,country:"美国",role:"钢琴 · 键盘 · 作曲",bio:"从迈尔斯五重奏的和声魔术师，到《Maiden Voyage》的现代经典，再到放克、电子与嘻哈的弄潮儿，他始终站在爵士与流行的交界处。一曲《Rockit》让黑胶刮碟登上主流舞台。"},
  "Hank Mobley":{zh:"汉克·莫布利",born:1930,died:1986,country:"美国",role:"次中音萨克斯 · 作曲",bio:"被乐评家形容为‘次中音萨克斯里的中量级冠军’——音色不张扬却分寸极佳。他是 Blue Note 硬波普的中坚，《Soul Station》被公认为最圆熟的硬波普专辑之一。"},
  "Lee Morgan":{zh:"李·摩根",born:1938,died:1972,country:"美国",role:"小号 · 作曲",bio:"硬波普时代最炽热的小号天才，十八岁已是录音室常客。《The Sidewinder》的灵魂爵士律动让 Blue Note 大卖。三十三岁在纽约俱乐部台前被情人枪杀，生涯戛然而止。"},
  "Sonny Rollins":{zh:"桑尼·罗林斯",born:1930,country:"美国",role:"次中音萨克斯 · 作曲",bio:"‘萨克斯巨人’，以无伴奏独奏的叙事能力和对主题的即兴重构著称。《Saxophone Colossus》中的《St. Thomas》尽显其加勒比节奏底色。曾两度隐退苦修，留下在威廉斯堡大桥上独练的传奇。"},
  "Weather Report":{zh:"气象报告（乐队）",life:"活跃 1970–1986",country:"美国",role:"融合爵士乐队",bio:"由键盘手乔·扎维努尔与萨克斯手韦恩·肖特创立，是融合爵士的旗舰。贝斯手雅科·帕斯托留斯加入后达到巅峰，《Heavy Weather》中的《Birdland》成为跨界标准曲。"},
  "Duke Ellington":{zh:"杜克·艾灵顿",born:1899,died:1974,country:"美国",role:"钢琴 · 作曲 · 大乐队领袖",bio:"美国音乐史上最伟大的作曲家之一，把大乐队当作自己的‘乐器’写了半个世纪。他为每位团员量身定制声部，《Ellington at Newport》的现场更点燃了爵士复兴。"},
  "Ornette Coleman":{zh:"奥奈特·科尔曼",born:1930,died:2015,country:"美国",role:"中音萨克斯 · 作曲",bio:"自由爵士的开创者。1959 年的《The Shape of Jazz to Come》抛开固定和弦框架，提出‘和声旋律’（harmolodics）理念，一度引发巨大争议，却永久改变了即兴的可能性。"},
  "Bud Powell":{zh:"巴德·鲍威尔",born:1924,died:1966,country:"美国",role:"钢琴 · 作曲",bio:"把帕克式比波普语汇移植到钢琴上的第一人，右手单音线条快如疾风，左手只点和弦。他奠定了现代爵士钢琴的范式，却一生饱受精神疾病与电击治疗之苦。"},
  "Charlie Parker":{zh:"查理·帕克",born:1920,died:1955,country:"美国",role:"中音萨克斯 · 作曲",bio:"绰号‘大鸟’（Bird），比波普革命的灵魂人物。他以闪电般的速度、复杂的和声替换重写了即兴语言，影响延续至今。三十四岁早逝时，验尸官误判其年龄超过五十。"},
  "Dexter Gordon":{zh:"德克斯特·戈登",born:1923,died:1990,country:"美国",role:"次中音萨克斯",bio:"把帕克的比波普语言带入次中音萨克斯的关键人物，音色宽厚、节奏从容偏后。旅居欧洲多年，晚年主演电影《午夜旋律》获奥斯卡提名，成为爵士传奇的银幕化身。"},
  "Stan Getz":{zh:"斯坦·盖茨",born:1927,died:1991,country:"美国",role:"次中音萨克斯",bio:"以‘如丝般’的甜美音色闻名，人称‘The Sound’。1960 年代他把巴西波萨诺瓦带入北美，《Getz/Gilberto》中的《伊帕内玛的女孩》风靡全球。"},
  "Wayne Shorter":{zh:"韦恩·肖特",born:1933,died:2023,country:"美国",role:"萨克斯 · 作曲",bio:"爵士史上最深邃的作曲家之一，先后效力爵士信使、迈尔斯五重奏，又共同创立气象报告。《Speak No Evil》中的乐曲如谜语般含蓄而开阔，影响了几代作曲者。"},
  "Cecil Taylor":{zh:"塞西尔·泰勒",born:1929,died:2018,country:"美国",role:"钢琴 · 作曲",bio:"自由爵士钢琴的极端先锋，把钢琴当作‘八十八面定音鼓’来敲击。他的音乐密度惊人、能量爆裂，融合古典前卫与非洲节奏，是即兴音乐里最难也最纯粹的存在。"},
  "Charles Mingus":{zh:"查尔斯·明格斯",born:1922,died:1979,country:"美国",role:"贝斯 · 作曲 · 乐队领袖",bio:"暴烈而深情的天才，把布鲁斯、福音、艾灵顿与集体即兴熔于一炉。《Mingus Ah Um》《The Black Saint and the Sinner Lady》既是音乐，也是对种族不公的呐喊。"},
  "Grant Green":{zh:"格兰特·格林",born:1935,died:1979,country:"美国",role:"吉他",bio:"Blue Note 的招牌吉他手，以单音线条的清晰与布鲁斯味十足的律动著称，从不滥用和弦。他横跨硬波普、灵魂爵士与放克，是后世爵士吉他与采样文化的常青源头。"},
  "Horace Silver":{zh:"霍勒斯·西尔弗",born:1928,died:2014,country:"美国",role:"钢琴 · 作曲",bio:"硬波普与‘灵魂爵士’（soul jazz）的奠基人，把福音和布鲁斯的烟火气注入比波普。《Song for My Father》的拉丁律动是一代人的爵士入门。"},
  "Joe Henderson":{zh:"乔·亨德森",born:1937,died:2001,country:"美国",role:"次中音萨克斯 · 作曲",bio:"音色辛辣、构思缜密的次中音大师，游走于硬波普与前卫之间。《Page One》《Inner Urge》尽显其作曲功力；1990 年代凭致敬专辑重获大众瞩目。"},
  "Scott Joplin":{zh:"斯科特·乔普林",born:1868,died:1917,country:"美国",role:"钢琴 · 作曲",bio:"‘拉格泰姆之王’，把这种切分钢琴音乐写成可登大雅之堂的作品。《枫叶拉格》传遍全美，他甚至写了拉格泰姆歌剧。其音乐是爵士节奏的直接前身。"},
  "Art Blakey & the Jazz Messengers":{zh:"阿特·布雷基与爵士信使",life:"活跃 1954–1990",country:"美国",role:"硬波普乐队",bio:"鼓手阿特·布雷基领衔的硬波普‘黄埔军校’，三十余年里源源不断地培养出莫布利、摩根、肖特、马萨利斯等大批新星。《Moanin'》是硬波普的标准范本。"},
  "Bill Evans":{zh:"比尔·埃文斯",born:1929,died:1980,country:"美国",role:"钢琴 · 作曲",bio:"现代爵士钢琴最具诗意的声音，以印象派和声、内省触键和三重奏的对话式互动重塑了钢琴三重奏。《Sunday at the Village Vanguard》是即兴室内乐的典范。"},
  "Cannonball Adderley":{zh:"加农炮·阿德利",born:1928,died:1975,country:"美国",role:"中音萨克斯 · 乐队领袖",bio:"音色明亮、洋溢喜悦的中音萨克斯手，曾参与《Kind of Blue》。他领衔的乐队把灵魂爵士推向流行榜，《Mercy, Mercy, Mercy》成为跨界金曲。"},
  "Dizzy Gillespie":{zh:"迪兹·吉莱斯皮",born:1917,died:1993,country:"美国",role:"小号 · 作曲 · 乐队领袖",bio:"与帕克并肩缔造比波普的小号巨人，标志是鼓起的双腮和向上弯折的喇叭口。他还把古巴节奏引入爵士，开创了‘拉丁爵士’（Afro-Cuban jazz）。"},
  "Donald Byrd":{zh:"唐纳德·伯德",born:1932,died:2013,country:"美国",role:"小号 · 作曲",bio:"学院派出身的硬波普小号手，后大胆拥抱放克与节奏布鲁斯。《Black Byrd》成为 Blue Note 史上最畅销专辑之一，也成为日后嘻哈采样的富矿。"},
  "Freddie Hubbard":{zh:"弗雷迪·哈伯德",born:1938,died:2008,country:"美国",role:"小号 · 作曲",bio:"技术华丽、音色灿烂的小号巨匠，硬波普与前卫的双栖好手，参与了《Free Jazz》《Maiden Voyage》等众多里程碑。《Red Clay》是其融合时期的代表作。"},
  "Jackie McLean":{zh:"杰基·麦克莱恩",born:1931,died:2006,country:"美国",role:"中音萨克斯 · 作曲",bio:"音色尖锐、略带‘走音’张力的中音萨克斯手，从硬波普一路探入前卫领域。《Let Freedom Ring》标志着他向自由爵士的勇敢跨越，晚年更是杰出的爵士教育家。"},
  "McCoy Tyner":{zh:"麦考伊·泰纳",born:1938,died:2020,country:"美国",role:"钢琴 · 作曲",bio:"柯川经典四重奏的钢琴基石，以雷霆般的左手五度和弦与汹涌的调式音阶定义了一种全新的钢琴语汇。单飞后《The Real McCoy》延续了这股磅礴气势。"},
  "Return to Forever":{zh:"重返永恒（乐队）",life:"活跃 1971–1977",country:"美国",role:"融合爵士乐队",bio:"奇克·科里亚创立的融合名团，早期带巴西色彩，后转向高能电气化。与气象报告、大慈悲管弦乐团并称 1970 年代融合爵士三巨头。"},
  "Sun Ra":{zh:"太阳·拉",born:1914,died:1993,country:"美国",role:"钢琴 · 键盘 · 大乐队领袖",bio:"自称来自土星的宇宙哲人，率领‘阿凯斯特拉’大乐队跨越摇摆、自由爵士与早期电子音乐。华丽的太空戏服与超前的合成器实验，使他成为非洲未来主义的鼻祖。"},
  "Albert Ayler":{zh:"阿尔伯特·艾勒",born:1936,died:1970,country:"美国",role:"次中音萨克斯 · 作曲",bio:"自由爵士最炽烈的呐喊者，用进行曲、灵歌与民谣式旋律包裹尖啸的多重泛音。《Spiritual Unity》如灵魂出窍般狂喜。三十四岁离奇溺亡于东河。"},
  "Antonio Carlos Jobim":{zh:"安东尼奥·卡洛斯·裘宾",born:1927,died:1994,country:"巴西",role:"作曲 · 钢琴 · 吉他",bio:"波萨诺瓦之父，巴西最伟大的作曲家。《伊帕内玛的女孩》《Desafinado》等作品把里约的慵懒阳光写成全世界的旋律，深刻影响了爵士标准曲库。"},
  "Bobby Hutcherson":{zh:"鲍比·哈奇森",born:1941,died:2016,country:"美国",role:"颤音琴 · 马林巴",bio:"把颤音琴从摇摆时代带入现代爵士的革新者，音色晶莹、和声前卫。他参与了多张 Blue Note 前卫经典，《Components》《Dialogue》尽显其作曲胸襟。"},
  "Charlie Haden":{zh:"查理·海登",born:1937,died:2014,country:"美国",role:"贝斯 · 作曲",bio:"奥奈特·科尔曼革命乐队的贝斯基石，把民谣的质朴与政治关怀注入自由爵士。他创立的‘解放音乐管弦乐团’把抗议歌曲谱成宏大编制，深沉而温暖。"},
  "Count Basie":{zh:"康特·贝西",born:1904,died:1984,country:"美国",role:"钢琴 · 大乐队领袖",bio:"摇摆大乐队的两大支柱之一，以堪萨斯城式的强劲律动、精简到极致的钢琴‘点彩’和无与伦比的节奏组著称。他证明：摇摆的秘诀是‘少即是多’。"},
  "Eric Dolphy":{zh:"埃里克·多尔菲",born:1928,died:1964,country:"美国",role:"中音萨克斯 · 低音单簧管 · 长笛",bio:"多管奇才，把跳跃的大音程和近乎说话的‘人声化’语汇带入即兴，是连接硬波普与自由爵士的桥梁。《Out to Lunch!》是前卫爵士的孤峰。三十六岁因误诊糖尿病猝逝。"},
  "Jimmy Smith":{zh:"吉米·史密斯",born:1925,died:2005,country:"美国",role:"哈蒙德风琴",bio:"把哈蒙德 B-3 风琴变成爵士主角的第一人，用脚踏贝斯、滚烫的布鲁斯乐句定义了‘灵魂爵士’的声音，掀起此后席卷酒吧的风琴热潮。"},
  "Stanley Turrentine":{zh:"斯坦利·特伦廷",born:1934,died:2000,country:"美国",role:"次中音萨克斯",bio:"音色温暖、布鲁斯味浓郁的次中音萨克斯手，绰号‘Mr. T’。他与风琴手希尔弗·斯科特等合作的灵魂爵士，是慵懒夜晚的最佳配乐。"},
  "Keith Jarrett":{zh:"基思·贾勒特",born:1945,country:"美国",role:"钢琴 · 作曲",bio:"当代最伟大的即兴钢琴家之一，能把整场独奏会从虚空中即兴成形。《The Köln Concert》是史上最畅销的钢琴独奏专辑；他的‘标准曲三重奏’亦是教科书。2018 年中风后几近无法演奏，留下无尽惋惜。"},
  "Andrew Hill":{zh:"安德鲁·希尔",born:1931,died:2007,country:"美国",role:"钢琴 · 作曲",bio:"Blue Note 阵中最具个性的作曲家之一，音乐结构暧昧、和声游移，介于调性与自由之间。《Point of Departure》是 1960 年代前卫爵士被低估的杰作。"},
  "Cal Tjader":{zh:"卡尔·杰德",born:1925,died:1982,country:"美国",role:"颤音琴 · 拉丁爵士领袖",bio:"非拉美裔却最成功的拉丁爵士领袖之一，以颤音琴的轻盈音色融合曼波、波萨诺瓦与硬波普。《Soul Sauce》让拉丁爵士登上流行榜。"},
  "Chet Baker":{zh:"切特·贝克",born:1929,died:1988,country:"美国",role:"小号 · 演唱",bio:"西海岸冷爵士的忧郁偶像，小号与歌声同样轻柔脆弱、楚楚动人。俊美的外表与毒瘾交织成一段悲剧传奇，最终在阿姆斯特丹坠楼离世。"},
  "Chick Corea":{zh:"奇克·科里亚",born:1941,died:2021,country:"美国",role:"钢琴 · 键盘 · 作曲",bio:"风格百变的钢琴巨匠，从迈尔斯电气乐队到融合名团‘重返永恒’，再到西班牙色彩的原声作品。《Now He Sings, Now He Sobs》《Return to Forever》皆为经典，一生横扫格莱美。"},
  "Coleman Hawkins":{zh:"科尔曼·霍金斯",born:1904,died:1969,country:"美国",role:"次中音萨克斯",bio:"次中音萨克斯的奠基之父，把这件原本不起眼的乐器立为爵士主角。1939 年的《Body and Soul》以大胆的和声即兴预告了比波普的到来。"},
  "Dave Brubeck":{zh:"戴夫·布鲁贝克",born:1920,died:2012,country:"美国",role:"钢琴 · 作曲",bio:"以不规则拍子实验闻名的冷爵士钢琴家。《Time Out》中 5/4 拍的《Take Five》成为史上最畅销的爵士单曲之一，把复杂节拍带进了千家万户。"},
  "Django Reinhardt":{zh:"让戈·莱因哈特",born:1910,died:1953,country:"法国",role:"吉他",bio:"吉普赛爵士的开山祖师，欧洲第一位真正意义上的爵士巨星。一场大火烧伤左手，他却以两根手指创造出令人眩目的吉他技艺，与小提琴手共创‘热力俱乐部五重奏’。"},
  "George Benson":{zh:"乔治·本森",born:1943,country:"美国",role:"吉他 · 演唱",bio:"师承韦斯·蒙哥马利的吉他名家，技艺精湛又极具流行亲和力。1976 年《Breezin'》大获成功，他以吉他与人声同步的‘scat’唱法跨入主流，成为爵士与节奏布鲁斯的桥梁。"},
  "Gerry Mulligan":{zh:"格里·马利根",born:1927,died:1996,country:"美国",role:"上低音萨克斯 · 作曲 · 编曲",bio:"把笨重的上低音萨克斯吹得轻盈如歌的西海岸代表人物。他参与了迈尔斯《Birth of the Cool》的编曲，又以‘无钢琴’的四重奏开创冷爵士的清透织体。"},
  "Kenny Dorham":{zh:"肯尼·多勒姆",born:1924,died:1972,country:"美国",role:"小号 · 作曲",bio:"被严重低估的硬波普小号诗人，音色含蓄抒情。他写下的《Blue Bossa》成为最常被演奏的爵士标准曲之一，作曲才华远胜其生前的名气。"},
  "Lou Donaldson":{zh:"卢·唐纳森",born:1926,died:2024,country:"美国",role:"中音萨克斯",bio:"帕克门徒里布鲁斯味最足的一位，后转向灵魂爵士与放克。《Alligator Boogaloo》律动十足，成为嘻哈采样的常客；他活到九十八岁高龄。"},
  "Louis Armstrong":{zh:"路易斯·阿姆斯特朗",born:1901,died:1971,country:"美国",role:"小号 · 演唱 · 乐队领袖",bio:"爵士史上第一位伟大的独奏家，亲手把这门音乐从集体即兴推向个人表达。沙哑温暖的歌声和‘Hot Five/Seven’的录音奠定了爵士的语言，影响无远弗届。"},
  "Mahavishnu Orchestra":{zh:"大慈悲管弦乐团（Mahavishnu）",life:"活跃 1971–1976",country:"美国",role:"融合爵士乐队",bio:"英国吉他手约翰·麦克劳克林领衔的高能融合名团，把摇滚的音量、印度音乐的灵性与超复杂节拍熔于一炉。《The Inner Mounting Flame》是融合摇滚的炸裂宣言。"},
  "Modern Jazz Quartet":{zh:"现代爵士四重奏",life:"活跃 1952–1974",country:"美国",role:"室内爵士四重奏",bio:"以颤音琴、钢琴、贝斯、鼓的精致编制著称，把巴洛克对位与赋格引入爵士，举止优雅如穿燕尾服演奏。‘第三流派’（Third Stream）的代表，证明了爵士的室内乐潜质。"},
  "Mongo Santamaria":{zh:"蒙戈·圣塔玛利亚",born:1917,died:2003,country:"古巴",role:"康加鼓 · 拉丁爵士领袖",bio:"古巴打击乐大师，把非洲–古巴节奏带入美国爵士主流。他翻奏汉考克的《Watermelon Man》大获成功，让拉丁爵士的律动渗入流行乐。"},
  "Pharoah Sanders":{zh:"法老·桑德斯",born:1940,died:2022,country:"美国",role:"次中音萨克斯",bio:"柯川晚期乐队的灵性搭档，以撕裂般的多重泛音和超验的能量著称。晚年风格转向宁静空灵，2021 年与电子音乐人合作的《Promises》成为绝唱级杰作。"},
  "Sonny Clark":{zh:"桑尼·克拉克",born:1931,died:1963,country:"美国",role:"钢琴 · 作曲",bio:"音色干净、律动摇摆的硬波普钢琴家，深受日本爵士迷崇拜。《Cool Struttin'》是 Blue Note 最受欢迎的专辑之一。三十一岁因毒瘾英年早逝。"},
  "Thelonious Monk":{zh:"塞隆尼斯·蒙克",born:1917,died:1982,country:"美国",role:"钢琴 · 作曲",bio:"爵士史上最独特的作曲家与钢琴家，以不协和音、错落的休止与古怪的触键自成一派。《'Round Midnight》《Straight, No Chaser》是被演奏最多的爵士原创曲，生前被误解，身后封神。"},
  "Wes Montgomery":{zh:"韦斯·蒙哥马利",born:1923,died:1968,country:"美国",role:"吉他",bio:"用大拇指拨弦、以平行八度奏旋律的吉他天才，温暖圆润的音色无人能仿。从硬波普到大获成功的流行跨界，他重新定义了爵士吉他的可能。"},
  "Wynton Marsalis":{zh:"温顿·马萨利斯",born:1961,country:"美国",role:"小号 · 作曲 · 乐队领袖",bio:"古典与爵士双修的小号名家，1980 年代‘新古典主义’（neo-bop）的旗手。作为林肯中心爵士乐团的掌舵人和教育者，他既被尊为传统守护者，也引发不少争议。"},
  "Anthony Braxton":{zh:"安东尼·布拉克斯顿",born:1945,country:"美国",role:"萨克斯 · 作曲 · 理论家",bio:"芝加哥 AACM 出身的前卫巨匠与作曲理论家，以图形化标题和庞杂的体系著称。《For Alto》是史上首张无伴奏中音萨克斯独奏专辑，把即兴推向作曲与哲学的交界。"},
  "Archie Shepp":{zh:"阿奇·谢普",born:1937,country:"美国",role:"次中音萨克斯 · 作曲",bio:"自由爵士的政治良心，把黑人民权抗争、诗歌与布鲁斯的根脉熔铸成炽热的呐喊。《Fire Music》《Attica Blues》既是音乐，也是时代的檄文。"},
  "Art Blakey":{zh:"阿特·布雷基",born:1919,died:1990,country:"美国",role:"鼓 · 乐队领袖",bio:"硬波普的‘发动机’，以雷鸣般的滚奏和标志性的‘press roll’驱动乐队。作为爵士信使的领袖，他三十余年如一日发掘年轻才俊，是爵士史上最伟大的伯乐。"},
  "Art Ensemble of Chicago":{zh:"芝加哥艺术合奏团",life:"活跃 1969 起",country:"美国",role:"前卫爵士乐队",bio:"AACM 旗下最著名的集体，口号是‘从古至今的伟大黑人音乐’。他们涂面彩、用上百件乐器，把自由即兴、戏剧表演与非洲根源融为一场仪式。"},
  "Art Pepper":{zh:"阿特·佩珀",born:1925,died:1982,country:"美国",role:"中音萨克斯",bio:"西海岸冷爵士最动人的中音萨克斯手，抒情中藏着撕裂的痛感。一生与毒瘾、牢狱缠斗，晚年复出愈发炽烈，自传《Straight Life》坦诚得令人心碎。"},
  "Benny Goodman":{zh:"本尼·古德曼",born:1909,died:1986,country:"美国",role:"单簧管 · 大乐队领袖",bio:"‘摇摆之王’，把爵士送上主流舞台的关键人物。1938 年卡内基音乐厅的传奇演出让爵士登堂入室，他也是最早公开起用黑人乐手的白人领班之一。"},
  "Brad Mehldau":{zh:"布拉德·梅尔道",born:1970,country:"美国",role:"钢琴 · 作曲",bio:"当代爵士钢琴的领军人物，以严密的对位、左右手独立的复调思维和对流行歌曲的深度改编著称。他翻奏电台司令与披头士，把爵士三重奏带向新的内省深度。"},
  "Branford Marsalis":{zh:"布兰福德·马萨利斯",born:1960,country:"美国",role:"萨克斯 · 乐队领袖",bio:"马萨利斯家族长子，技艺全面的萨克斯手，游走于硬波普传统与流行跨界之间。他曾任斯汀乐队与电视深夜秀乐队成员，把爵士带给更广的听众。"},
  "Clifford Brown":{zh:"克利福德·布朗",born:1930,died:1956,country:"美国",role:"小号 · 作曲",bio:"硬波普最纯净灿烂的小号声音，技术与抒情兼备，且洁身自好、远离毒品。与鼓手罗奇的五重奏正值巅峰时，他在二十五岁因车祸骤逝，成为爵士史最痛的‘如果’。"},
  "Don Cherry":{zh:"唐·切利",born:1936,died:1995,country:"美国",role:"袖珍小号 · 作曲",bio:"奥奈特·科尔曼革命乐队的小号搭档，自由爵士的核心人物。他更是‘世界音乐’的先驱，融入印度、非洲与中东元素，背着袖珍小号浪迹全球。"},
  "Ella Fitzgerald":{zh:"埃拉·菲茨杰拉德",born:1917,died:1996,country:"美国",role:"演唱",bio:"‘歌曲第一夫人’，音准完美、音色清澈，拟声唱法（scat）无人能及。她录制的《Songbook》系列系统梳理了美国流行歌曲宝库，是爵士演唱的最高标准之一。"},
  "James Scott":{zh:"詹姆斯·斯科特",born:1885,died:1938,country:"美国",role:"钢琴 · 作曲",bio:"与乔普林、约瑟夫·兰姆并称‘古典拉格泰姆三巨头’。他的拉格泰姆技巧繁难、织体华丽，《Grace and Beauty》展现了这门音乐在结构上的精致巅峰。"},
  "Jelly Roll Morton":{zh:"杰利·罗尔·莫顿",born:1890,died:1941,country:"美国",role:"钢琴 · 作曲 · 乐队领袖",bio:"自称‘爵士发明者’的新奥尔良钢琴家，虽夸大其词，却确是第一位伟大的爵士作曲与编曲家。他的‘红辣椒’乐队录音把集体即兴写成了精密的乐章。"},
  "Jimmy Giuffre":{zh:"吉米·朱弗里",born:1921,died:2008,country:"美国",role:"单簧管 · 萨克斯 · 作曲",bio:"安静的革新者，从西海岸冷爵士的室内乐写作，一路走到 1960 年代无鼓、近乎室内乐的自由即兴三重奏。《Free Fall》在当时无人问津，如今被奉为先知之作。"},
  "Joe Lovano":{zh:"乔·洛瓦诺",born:1952,country:"美国",role:"次中音萨克斯 · 作曲",bio:"当代次中音萨克斯的多面手，音色厚重、根基扎实又乐于实验。他扎根传统却不断与前卫对话，是 1990 年代以来 Blue Note 的中流砥柱。"},
  "Joshua Redman":{zh:"约书亚·雷德曼",born:1969,country:"美国",role:"次中音萨克斯 · 作曲",bio:"哈佛毕业却选择音乐的当代萨克斯明星，音色圆熟、旋律感极强。作为萨克斯名宿杜威·雷德曼之子，他成为 1990 年代爵士复兴的青年门面。"},
  "Lester Young":{zh:"莱斯特·扬",born:1909,died:1959,country:"美国",role:"次中音萨克斯",bio:"绰号‘Prez’（总统），以轻盈飘逸、旋律优先的乐句颠覆了霍金斯式的厚重传统，直接启发了冷爵士与比波普。他与歌手比莉·哈乐黛的合作堪称天作之合。"},
  "Lionel Hampton":{zh:"莱昂内尔·汉普顿",born:1908,died:2002,country:"美国",role:"颤音琴 · 大乐队领袖",bio:"把颤音琴确立为爵士独奏乐器的第一人，也是古德曼乐队打破种族界限的成员。他领衔的大乐队活力四射，舞台魅力延续了半个多世纪。"},
  "Pat Metheny":{zh:"帕特·麦席尼",born:1954,country:"美国",role:"吉他 · 作曲",bio:"当代最受欢迎的爵士吉他家，音色温暖辽阔，融合美国乡村的开阔感与巴西节奏。从前卫即兴到电影配乐式的大编制，他几乎拿遍了爵士格莱美。"},
  "Pat Metheny Group":{zh:"帕特·麦席尼乐队",life:"活跃 1977–2010s",country:"美国",role:"现代爵士乐队",bio:"麦席尼与键盘手莱尔·梅斯共同主导的招牌乐队，以辽阔的音景、合成吉他与世界音乐织体著称。《Still Life (Talking)》《Letter from Home》定义了一种‘电影感’的当代爵士。"},
  "Roy Hargrove":{zh:"罗伊·哈格罗夫",born:1969,died:2018,country:"美国",role:"小号 · 作曲",bio:"新生代硬波普的杰出代表，音色甜美、根基深厚，又积极拥抱嘻哈与新灵魂乐。他的 RH Factor 项目连接了爵士与当代黑人流行乐，四十九岁因肾病早逝令人扼腕。"},
  "Sergio Mendes":{zh:"塞尔吉奥·门德斯",born:1941,died:2024,country:"巴西",role:"钢琴 · 乐队领袖",bio:"把巴西波萨诺瓦与桑巴包装成全球流行的关键推手。其‘Brasil '66’乐队翻唱的《Mas Que Nada》风靡世界，让巴西节奏成为几代人的夏日记忆。"},
  "Sidney Bechet":{zh:"西德尼·贝谢",born:1897,died:1959,country:"美国",role:"高音萨克斯 · 单簧管",bio:"新奥尔良早期的传奇，把高音萨克斯立为独奏乐器的先驱，颤音宽阔而炽烈。他与阿姆斯特朗同为最早的伟大独奏家，晚年在法国被奉为国宝级人物。"},
  "Sonny Stitt":{zh:"桑尼·斯蒂特",born:1924,died:1982,country:"美国",role:"中音/次中音萨克斯",bio:"比波普语汇最流利的传人之一，一生背负‘帕克模仿者’的标签，遂转攻次中音以自立门户。无论何时何地都能即兴如流，是巡演舞台上的常胜将军。"},
  "Stanley Clarke":{zh:"斯坦利·克拉克",born:1951,country:"美国",role:"电贝斯 · 原声贝斯 · 作曲",bio:"融合爵士时代把贝斯推上独奏前台的先锋，‘重返永恒’的核心成员。他炫目的电贝斯技巧重新定义了这件乐器的角色，《School Days》成为贝斯手的必修课。"},
  "Wardell Gray":{zh:"沃德尔·格雷",born:1921,died:1955,country:"美国",role:"次中音萨克斯",bio:"连接摇摆与比波普的次中音好手，乐句流畅、布鲁斯味浓，与德克斯特·戈登的‘萨克斯对决’录音风靡一时。三十四岁离奇横死于沙漠，至今成谜。"},

  "Art Tatum":{zh:"阿特·塔图姆",born:1909,died:1956,country:"美国",role:"钢琴",bio:"公认技术最华丽的爵士钢琴家，几近全盲却以惊人的速度、繁复的和声重新装点旋律，连古典大师都为之叹服。"},
  "Earl Hines":{zh:"厄尔·海因斯",born:1903,died:1983,country:"美国",role:"钢琴",bio:"现代爵士钢琴的奠基者之一，以‘小号式’右手单音线条突破早期的节奏型弹法，与阿姆斯特朗的合作堪称经典。"},
  "Fats Waller":{zh:"法茨·沃勒",born:1904,died:1943,country:"美国",role:"钢琴 · 演唱 · 作曲",bio:"‘跨步钢琴’（stride）大师与天才词曲作者，以诙谐演唱与华丽左手风靡一时，《Ain't Misbehavin'》传唱至今。"},
  "Teddy Wilson":{zh:"泰迪·威尔逊",born:1912,died:1986,country:"美国",role:"钢琴",bio:"摇摆时代最优雅的钢琴家，古德曼三重奏成员（最早打破种族界限的组合之一），是哈乐黛经典录音的灵魂搭档。"},
  "Fletcher Henderson":{zh:"弗莱彻·亨德森",born:1897,died:1952,country:"美国",role:"编曲 · 大乐队领袖",bio:"大乐队编曲的奠基者，把铜管与簧管分声部对答的写法立为摇摆范式，他为古德曼所写的编曲点燃了整个摇摆时代。"},
  "Eddie Condon":{zh:"埃迪·康登",born:1905,died:1973,country:"美国",role:"班卓琴 · 吉他 · 乐队领袖",bio:"芝加哥风格迪克西兰的核心组织者，以连珠炮般的现场与热爵士聚会闻名，是传统爵士的旗手。"},
  "Red Norvo":{zh:"瑞德·诺沃",born:1908,died:1999,country:"美国",role:"颤音琴 · 木琴",bio:"最早把木琴／颤音琴立为爵士独奏乐器的先驱，其无鼓三重奏轻盈精巧，是冷爵士室内乐的早期雏形。"},
  "Bessie Smith":{zh:"贝西·史密斯",born:1894,died:1937,country:"美国",role:"演唱",bio:"‘布鲁斯皇后’，1920 年代最伟大的女歌手，嗓音雄浑深情，把古典布鲁斯唱进了爵士的血脉。"},
  "Billie Holiday":{zh:"比莉·哈乐黛",born:1915,died:1959,country:"美国",role:"演唱",bio:"‘Lady Day’，爵士演唱史上最具感染力的声音，以独特的节奏处理把歌词唱成自传；《Strange Fruit》是控诉私刑的不朽之作。"},

  "Fats Navarro":{zh:"法茨·纳瓦罗",born:1923,died:1950,country:"美国",role:"小号",bio:"比波普小号的关键人物，音色饱满圆润、乐句典雅，是克利福德·布朗等后辈的直接楷模，二十六岁因肺结核与毒瘾早逝。"},
  "Max Roach":{zh:"马克斯·罗奇",born:1924,died:2007,country:"美国",role:"鼓 · 作曲",bio:"比波普鼓的奠基人，把鼓从单纯节拍提升为旋律性的对话。政治意识强烈，《We Insist!》是民权运动的鼓上宣言。"},
  "Clifford Brown & Max Roach":{zh:"克利福德·布朗与马克斯·罗奇",life:"活跃 1954–1956",country:"美国",role:"硬波普五重奏",bio:"小号手布朗与鼓手罗奇共同领衔的传奇五重奏，是硬波普的完美范本，因布朗 1956 年车祸骤逝而戛然而止。"},
  "Hampton Hawes":{zh:"汉普顿·霍斯",born:1928,died:1977,country:"美国",role:"钢琴",bio:"西海岸比波普钢琴的代表，乐句明快、布鲁斯感强烈，是帕克体系在钢琴上最自然的延伸之一。"},
  "Shorty Rogers":{zh:"肖蒂·罗杰斯",born:1924,died:1994,country:"美国",role:"小号 · 编曲",bio:"西海岸冷爵士的核心组织者与编曲家，把比波普语汇编织成清爽明亮的加州声音。"},
  "Charlie Byrd":{zh:"查理·伯德",born:1925,died:1999,country:"美国",role:"吉他",bio:"指弹古典吉他出身的爵士吉他手，与斯坦·盖茨合作的《Jazz Samba》把巴西波萨诺瓦引入美国，掀起热潮。"},
  "Curtis Counce":{zh:"柯蒂斯·康斯",born:1926,died:1963,country:"美国",role:"贝斯 · 乐队领袖",bio:"西海岸硬波普的贝斯手与领袖，其五重奏录音强劲而被低估，是 1950 年代洛杉矶爵士硬朗的一面。"},
  "Gene Ammons":{zh:"吉恩·阿蒙斯",born:1925,died:1974,country:"美国",role:"次中音萨克斯",bio:"绰号‘Jug’，音色宽厚多情的次中音大师，是灵魂爵士与‘对吹’（tenor battle）传统的代表，布鲁斯味十足。"},
  "Johnny Griffin":{zh:"约翰尼·格里芬",born:1928,died:2008,country:"美国",role:"次中音萨克斯",bio:"绰号‘小巨人’，以惊人速度著称的硬波普萨克斯手，与蒙克合作的现场录音淋漓尽致，后旅居欧洲。"},
  "Blue Mitchell":{zh:"布鲁·米切尔",born:1930,died:1979,country:"美国",role:"小号",bio:"音色温暖明亮的硬波普小号手，长期搭档霍勒斯·西尔弗，独奏作品布鲁斯味十足、亲切耐听。"},
  "Ike Quebec":{zh:"艾克·魁北克",born:1918,died:1963,country:"美国",role:"次中音萨克斯",bio:"音色温暖醇厚的次中音萨克斯手，也是 Blue Note 的星探，晚期《Blue and Sentimental》尽显其抒情之美。"},
  "Tina Brooks":{zh:"蒂娜·布鲁克斯",born:1932,died:1974,country:"美国",role:"次中音萨克斯 · 作曲",bio:"被严重低估的硬波普作曲家与萨克斯手（本名 Harold，‘Tina’为绰号），《True Blue》是 Blue Note 的隐藏珍宝，生前大量录音未能发行。"},
  "Horace Parlan":{zh:"霍勒斯·帕兰",born:1931,died:2017,country:"美国",role:"钢琴",bio:"幼年小儿麻痹使右手受限，他却发展出独特的左手主导、布鲁斯味浓郁的钢琴风格，是明格斯乐队与 Blue Note 的可靠基石。"},
  "Red Garland":{zh:"瑞德·加兰",born:1923,died:1984,country:"美国",role:"钢琴",bio:"迈尔斯第一伟大五重奏的钢琴手，以晶莹的‘块状和弦’与优雅律动著称，是 1950 年代硬波普钢琴的标志音色。"},
  "Paul Chambers":{zh:"保罗·钱伯斯",born:1935,died:1969,country:"美国",role:"贝斯",bio:"迈尔斯第一伟大五重奏的贝斯基石，以稳健的行走低音和开创性的拉弓独奏著称，《Kind of Blue》等无数经典皆有他坐镇。"},
  "Philly Joe Jones":{zh:"费城乔·琼斯",born:1923,died:1985,country:"美国",role:"鼓",bio:"迈尔斯第一伟大五重奏的鼓手，以标志性的‘鼓边敲击’和强劲律动推动乐队，是硬波普鼓的典范。"},
  "The Three Sounds":{zh:"三重音（乐队）",life:"活跃 1956–1970s",country:"美国",role:"灵魂爵士三重奏",bio:"以钢琴手吉恩·哈里斯为核心的三重奏，亲切讨喜的布鲁斯律动，是 Blue Note 灵魂爵士最受欢迎的声音之一。"},

  "Lee Konitz":{zh:"李·科尼茨",born:1927,died:2020,country:"美国",role:"中音萨克斯",bio:"冷爵士的独立声音，师从特里斯塔诺，以清冷干燥的音色和不断重塑旋律的态度自成一格，七十年如一日地探索。"},
  "Phil Woods":{zh:"菲尔·伍兹",born:1931,died:2015,country:"美国",role:"中音萨克斯",bio:"帕克衣钵最杰出的传人之一，炽热流畅、根基扎实，也以比利·乔尔《Just the Way You Are》的萨克斯独奏为大众所知。"},
  "Rahsaan Roland Kirk":{zh:"拉桑·罗兰·柯克",born:1935,died:1977,country:"美国",role:"萨克斯 · 多管齐奏",bio:"失明的奇才，能同时吹奏三支管乐器，并以循环呼吸不间断演奏，把马戏般的技艺与深厚的爵士传统熔于一炉。"},
  "Grachan Moncur III":{zh:"格拉昌·蒙库尔三世",born:1937,died:2022,country:"美国",role:"长号 · 作曲",bio:"前卫长号手与作曲家，游走于硬波普与自由爵士之间，《Evolution》是 1960 年代 Blue Note 前卫浪潮中被低估的杰作。"},
  "Marion Brown":{zh:"马里恩·布朗",born:1931,died:2010,country:"美国",role:"中音萨克斯",bio:"自由爵士的抒情声音，参与了柯川的《Ascension》，其作品却更偏向温柔的田园冥想，《Afternoon of a Georgia Faun》别具一格。"},
  "Sam Rivers":{zh:"萨姆·里弗斯",born:1923,died:2011,country:"美国",role:"萨克斯 · 长笛 · 作曲",bio:"前卫多管乐手与作曲家，1970 年代纽约‘阁楼爵士’运动的核心，作品兼具自由的能量与缜密的结构。"},
  "Paul Bley":{zh:"保罗·布雷",born:1932,died:2016,country:"加拿大",role:"钢琴",bio:"自由爵士钢琴的先知，最早演绎奥奈特·科尔曼乐曲的人之一，又是最早拥抱合成器的爵士钢琴家，录音满是空间与留白。"},
  "Alice Coltrane":{zh:"爱丽丝·柯川",born:1937,died:2007,country:"美国",role:"钢琴 · 竖琴 · 作曲",bio:"约翰·柯川的遗孀与音乐伙伴，以竖琴与管风琴营造灵性氛围，把印度灵修与自由爵士融为冥想之声，《Journey in Satchidananda》是代表作。"},
  "Air":{zh:"空气（乐队）",life:"活跃 1971–1986",country:"美国",role:"前卫爵士三重奏",bio:"由亨利·思雷吉尔领衔的前卫三重奏，把拉格泰姆、布鲁斯与自由即兴重新拼贴，《Air Lore》以现代手法重读乔普林与莫顿。"},

  "Sarah Vaughan":{zh:"莎拉·沃恩",born:1924,died:1990,country:"美国",role:"演唱",bio:"绰号‘神音’（Sassy），拥有歌剧般音域与器乐化即兴能力的爵士女声，把每首歌都唱成华丽炫技与深情的并存。"},
  "Carmen McRae":{zh:"卡门·麦克雷",born:1920,died:1994,country:"美国",role:"演唱",bio:"以精准咬字、钢琴家般的乐句和略带辛辣的诠释著称的爵士女声，与菲茨杰拉德、沃恩并称同代三大歌后。"},
  "Nat King Cole":{zh:"纳特·金·科尔",born:1919,died:1965,country:"美国",role:"演唱 · 钢琴",bio:"先是顶尖的爵士钢琴三重奏领袖，后以丝绒般的嗓音成为流行巨星，钢琴影响了一代人，歌声则跨越了种族藩篱。"},
  "Frank Sinatra":{zh:"弗兰克·辛纳屈",born:1915,died:1998,country:"美国",role:"演唱",bio:"二十世纪最伟大的流行／爵士男声，以无可挑剔的乐句与叙事感重新定义了‘演唱专辑’，与里德尔合作的作品是美国歌曲的巅峰。"},
  "Mel Tormé":{zh:"梅尔·托梅",born:1925,died:1999,country:"美国",role:"演唱 · 作曲",bio:"绰号‘天鹅绒之雾’，以丝滑音色和高超拟声唱法著称的男声，也是《The Christmas Song》的作者。"},

  "Tony Williams":{zh:"托尼·威廉姆斯",born:1945,died:1997,country:"美国",role:"鼓",bio:"十七岁加入迈尔斯第二伟大五重奏的鼓坛神童，以爆发力与自由的节奏概念革新了爵士鼓，后创立融合名团 Lifetime。"},
  "Jaco Pastorius":{zh:"雅科·帕斯托留斯",born:1951,died:1987,country:"美国",role:"电贝斯",bio:"史上最具革命性的电贝斯手，以无品贝斯的歌唱音色、泛音与和弦彻底改写了这件乐器，气象报告时期达到巅峰，三十五岁悲剧离世。"},
  "Billy Cobham":{zh:"比利·科巴姆",born:1944,country:"美国",role:"鼓",bio:"大慈悲管弦乐团的鼓手，以双底鼓的雷霆技巧与精准的复杂节拍定义了融合爵士的鼓语言，《Spectrum》是鼓手必听。"},
  "John McLaughlin":{zh:"约翰·麦克劳克林",born:1942,country:"英国",role:"吉他",bio:"融合爵士吉他的旗手，参与迈尔斯电气乐队、创立大慈悲管弦乐团，又以原声三重奏 Shakti 融合印度古典，是横跨多种传统的吉他思想家。"},
  "Larry Coryell":{zh:"拉里·科里尔",born:1943,died:2017,country:"美国",role:"吉他",bio:"被誉为‘融合教父’的吉他先驱，最早把摇滚能量与爵士即兴结合，为后来的融合吉他铺平道路。"},
  "Al Di Meola":{zh:"阿尔·迪·梅奥拉",born:1954,country:"美国",role:"吉他",bio:"以惊人速度与拉丁／地中海色彩著称的融合吉他名家，‘重返永恒’成员，与麦克劳克林、德卢西亚的原声吉他三重奏风靡一时。"},
  "Jean-Luc Ponty":{zh:"让-吕克·庞蒂",born:1942,country:"法国",role:"小提琴",bio:"把电小提琴带入融合爵士的先驱，曾效力扎帕与大慈悲管弦乐团，以效果器处理的滑亮音色开拓了弦乐在爵士中的新角色。"},
  "Jeff Beck":{zh:"杰夫·贝克",born:1944,died:2023,country:"英国",role:"吉他",bio:"摇滚吉他巨匠，1970 年代以《Blow by Blow》转向器乐融合，用拨片与摇把唱出人声般的乐句，跨界影响深远。"},
  "Airto":{zh:"艾尔托·莫雷拉",born:1941,country:"巴西",role:"打击乐",bio:"巴西打击乐大师，把繁复的巴西节奏与人声效果带入迈尔斯电气乐队与‘重返永恒’，是融合爵士不可或缺的色彩。"},
  "Grover Washington Jr.":{zh:"格罗弗·华盛顿（小）",born:1943,died:1999,country:"美国",role:"萨克斯",bio:"流畅爵士（smooth jazz）的奠基人之一，《Winelight》中的《Just the Two of Us》成为跨界金曲，把爵士萨克斯带入千家万户。"},

  "João Gilberto":{zh:"若昂·吉尔贝托",born:1931,died:2019,country:"巴西",role:"演唱 · 吉他",bio:"波萨诺瓦之父之一，以近乎耳语的演唱和独创的切分吉他节奏（batida）定义了这种音乐，《Getz/Gilberto》让它风靡全球。"},
  "Stan Getz & João Gilberto":{zh:"斯坦·盖茨与若昂·吉尔贝托",life:"录于 1963",country:"美国／巴西",role:"波萨诺瓦合作",bio:"萨克斯手盖茨与巴西吉他歌手吉尔贝托的历史性合作，《Getz/Gilberto》把波萨诺瓦推向全球，《伊帕内玛的女孩》成为永恒标准曲。"},
  "Milton Nascimento":{zh:"米尔顿·纳西门托",born:1942,country:"巴西",role:"演唱 · 作曲",bio:"巴西音乐的灵魂人物，空灵的假声与米纳斯山区的旋律深深打动了韦恩·肖特等大师，合作专辑《Native Dancer》是跨界经典。"},
  "Gato Barbieri":{zh:"加托·巴比耶里",born:1932,died:2016,country:"阿根廷",role:"次中音萨克斯",bio:"阿根廷萨克斯手，以撕裂炽热的音色把自由爵士与拉美民族色彩结合，电影《巴黎最后的探戈》配乐让他名声大噪。"},
  "Eddie Palmieri":{zh:"埃迪·帕尔米耶里",born:1936,country:"美国",role:"钢琴 · 拉丁爵士领袖",bio:"波多黎各裔的萨尔萨与拉丁爵士巨匠，以激烈的蒙图诺钢琴和先锋编曲把拉丁律动推向新高度，多次问鼎格莱美。"},
  "Tito Puente":{zh:"蒂托·普恩特",born:1923,died:2000,country:"美国",role:"定音鼓 · 拉丁爵士领袖",bio:"‘曼波之王’，波多黎各裔的定音鼓（timbales）大师，把拉丁爵士与曼波推向主流，《Oye Como Va》经桑塔纳翻唱风靡世界。"},
  "Ray Barretto":{zh:"雷·巴雷托",born:1929,died:2007,country:"美国",role:"康加鼓 · 拉丁爵士领袖",bio:"波多黎各裔的康加鼓大师，是无数硬波普名盘的打击乐手，也以萨尔萨与拉丁爵士乐队闻名，《Acid》是拉丁灵魂的经典。"},

  "Vince Guaraldi":{zh:"文斯·瓜拉尔迪",born:1928,died:1976,country:"美国",role:"钢琴 · 作曲",bio:"以《花生漫画》动画配乐家喻户晓的旧金山钢琴家，《Linus and Lucy》旋律深入人心，把爵士钢琴的温情带给了几代人。"},
  "Ramsey Lewis":{zh:"拉姆齐·刘易斯",born:1935,died:2022,country:"美国",role:"钢琴",bio:"把爵士钢琴三重奏带上流行榜的灵魂爵士名家，《The In Crowd》大获成功，亲切的律动让爵士走向更广的听众。"},
  "Kenny Burrell":{zh:"肯尼·布雷尔",born:1931,country:"美国",role:"吉他",bio:"音色温暖、品味无瑕的爵士吉他典范，艾灵顿最爱的吉他手，《Midnight Blue》是布鲁斯味爵士吉他的标杆。"},
  "Kenny Barron":{zh:"肯尼·巴伦",born:1943,country:"美国",role:"钢琴",bio:"当代最受敬重的爵士钢琴大师与教育家，触键优雅、和声丰盈，是无数经典录音的中流砥柱与年轻乐手的导师。"},
  "Roy Haynes":{zh:"罗伊·海恩斯",born:1925,died:2024,country:"美国",role:"鼓",bio:"横跨七十余年的鼓坛常青树，从帕克、蒙克到柯川都有他的鼓声，律动灵动现代，是连接各时代的活历史，享年九十九岁。"},

  "Tom Harrell":{zh:"汤姆·哈雷尔",born:1946,country:"美国",role:"小号 · 短号 · 作曲",bio:"音色温润、抒情深邃的小号大师与作曲家，长年与精神分裂症共处，舞台下静默、举号即化为最动人的乐句。"},
  "Marcus Roberts":{zh:"马库斯·罗伯茨",born:1963,country:"美国",role:"钢琴",bio:"失明的钢琴家，温顿·马萨利斯乐队的早期成员，深耕拉格泰姆、跨步与早期爵士传统，并以全新方式重构三重奏的角色。"},
  "Terence Blanchard":{zh:"特伦斯·布兰查德",born:1962,country:"美国",role:"小号 · 作曲",bio:"新奥尔良的小号手与电影配乐大师，长期为斯派克·李配乐，又是首位作品登上大都会歌剧院的非裔作曲家。"},
  "Nicholas Payton":{zh:"尼古拉斯·佩顿",born:1973,country:"美国",role:"小号",bio:"新奥尔良出身的小号多面手，技艺精湛又勇于争论，提出以‘BAM（黑人美国音乐）’重新命名爵士，是当代最具思辨性的乐手之一。"},
  "Christian McBride":{zh:"克里斯蒂安·麦克布莱德",born:1972,country:"美国",role:"贝斯 · 乐队领袖",bio:"当代最炙手可热的贝斯手与乐队领袖，技艺全面、律动扎实，横跨原声爵士、放克与跨界合作，多次斩获格莱美。"},
  "Diana Krall":{zh:"戴安娜·克瑞儿",born:1964,country:"加拿大",role:"演唱 · 钢琴",bio:"当代最畅销的爵士女声之一，慵懒低回的嗓音与扎实的钢琴功底相得益彰，把标准曲唱得既经典又亲密。"},
  "Cassandra Wilson":{zh:"卡桑德拉·威尔逊",born:1955,country:"美国",role:"演唱",bio:"低沉烟嗓的当代爵士女声，把布鲁斯、民谣与流行重新编织成幽暗性感的声景，《Blue Light 'Til Dawn》开创了一种新的演唱美学。"},
  "Kenny G":{zh:"肯尼·基",born:1956,country:"美国",role:"高音萨克斯",bio:"史上最畅销的器乐演奏家，流畅爵士的标志人物。尽管在爵士圈饱受争议，他甜美悠长的高音萨克斯却是无数人的入门旋律。"},
  "Spyro Gyra":{zh:"Spyro Gyra（乐队）",life:"活跃 1974 起",country:"美国",role:"流畅爵士乐队",bio:"流畅爵士／融合的长青乐队，旋律明快、制作精良，《Morning Dance》是这一风格的代表作。"},

  "Kenny Garrett":{zh:"肯尼·加勒特",born:1960,country:"美国",role:"中音萨克斯 · 作曲",bio:"迈尔斯晚期乐队的中音萨克斯手，音色炽烈、律动强劲，融合放克与世界节奏，是当代最具能量的萨克斯之声。"},
  "Joseph Lamb":{zh:"约瑟夫·兰姆",born:1887,died:1960,country:"美国",role:"作曲 · 钢琴",bio:"‘古典拉格泰姆三巨头’中唯一的白人，也是乔普林的门生，作品结构精致、和声丰富，为拉格泰姆增添了细腻的抒情色彩。"},
  "Quincy Jones":{zh:"昆西·琼斯",born:1933,died:2024,country:"美国",role:"编曲 · 制作 · 乐队领袖",bio:"从比波普编曲家到流行音乐巨擘的传奇，制作了迈克尔·杰克逊《Thriller》；他的爵士大乐队作品同样气派非凡，影响横跨半个世纪。"},

  "Cecile McLorin Salvant":{zh:"塞西尔·麦克洛林·萨尔万特",born:1989,country:"美国",role:"演唱",bio:"当代最受瞩目的爵士女声，音域宽广、戏剧性十足，擅长挖掘被遗忘的老歌并赋予机智的当代解读，已数获格莱美。"},
  "Esperanza Spalding":{zh:"埃斯佩兰萨·斯波尔丁",born:1984,country:"美国",role:"贝斯 · 演唱 · 作曲",bio:"集贝斯、演唱与作曲于一身的天才，2011 年击败众多流行巨星夺得格莱美最佳新人，把爵士、灵魂与艺术流行熔于一炉。"},
  "Robert Glasper":{zh:"罗伯特·格拉斯珀",born:1978,country:"美国",role:"钢琴 · 制作",bio:"连接爵士与新灵魂、嘻哈的关键人物，《Black Radio》系列屡获格莱美，重新定义了爵士与当代黑人流行乐的关系。"},
  "Vijay Iyer":{zh:"维杰·艾耶尔",born:1971,country:"美国",role:"钢琴 · 作曲",bio:"印度裔的钢琴家与作曲家，物理学博士出身，以节奏的数学结构和跨文化视野著称，是当代最具知识分子气质的爵士声音之一。"},
  "Christian Scott":{zh:"克里斯蒂安·斯科特",born:1983,country:"美国",role:"小号 · 作曲",bio:"新奥尔良出身的小号革新者（又名 aTunde Adjuah），以‘伸展音乐’理念融合嘻哈、电子与各族裔节奏，是当代爵士的先锋之声。"},
  "Makaya McCraven":{zh:"马卡亚·麦克雷文",born:1983,country:"美国",role:"鼓 · 制作",bio:"芝加哥的鼓手兼制作人，把现场即兴录音剪辑重组为嘻哈式的‘节拍科学’，是当代爵士与采样文化交汇处的代表。"},
  "Kamasi Washington":{zh:"卡马西·华盛顿",born:1981,country:"美国",role:"次中音萨克斯 · 作曲",bio:"洛杉矶的萨克斯巨匠，以宏大编制、灵性氛围与嘻哈血脉掀起新一代爵士复兴，三小时巨制《The Epic》是当代爵士的现象级作品。"},

  "Snarky Puppy":{zh:"Snarky Puppy（乐队）",life:"活跃 2004 起",country:"美国",role:"融合爵士集体",bio:"由迈克尔·里格领衔的大型器乐集体，融合放克、世界音乐与融合爵士，以高能现场和多次格莱美把器乐爵士带给年轻一代。"},
  "BadBadNotGood":{zh:"BadBadNotGood（乐队）",life:"活跃 2010 起",country:"加拿大",role:"爵士／嘻哈乐队",bio:"多伦多的年轻四人组，从翻奏嘻哈节拍起家，把爵士、放克与电子嫁接，常与说唱歌手合作，是新一代跨界爵士的代表。"},
  "GoGo Penguin":{zh:"GoGo Penguin（乐队）",life:"活跃 2009 起",country:"英国",role:"原声电子三重奏",bio:"曼彻斯特的钢琴三重奏，以电子舞曲式的律动、极简主义动机和缜密编排打造‘原声电子’声音，深受新生代听众喜爱。"},
  "The Cinematic Orchestra":{zh:"电影感管弦乐团（乐队）",life:"活跃 1999 起",country:"英国",role:"爵士／电子乐队",bio:"杰森·斯温斯科领衔的英国乐团，把爵士现场与电子制作、弦乐编排融成电影般的氛围，《To Build a Home》广为流传。"},
  "Jazzanova":{zh:"Jazzanova（乐队）",life:"活跃 1995 起",country:"德国",role:"Nu-Jazz 制作团体",bio:"柏林的 DJ／制作人集体，是 2000 年代‘新爵士’（nu-jazz）与浩室爵士的代表，把碎拍、桑巴与灵魂乐缝合成都市夜色。"},
  "St Germain":{zh:"圣日耳曼",born:1969,country:"法国",role:"浩室爵士制作人",bio:"法国制作人卢多维克·纳瓦尔的化名，把深浩室、爵士采样与布鲁斯缝合，《Tourist》是‘house 爵士’的里程碑。"},
  "Sons of Kemet":{zh:"Sons of Kemet（乐队）",life:"活跃 2011–2023",country:"英国",role:"新爵士乐队",bio:"萨克斯手沙巴卡·哈钦斯领衔的伦敦四人组，编制为萨克斯、大号与双鼓，把加勒比律动与政治呐喊熔成炽热的现场能量。"},
  "Ezra Collective":{zh:"以斯拉合奏团（乐队）",life:"活跃 2012 起",country:"英国",role:"新爵士乐队",bio:"伦敦新爵士浪潮的领军乐队，融合 Afrobeat、雷鬼与嘻哈的炽热律动，2023 年凭《Where I'm Meant to Be》成为首支夺得水星奖的爵士专辑。"},
  "Nubya Garcia":{zh:"努比亚·加西亚",born:1991,country:"英国",role:"次中音萨克斯",bio:"伦敦新爵士浪潮的代表萨克斯手，把加勒比、Afrobeat 与精神爵士的根脉编织进深沉宽广的音色，《Source》广受赞誉。"},

  "4hero":{zh:"4hero（乐队）",life:"活跃 1990 起",country:"英国",role:"鼓打贝斯／灵魂电子",bio:"伦敦碎拍先锋，从鼓打贝斯走向交响化的灵魂电子，《Two Pages》把爵士、弦乐与未来主义节拍缝合，是英伦新爵士电子的里程碑。"},
  "Acoustic Alchemy":{zh:"原声炼金（乐队）",life:"活跃 1981 起",country:"英国",role:"流畅爵士乐队",bio:"以双吉他（钢弦+尼龙弦）交织为标志的流畅爵士长青组合，旋律温暖明快，是 GRP 厂牌的招牌之声。"},
  "Al Cohn":{zh:"阿尔·科恩",born:1925,died:1988,country:"美国",role:"次中音萨克斯 · 编曲",bio:"出自伍迪·赫尔曼乐队的‘四兄弟’传统，音色温润的冷／比波普萨克斯手与出色编曲家，常与佐特·西姆斯搭档。"},
  "Al Haig":{zh:"阿尔·黑格",born:1922,died:1982,country:"美国",role:"钢琴",bio:"最早把比波普语汇带上钢琴的白人乐手之一，曾为帕克、吉莱斯皮伴奏，触键清晰、律动精准。"},
  "Al Jarreau":{zh:"阿尔·贾罗",born:1940,died:2017,country:"美国",role:"演唱",bio:"以惊人的拟声与人声打击技巧著称的爵士／节奏布鲁斯歌手，是唯一在爵士、流行、节奏布鲁斯三类别都获格莱美的歌手。"},
  "Albert Mangelsdorff":{zh:"阿尔伯特·曼格尔斯多夫",born:1928,died:2005,country:"德国",role:"长号",bio:"欧洲自由爵士的代表长号手，以多音奏法（同时发出和声）开拓了长号的边界，是德国战后爵士的旗帜人物。"},
  "Alfa Mist":{zh:"阿尔法·密斯特",born:1990,country:"英国",role:"键盘 · 制作 · 说唱",bio:"嘻哈制作人出身的伦敦键盘手，把低保真节拍、内省钢琴与爵士即兴融成都市夜色，是新一代英伦爵士的代表。"},
  "Allan Holdsworth":{zh:"艾伦·霍兹沃思",born:1946,died:2017,country:"英国",role:"吉他",bio:"以丝滑的连奏（legato）和外行人难以理解的和声著称的融合吉他大师，被无数吉他手奉为‘吉他手的吉他手’。"},
  "Ambrose Akinmusire":{zh:"安布罗斯·阿金穆希雷",born:1982,country:"美国",role:"小号 · 作曲",bio:"奥克兰出身的当代小号思想家，音色脆弱而锐利，把后波普、室内乐与社会关怀写成结构繁复的作品，是 Blue Note 的当代旗手之一。"},
  "André Previn":{zh:"安德烈·普列文",born:1929,died:2019,country:"美国",role:"钢琴 · 指挥 · 作曲",bio:"横跨爵士、古典与好莱坞配乐的全才，既是冷爵士钢琴家，又是名指挥与四获奥斯卡的电影作曲家。"},
  "Andrew Cyrille":{zh:"安德鲁·西里尔",born:1939,country:"美国",role:"鼓",bio:"塞西尔·泰勒乐队的长期鼓手，自由爵士打击乐的诗人，以色彩与空间感重新定义了鼓在前卫音乐中的角色。"},
  "Andy Kirk":{zh:"安迪·柯克",born:1898,died:1992,country:"美国",role:"大乐队领袖 · 大号",bio:"堪萨斯城摇摆名团‘欢乐之云’的领班，乐队因钢琴手玛丽·卢·威廉姆斯的编曲而声名远扬。"},
  "Anita O'Day":{zh:"阿妮塔·奥黛",born:1919,died:2006,country:"美国",role:"演唱",bio:"清脆机智、节奏感凌厉的摇摆女声，无惧失去部分味觉仍以独特的乐句自成一格，纪录片中的纽波特演出成为传奇。"},
  "Antonio Hart":{zh:"安东尼奥·哈特",born:1968,country:"美国",role:"中音萨克斯",bio:"罗伊·哈格罗夫的老搭档，音色饱满、扎根传统的新生代中音萨克斯手，是 1990 年代新古典浪潮的中坚。"},
  "Art Farmer":{zh:"阿特·法默",born:1928,died:1999,country:"美国",role:"小号 · 短号",bio:"抒情含蓄的硬波普小号大师，后改奏自己设计的‘flumpet’，音色温柔而精致，旅居维也纳多年。"},
  "Art Farmer & Benny Golson":{zh:"法默与戈尔森的爵士六重奏",life:"活跃 1959–1962",country:"美国",role:"硬波普乐队（Jazztet）",bio:"小号手法默与萨克斯手戈尔森共同领衔的‘爵士六重奏’（Jazztet），以精致的编曲与三管音色成为硬波普的优雅代表。"},
  "Art Taylor":{zh:"阿特·泰勒",born:1929,died:1995,country:"美国",role:"鼓",bio:"硬波普录音室里出镜率最高的鼓手之一，律动扎实可靠，晚年还以访谈集《Notes and Tones》记录了大批爵士同行的心声。"},
  "Arthur Blythe":{zh:"阿瑟·布莱思",born:1940,died:2017,country:"美国",role:"中音萨克斯",bio:"以颤动炽烈的音色著称的前卫中音萨克斯手，把自由爵士与放克、世界节奏结合，《Lenox Avenue Breakdown》别开生面。"},
  "Artie Shaw":{zh:"阿蒂·肖",born:1910,died:2004,country:"美国",role:"单簧管 · 大乐队领袖",bio:"与古德曼齐名的摇摆单簧管巨星，《Begin the Beguine》风靡全美；他厌倦名利、屡次解散乐队，最终彻底退出乐坛。"},
  "Arturo Sandoval":{zh:"阿图罗·桑多瓦尔",born:1949,country:"美国",role:"小号",bio:"古巴出身的炫技小号大师，伊拉克雷乐队的创始成员，后投奔吉莱斯皮并叛逃美国，以惊人的高音与拉丁火力闻名。"},
  "Astrud Gilberto":{zh:"阿斯特鲁德·吉尔贝托",born:1940,died:2023,country:"巴西",role:"演唱",bio:"以《伊帕内玛的女孩》一夜成名的波萨诺瓦女声，原本只是录音室里的临时人选，那份天真清淡的嗓音却成了波萨诺瓦的国际名片。"},
  "Avishai Cohen":{zh:"阿维沙伊·科恩",born:1970,country:"以色列",role:"贝斯 · 作曲",bio:"以色列贝斯手与作曲家，把地中海、东欧与中东旋律织入现代爵士三重奏，是当代最具民族色彩的贝斯之声。"},
  "Baby Face Willette":{zh:"娃娃脸·威莱特",born:1933,died:1971,country:"美国",role:"哈蒙德风琴",bio:"福音背景出身的灵魂爵士风琴手，在 Blue Note 留下炽热的录音后便神秘隐退，生平至今笼罩谜团。"},
  "Baden Powell":{zh:"巴登·鲍威尔",born:1937,died:2000,country:"巴西",role:"吉他",bio:"巴西吉他大师，把古典技巧、桑巴与非洲–巴西的‘aff­ro-samba’熔于一炉，与诗人莫赖斯的合作是巴西音乐的瑰宝。"},
  "Barry Harris":{zh:"巴里·哈里斯",born:1929,died:2021,country:"美国",role:"钢琴 · 教育家",bio:"比波普的守护者与传奇教师，毕生以纯正的帕克／鲍威尔语汇演奏与授课，影响了无数后辈钢琴手。"},
  "Ben Webster":{zh:"本·韦伯斯特",born:1909,died:1973,country:"美国",role:"次中音萨克斯",bio:"艾灵顿乐队的招牌次中音，快板时粗粝咆哮、慢板时气声缠绵，被誉为最深情的抒情萨克斯之一，晚年定居欧洲。"},
  "Bennie Green":{zh:"本尼·格林",born:1923,died:1977,country:"美国",role:"长号",bio:"以摇摆律动与布鲁斯味著称的长号手，把比波普的灵巧与早期摇摆的暖意结合得轻松自然。"},
  "Benny Carter":{zh:"本尼·卡特",born:1907,died:2003,country:"美国",role:"中音萨克斯 · 编曲 · 小号",bio:"绰号‘The King’的多面巨匠，既是优雅的中音萨克斯典范，又是顶级编曲家，活跃了七十余年，《Further Definitions》是其代表作。"},
  "Benny Golson":{zh:"本尼·戈尔森",born:1929,died:2024,country:"美国",role:"次中音萨克斯 · 作曲",bio:"硬波普最重要的作曲家之一，《I Remember Clifford》《Killer Joe》等已成标准曲，他几乎是爵士史上被演奏最多的作曲家。"},
  "Benny Green":{zh:"本尼·格林",born:1963,country:"美国",role:"钢琴",bio:"师承蒙克与鲍威尔传统的硬波普钢琴家（与同名长号手不同），曾效力爵士信使与奥斯卡·彼得森，律动强劲、扎实纯正。"},
  "Big John Patton":{zh:"大约翰·巴顿",born:1935,died:2002,country:"美国",role:"哈蒙德风琴",bio:"Blue Note 灵魂爵士的中坚风琴手，律动深沉布鲁斯味十足，晚期还大胆探入前卫领域。"},
  "Bill Bruford":{zh:"比尔·布鲁福德",born:1949,country:"英国",role:"鼓",bio:"出自前卫摇滚名团 Yes 与 King Crimson 的鼓手，以电子鼓与复杂节拍转向融合爵士，乐队 Earthworks 别具一格。"},
  "Bill Dixon":{zh:"比尔·迪克森",born:1925,died:2010,country:"美国",role:"小号 · 作曲",bio:"自由爵士的理论家与组织者，1964 年‘十月革命’音乐节的发起人，小号音色幽暗、富于空间，兼具画家与教育家身份。"},
  "Bill Holman":{zh:"比尔·霍尔曼",born:1927,country:"美国",role:"编曲 · 次中音萨克斯",bio:"西海岸最受敬重的大乐队编曲家之一，以对位繁复又摇摆十足的写作著称，从肯顿乐队一路写到晚近。"},
  "Billy May":{zh:"比利·梅",born:1916,died:2004,country:"美国",role:"编曲 · 大乐队领袖",bio:"以滑奏簧管与诙谐活泼的编曲风格闻名的大乐队作家，为辛纳屈等众多歌手操刀，留下大量经典唱片。"},
  "Bing Crosby":{zh:"宾·克罗斯比",born:1903,died:1977,country:"美国",role:"演唱",bio:"‘低吟唱法’（crooning）的奠基者，借助麦克风把亲密随性的演唱推向大众，对后世所有流行歌手影响深远，与阿姆斯特朗惺惺相惜。"},
  "Binker and Moses":{zh:"宾克与摩西（二人组）",life:"活跃 2014 起",country:"英国",role:"萨克斯／鼓二重奏",bio:"萨克斯手宾克·戈尔丁与鼓手摩西·博伊德的二重奏，以萨克斯与鼓的赤裸对话掀起伦敦新爵士的炽热能量。"},
  "Bix Beiderbecke":{zh:"比克斯·拜德贝克",born:1903,died:1931,country:"美国",role:"短号",bio:"爵士史上第一位伟大的白人独奏家，短号音色如钟般清亮抒情，与阿姆斯特朗的热烈相映成趣，二十八岁因酗酒早逝，成为‘悲剧天才’的原型。"},
  "Bob Brookmeyer":{zh:"鲍勃·布鲁克迈耶",born:1929,died:2011,country:"美国",role:"阀键长号 · 编曲",bio:"冷爵士的阀键长号手与杰出编曲家，从马利根乐队到晚年的现代大乐队写作，始终走在和声探索的前沿。"},
  "Bob Cooper":{zh:"鲍勃·库珀",born:1925,died:1993,country:"美国",role:"次中音萨克斯 · 双簧管",bio:"西海岸冷爵士的多面手，也是少数把双簧管引入爵士的乐手，斯坦·肯顿乐队的成员。"},
  "Bob Crosby":{zh:"鲍勃·克罗斯比",born:1913,died:1993,country:"美国",role:"大乐队领袖 · 演唱",bio:"宾·克罗斯比之弟，他领衔的乐队与‘Bobcats’小组逆潮流地复兴迪克西兰，是摇摆时代里的‘怀旧派’。"},
  "Bob James":{zh:"鲍勃·詹姆斯",born:1939,country:"美国",role:"键盘 · 制作",bio:"流畅爵士与跨界融合的奠基人之一，《One》中的《Nautilus》《Take Me to the Mardi Gras》成为嘻哈采样的传奇富矿。"},
  "Bob James & David Sanborn":{zh:"鲍勃·詹姆斯与大卫·桑伯恩",life:"录于 1986",country:"美国",role:"流畅爵士合作",bio:"键盘手詹姆斯与萨克斯手桑伯恩的合作专辑《Double Vision》，是 1980 年代流畅爵士最畅销、最精致的范本。"},
  "Bob James & Earl Klugh":{zh:"鲍勃·詹姆斯与厄尔·克卢",life:"录于 1979",country:"美国",role:"流畅爵士合作",bio:"键盘与原声吉他的优雅二重唱《One on One》，把流畅爵士的温柔旋律打磨到极致，获格莱美肯定。"},
  "Bobbi Humphrey":{zh:"鲍比·汉弗莱",born:1950,country:"美国",role:"长笛",bio:"Blue Note 旗下第一位女性器乐领班，与拉里·缪伦合作的爵士放克专辑《Blacks and Blues》律动甜美、采样常客。"},
  "Bobby Hackett":{zh:"鲍比·哈克特",born:1915,died:1976,country:"美国",role:"短号 · 小号",bio:"音色温柔抒情的短号手，常被比作拜德贝克的传人，也为众多流行专辑吹奏过优美的独奏。"},
  "Bobby Jaspar":{zh:"鲍比·雅斯帕",born:1926,died:1963,country:"比利时",role:"次中音萨克斯 · 长笛",bio:"旅美的比利时冷爵士好手，音色细腻、长笛尤为出色，是 1950 年代欧洲爵士融入纽约主流的代表。"},
  "Bobby Timmons":{zh:"鲍比·蒂蒙斯",born:1935,died:1974,country:"美国",role:"钢琴 · 作曲",bio:"灵魂爵士的旋律高手，为爵士信使写下《Moanin'》、为阿德利写下《This Here》，把福音的暖意注入硬波普。"},
  "Bobby Watson":{zh:"鲍比·沃森",born:1953,country:"美国",role:"中音萨克斯 · 作曲",bio:"爵士信使的音乐总监出身，音色甜美富歌唱性的中音萨克斯手与作曲家，是 1980 年代新生代的代表。"},
  "Bola Sete":{zh:"博拉·塞特",born:1923,died:1987,country:"巴西",role:"吉他",bio:"旅美的巴西吉他大师，把古典、桑巴与爵士融为一体，曾与迪兹·吉莱斯皮、维斯·蒙哥马利合作。"},
  "Bonobo":{zh:"博诺博",born:1976,country:"英国",role:"制作人 · 多乐器",wiki:"Bonobo (musician)",bio:"西蒙·格林的化名，以温暖的采样、原声乐器与碎拍编织出细腻的当代下游电子，深受爵士与世界音乐滋养。"},
  "Booker Ervin":{zh:"布克·欧文",born:1930,died:1970,country:"美国",role:"次中音萨克斯",bio:"明格斯乐队的炽烈次中音，德州布鲁斯的根脉与硬朗的音色交织，《Book》系列展现其旺盛的即兴能量。"},
  "Booker Little":{zh:"布克·利特尔",born:1938,died:1961,country:"美国",role:"小号 · 作曲",bio:"才华横溢的小号天才与作曲家，与埃里克·多尔菲并肩探索前卫和声，《Out Front》是杰作，年仅二十三岁便因尿毒症离世。"},
  "Brand X":{zh:"Brand X（乐队）",life:"活跃 1975–1980",country:"英国",role:"融合爵士乐队",bio:"以菲尔·柯林斯的鼓为核心的英国融合名团，技术华丽又不乏幽默，是 1970 年代英伦融合的代表之一。"},
  "Buck Clayton":{zh:"巴克·克莱顿",born:1911,died:1991,country:"美国",role:"小号 · 编曲",bio:"贝西乐队的招牌小号手，音色明亮优雅，晚年以一系列‘Jam Sessions’录音延续了摇摆即兴的传统。"},
  "Bud Shank":{zh:"巴德·尚克",born:1926,died:2009,country:"美国",role:"中音萨克斯 · 长笛",bio:"西海岸冷爵士的代表，长笛与中音萨克斯俱佳，也参与了大量好莱坞录音与早期波萨诺瓦实验。"},
  "Buddy Collette":{zh:"巴迪·科莱特",born:1921,died:2010,country:"美国",role:"萨克斯 · 长笛 · 单簧管",bio:"奇科·汉密尔顿五重奏的多管乐手，也是推动洛杉矶音乐家工会种族融合的民权先驱。"},
  "Buddy DeFranco":{zh:"巴迪·德弗兰科",born:1923,died:2014,country:"美国",role:"单簧管",bio:"把单簧管带入比波普时代的少数大师之一，技术无懈可击，在单簧管式微的年代里坚守这件乐器的现代可能。"},
  "Buddy Rich":{zh:"巴迪·里奇",born:1917,died:1987,country:"美国",role:"鼓 · 大乐队领袖",bio:"公认技术最惊人的爵士鼓手，自幼登台、从不识谱，以雷霆般的速度与力量领衔自己的大乐队直到晚年。"},
  "Bugge Wesseltoft":{zh:"布格·韦塞尔托夫特",born:1964,country:"挪威",role:"键盘 · 制作",bio:"挪威‘未来爵士’的旗手，以‘New Conception of Jazz’项目把原声爵士与浩室、电子节拍融合，开拓了北欧的新爵士声景。"},
  "Bunk Johnson":{zh:"邦克·约翰逊",born:1879,died:1949,country:"美国",role:"小号",bio:"新奥尔良早期的传奇人物，1940 年代被乐迷‘重新发现’并配上假牙重返舞台，掀起了传统爵士复兴运动。"},
  "Cab Calloway":{zh:"卡布·卡洛威",born:1907,died:1994,country:"美国",role:"演唱 · 大乐队领袖",bio:"‘Hi-De-Ho’的拟声之王，棉花俱乐部的台柱，以华丽的舞台魅力与《Minnie the Moocher》风靡一时。"},
  "Cachao":{zh:"卡查奥",born:1918,died:2008,country:"古巴",role:"贝斯 · 作曲",wiki:"Israel López",bio:"曼波节奏的共同发明者与即兴‘descarga’（古巴jam）的开创者，被尊为古巴低音提琴的一代宗师。"},
  "Caldera":{zh:"Caldera（乐队）",life:"活跃 1976–1979",country:"美国",role:"拉丁融合乐队",bio:"洛杉矶的拉丁融合名团，把afro-cuban节奏、放克与融合爵士熔成绚烂的声响，是 1970 年代拉丁融合的隐藏珍宝。"},
  "Candido":{zh:"坎迪多",born:1921,died:2020,country:"古巴",role:"康加鼓",wiki:"Cándido Camero",bio:"把多只康加鼓同时演奏的技法带入美国爵士的古巴打击乐先驱，与吉莱斯皮、蒙克等无数大师合作，享年九十九岁。"},
  "Carl Perkins":{zh:"卡尔·珀金斯",born:1928,died:1958,country:"美国",role:"钢琴",bio:"西海岸的硬波普钢琴家（与摇滚同名者无关），因儿时小儿麻痹而以独特的横臂奏法弹奏低音，二十九岁早逝。"},
  "Carla Bley":{zh:"卡拉·布雷",born:1936,died:2023,country:"美国",role:"作曲 · 键盘 · 乐队领袖",bio:"自学成才的作曲奇才，爵士作曲家协会的核心，巨制《Escalator over the Hill》横跨爵士、摇滚与歌剧，幽默而宏大。"},
  "Charles L. Johnson":{zh:"查尔斯·L·约翰逊",born:1876,died:1950,country:"美国",role:"作曲 · 钢琴",bio:"高产的拉格泰姆作曲家，《Dill Pickles Rag》是销量最高的拉格泰姆之一，把这种音乐推向大众市场。"},
  "Charles Lloyd":{zh:"查尔斯·劳埃德",born:1938,country:"美国",role:"次中音萨克斯 · 长笛",bio:"以空灵抒情著称的萨克斯长者，1960 年代四重奏（基思·贾勒特在列）罕见地把爵士带入摇滚乐迷，晚年愈发深邃高产。"},
  "Charlie Barnet":{zh:"查理·巴尼特",born:1913,died:1991,country:"美国",role:"萨克斯 · 大乐队领袖",bio:"最早公开起用黑人乐手的白人领班之一，深受艾灵顿影响，《Cherokee》是其招牌摇摆名曲。"},
  "Charlie Christian":{zh:"查理·克里斯蒂安",born:1916,died:1942,country:"美国",role:"电吉他",bio:"电吉他作为独奏乐器的奠基者，在古德曼乐队中以单音线条预告了比波普，又在明顿俱乐部参与了比波普的孕育，二十五岁因肺结核早逝。"},
  "Charlie Parker & Dizzy Gillespie":{zh:"查理·帕克与迪兹·吉莱斯皮",life:"录于 1950",country:"美国",role:"比波普合作",bio:"比波普双雄的联袂录音，《Bird and Diz》凝固了这场音乐革命两位主帅最酣畅的对话。"},
  "Chick Webb":{zh:"奇克·韦布",born:1905,died:1939,country:"美国",role:"鼓 · 大乐队领袖",bio:"萨伏伊舞厅的‘擂台之王’，驼背残疾却以惊人的鼓艺称霸摇摆乐队对决，并发掘了少女埃拉·菲茨杰拉德。"},
  "Chico Hamilton":{zh:"奇科·汉密尔顿",born:1921,died:2013,country:"美国",role:"鼓 · 乐队领袖",bio:"以大提琴入编的室内乐式五重奏闻名的鼓手，把冷爵士引向精致细腻的方向，活跃逾七十年。"},
  "Chico O'Farrill":{zh:"奇科·奥法里尔",born:1921,died:2001,country:"古巴",role:"编曲 · 作曲",bio:"非洲–古巴爵士的编曲巨匠，《Afro-Cuban Jazz Suite》把拉丁节奏写成交响化的组曲，连接了曼波与现代爵士。"},
  "Chris Botti":{zh:"克里斯·波蒂",born:1962,country:"美国",role:"小号",bio:"音色甜美忧郁的流畅爵士小号明星，以唯美的旋律与跨界合作赢得大量大众听众。"},
  "Chris Connor":{zh:"克丽丝·康纳",born:1927,died:2009,country:"美国",role:"演唱",bio:"出自肯顿乐队的冷爵士女声，烟嗓低回、略带忧郁，是 1950 年代‘冷’演唱风格的代表之一。"},
  "Chu Berry":{zh:"楚·贝里",born:1908,died:1941,country:"美国",role:"次中音萨克斯",bio:"霍金斯之后最重要的摇摆次中音之一，音色饱满有力，正值巅峰时因车祸早逝，年仅三十三岁。"},
  "Chucho Valdes":{zh:"丘乔·巴尔德斯",born:1941,country:"古巴",role:"钢琴 · 作曲",bio:"伊拉克雷乐队的创始人，当代最伟大的拉丁爵士钢琴家，把古巴节奏与比波普、古典熔成磅礴的键盘语言，屡获格莱美。"},
  "Clarence Williams":{zh:"克拉伦斯·威廉姆斯",born:1898,died:1965,country:"美国",role:"钢琴 · 制作 · 作曲",bio:"新奥尔良出身的钢琴家与早期唱片制作人，组织了大量经典录音（贝谢、阿姆斯特朗在列），是爵士早期商业化的关键推手。"},
  "Claude Thornhill":{zh:"克劳德·桑希尔",born:1908,died:1965,country:"美国",role:"钢琴 · 大乐队领袖",bio:"以圆号、低音单簧管营造朦胧音色的大乐队领袖，吉尔·埃文斯的编曲在此孕育，直接启发了《Birth of the Cool》。"},
  "Claude Williamson":{zh:"克劳德·威廉姆森",born:1926,died:2016,country:"美国",role:"钢琴",bio:"鲍威尔式比波普语汇的西海岸传人，触键清晰、律动摇摆，是洛杉矶冷爵士场景的可靠钢琴手。"},
  "Clifford Jordan":{zh:"克利福德·乔丹",born:1931,died:1993,country:"美国",role:"次中音萨克斯",bio:"芝加哥出身、音色温厚的次中音萨克斯手，从硬波普一路走向精神爵士，《Glass Bead Games》是其杰作。"},
  "Conte Candoli":{zh:"孔特·坎多利",born:1927,died:2001,country:"美国",role:"小号",bio:"西海岸炙手可热的比波普小号手，长年坐镇‘灯塔全明星’与电视台乐队，火力十足。"},
  "Cootie Williams":{zh:"库蒂·威廉姆斯",born:1911,died:1985,country:"美国",role:"小号",bio:"艾灵顿乐队的‘哮吼’（growl）小号名家，以弱音器营造的人声化音色定义了乐队的丛林之声。"},
  "Curtis Fuller":{zh:"柯蒂斯·富勒",born:1934,died:2021,country:"美国",role:"长号",bio:"硬波普最流畅的长号手之一，柯川《Blue Train》与爵士信使的核心成员，乐句快捷如管乐。"},
  "Cy Touff":{zh:"赛·陶夫",born:1927,died:2003,country:"美国",role:"上低音小号",bio:"少见的上低音小号（bass trumpet）专精者，出自伍迪·赫尔曼乐队，音色介于小号与长号之间，别具一格。"},
  "D'Angelo":{zh:"迪安杰罗",born:1974,country:"美国",role:"演唱 · 键盘 · 制作",bio:"新灵魂（neo-soul）的关键人物，《Voodoo》以松弛的‘后拍’律动深受爵士与放克滋养，影响了罗伯特·格拉斯珀一代。"},
  "Danilo Perez":{zh:"达尼洛·佩雷斯",born:1965,country:"巴拿马",role:"钢琴 · 作曲",bio:"巴拿马钢琴家，把泛拉美节奏与现代爵士熔为一体，长期效力韦恩·肖特四重奏，是当代最重要的拉丁爵士钢琴声音之一。"},
  "Dave Pell":{zh:"戴夫·佩尔",born:1925,died:2017,country:"美国",role:"次中音萨克斯 · 乐队领袖",bio:"西海岸冷爵士的八重奏领班，编曲精巧、轻盈摇摆，是 1950 年代加州‘室内摇摆’的代表。"},
  "David Murray":{zh:"大卫·默里",born:1955,country:"美国",role:"次中音萨克斯 · 低音单簧管",bio:"高产的前卫巨匠，世界萨克斯四重奏成员，把自由爵士的咆哮与传统的咏唱熔于一炉，音色狂野而饱含历史。"},
  "David Sanborn":{zh:"大卫·桑伯恩",born:1945,died:2024,country:"美国",role:"中音萨克斯",bio:"史上影响最广的流畅／放克中音萨克斯音色，那种炽烈带哭腔的乐句出现在无数流行唱片里，定义了一个时代的‘萨克斯独奏’。"},
  "Deodato":{zh:"德奥达托",born:1942,country:"巴西",role:"键盘 · 编曲 · 制作",wiki:"Eumir Deodato",bio:"巴西键盘手与制作人，把《查拉图斯特拉如是说》改成放克版一举成名，是 CTI 时代爵士放克的金牌操盘手。"},
  "Derek Bailey":{zh:"德里克·贝利",born:1930,died:2005,country:"英国",role:"吉他",bio:"自由即兴的极端先锋，彻底抛弃旋律与调性，把吉他变成纯粹的声音探索工具，是欧洲非特质即兴的旗手。"},
  "Dewey Redman":{zh:"杜威·雷德曼",born:1931,died:2006,country:"美国",role:"次中音萨克斯",bio:"奥奈特·科尔曼乐队与‘新旧梦’的萨克斯手，德州布鲁斯根脉深厚的自由爵士声音，约书亚·雷德曼之父。"},
  "Dexter Gordon & Wardell Gray":{zh:"戈登与格雷的萨克斯对决",life:"录于 1947",country:"美国",role:"比波普对吹",bio:"两位次中音名家在《The Chase》中的‘萨克斯对决’，是比波普‘对吹’（tenor battle）传统最著名的录音之一。"},
  "Dinah Washington":{zh:"黛娜·华盛顿",born:1924,died:1963,country:"美国",role:"演唱",bio:"‘蓝调皇后’，咬字凌厉、情感炽烈的歌手，游走于爵士、布鲁斯与节奏布鲁斯之间，三十九岁因药物意外早逝。"},
  "Dizzy Gillespie / Sonny Stitt / Sonny Rollins":{zh:"吉莱斯皮 / 斯蒂特 / 罗林斯",life:"录于 1957",country:"美国",role:"比波普合作",bio:"《Sonny Side Up》中两位‘桑尼’萨克斯手在吉莱斯皮带领下的酣畅对吹，《The Eternal Triangle》是比波普即兴的巅峰之一。"},
  "DJ Krush":{zh:"DJ Krush",born:1962,country:"日本",role:"制作人 · 唱盘",bio:"日本嘻哈／碎拍宗师，以幽暗冷峻的氛围把爵士采样与说唱、电子缝合，是器乐嘻哈与抽象节拍的国际代表。"},
  "Dodo Marmarosa":{zh:"多多·马尔马罗萨",born:1925,died:2002,country:"美国",role:"钢琴",bio:"早期比波普的钢琴奇才，曾为帕克伴奏，触键灵动，却因健康与时运过早淡出，留下令人惋惜的‘隐世天才’传说。"},
  "Domi & JD Beck":{zh:"Domi 与 JD Beck（二人组）",life:"活跃 2018 起",country:"美国",role:"键盘／鼓二重奏",bio:"键盘手 Domi 与鼓手 JD Beck 的少年二人组，以眼花缭乱的速度与精度把融合爵士玩出嘻哈时代的新鲜感，由 Anderson .Paak 厂牌与 Blue Note 联合推出。"},
  "Don Pullen":{zh:"唐·普伦",born:1941,died:1995,country:"美国",role:"钢琴",bio:"既能弹出柔美旋律、又能以手背横扫琴键制造音簇的双面钢琴家，把自由爵士与福音、拉丁律动奇妙地结合。"},
  "Don Redman":{zh:"唐·雷德曼",born:1900,died:1964,country:"美国",role:"编曲 · 大乐队领袖",bio:"大乐队编曲的真正奠基者，在亨德森乐队里最早把簧管与铜管分声部写作，奠定了摇摆乐的整个语法。"},
  "Down to the Bone":{zh:"Down to the Bone（乐队）",life:"活跃 1996 起",country:"英国",role:"酸爵士／爵士放克",bio:"英国制作人主导的爵士放克企划，律动扎实、旋律亲切，是 1990 年代酸爵士俱乐部的常青之声。"},
  "Duke Jordan":{zh:"杜克·乔丹",born:1922,died:2006,country:"美国",role:"钢琴 · 作曲",bio:"帕克五重奏的钢琴手，写下标准曲《Jordu》，触键优雅抒情，晚年旅居丹麦广受爱戴。"},
  "Duke Pearson":{zh:"杜克·皮尔逊",born:1932,died:1980,country:"美国",role:"钢琴 · 作曲 · 制作",bio:"Blue Note 的金牌制作人与作曲家，旋律优美的硬波普钢琴手，《Sweet Honey Bee》等作品温润动人。"},
  "Earl Klugh":{zh:"厄尔·克卢",born:1953,country:"美国",role:"原声吉他",bio:"以纯指弹尼龙弦原声吉他著称的流畅爵士名家，旋律甜美抒情，从不使用拨片，自成一派。"},
  "Eddie Harris":{zh:"埃迪·哈里斯",born:1934,died:1996,country:"美国",role:"次中音萨克斯",bio:"勇于实验的灵魂爵士萨克斯手，最早使用电萨克斯，《Compared to What》（与莱斯·麦坎合作）成为时代金曲。"},
  "Eddie Henderson":{zh:"埃迪·亨德森",born:1940,country:"美国",role:"小号",bio:"医生出身的小号手，汉考克‘Mwandishi’电气乐队成员，游走于太空融合与硬波普之间，音色温润内敛。"},
  "Elis Regina & Antonio Carlos Jobim":{zh:"埃利斯·雷吉娜与裘宾",life:"录于 1974",country:"巴西",role:"巴西流行经典",bio:"巴西国宝级歌后雷吉娜与作曲大师裘宾的传世合作《Elis & Tom》，被公认为有史以来最美的巴西音乐唱片之一。"},
  "Ella Fitzgerald & Louis Armstrong":{zh:"埃拉与路易斯",life:"录于 1956–57",country:"美国",role:"爵士演唱合作",bio:"歌后菲茨杰拉德与阿姆斯特朗的对唱专辑《Ella and Louis》，清亮与沙哑的天作之合，是爵士演唱史上最温暖的录音。"},
  "Elmo Hope":{zh:"埃尔莫·霍普",born:1923,died:1967,country:"美国",role:"钢琴 · 作曲",bio:"蒙克与鲍威尔的挚友，作曲怪趣、和声独特的硬波普钢琴家，长期被低估，四十三岁早逝。"},
  "Erroll Garner":{zh:"埃罗尔·加纳",born:1921,died:1977,country:"美国",role:"钢琴",bio:"不识谱却自成一格的钢琴大师，左手如吉他扫弦、右手延迟入拍，《Concert by the Sea》风靡一时，写下标准曲《Misty》。"},
  "Erskine Hawkins":{zh:"厄斯金·霍金斯",born:1914,died:1993,country:"美国",role:"小号 · 大乐队领袖",bio:"绰号‘小号界的加百列’，其乐队的《Tuxedo Junction》《After Hours》是摇摆与节奏布鲁斯之间的桥梁。"},
  "Erykah Badu":{zh:"埃丽卡·巴杜",born:1971,country:"美国",role:"演唱",bio:"‘新灵魂教母’，以慵懒爵士化的演唱与即兴气质重塑了当代节奏布鲁斯，与众多爵士乐手深度交融。"},
  "Eubie Blake":{zh:"尤比·布莱克",born:1887,died:1983,country:"美国",role:"钢琴 · 作曲",bio:"拉格泰姆与跨步钢琴的活历史，百老汇黑人音乐剧《Shuffle Along》的作曲者，活到九十六岁仍在演出。"},
  "Evan Parker":{zh:"埃文·帕克",born:1944,country:"英国",role:"萨克斯",bio:"欧洲自由即兴的标志人物，以循环呼吸与多重发声制造连绵不绝的音流，把萨克斯独奏推向声学的极限。"},
  "Floating Points & Pharoah Sanders":{zh:"浮点与法老·桑德斯",life:"录于 2021",country:"英国／美国",role:"电子／精神爵士合作",bio:"电子制作人萨姆·谢泼德与萨克斯巨匠桑德斯、伦敦交响乐团合作的《Promises》，是桑德斯的绝唱级杰作，空灵浩瀚。"},
  "Flora Purim":{zh:"弗洛拉·普里姆",born:1942,country:"巴西",role:"演唱",bio:"巴西融合爵士的标志女声，‘重返永恒’早期成员，宽广灵动的嗓音如一件乐器，把巴西色彩注入融合爵士。"},
  "Fourplay":{zh:"Fourplay（乐队）",life:"活跃 1990 起",country:"美国",role:"流畅爵士超级组合",bio:"由鲍勃·詹姆斯领衔的流畅爵士‘超级组合’，制作精良、旋律优雅，是这一风格商业上最成功的乐队之一。"},
  "Frank Rosolino":{zh:"弗兰克·罗索利诺",born:1926,died:1978,country:"美国",role:"长号",bio:"技艺惊人、幽默风趣的西海岸长号大师，乐句流畅如歌，悲剧性地结束了自己的生命，年仅五十二岁。"},
  "Frank Wright":{zh:"弗兰克·赖特",born:1935,died:1990,country:"美国",role:"次中音萨克斯",bio:"绰号‘教父’的自由爵士萨克斯手，演奏狂野炽烈、充满福音式的呐喊，旅居欧洲多年。"},
  "Frankie Trumbauer":{zh:"弗兰基·特朗鲍尔",born:1901,died:1956,country:"美国",role:"C 调次中音萨克斯",bio:"早期爵士最具影响力的萨克斯手，轻盈流畅的乐句直接启发了莱斯特·扬，与拜德贝克的合作是白人早期爵士的高峰。"},
  "Gabor Szabo":{zh:"加博尔·萨博",born:1936,died:1982,country:"匈牙利",role:"吉他",bio:"逃离匈牙利的吉他手，把吉普赛、印度与迷幻摇滚的色彩注入爵士，催眠般的调式即兴自成一格。"},
  "Galliano":{zh:"Galliano（乐队）",life:"活跃 1988–1997",country:"英国",role:"酸爵士乐队",bio:"英国 Talkin' Loud 厂牌的旗舰酸爵士乐队，把放克、灵魂与诗朗诵融合，是 1990 年代伦敦俱乐部场景的核心。"},
  "Gary Bartz":{zh:"加里·巴茨",born:1940,country:"美国",role:"中音萨克斯",bio:"从迈尔斯电气乐队走来的萨克斯手，‘NTU Troop’把精神爵士、放克与黑人意识结合，是采样文化钟爱的源头。"},
  "Gene Krupa":{zh:"吉恩·克鲁帕",born:1909,died:1973,country:"美国",role:"鼓 · 大乐队领袖",bio:"把鼓手推上明星地位的第一人，古德曼乐队《Sing, Sing, Sing》的狂热鼓点点燃了整个摇摆时代。"},
  "George Botsford":{zh:"乔治·博茨福德",born:1874,died:1949,country:"美国",role:"作曲",bio:"拉格泰姆作曲家，《Black and White Rag》节奏明快、流传极广，是拉格泰姆通俗化的代表作之一。"},
  "George Duke":{zh:"乔治·杜克",born:1946,died:2013,country:"美国",role:"键盘 · 制作",bio:"横跨融合、放克与流行的键盘巨匠，与扎帕、康复合作，制作功力深厚，是 1970–80 年代黑人融合乐的中坚。"},
  "George Gershwin / Paul Whiteman":{zh:"格什温 / 保罗·怀特曼",life:"首演 1924",country:"美国",role:"交响爵士",bio:"1924 年怀特曼乐团首演格什温的《蓝色狂想曲》，把爵士的语汇带入音乐厅，开创了‘交响爵士’的争议性尝试。"},
  "George Shearing":{zh:"乔治·希尔林",born:1919,died:2011,country:"英国",role:"钢琴",bio:"失明的英裔钢琴家，以‘锁定和声’（block chords）的招牌音响风靡美国，写下标准曲《Lullaby of Birdland》。"},
  "Geri Allen":{zh:"杰莉·艾伦",born:1957,died:2017,country:"美国",role:"钢琴 · 作曲",bio:"连接传统与前卫的钢琴家与作曲家，M-Base 集体的早期成员，触键富于歌唱性，也是杰出的爵士教育家。"},
  "Gerry Mulligan & Chet Baker":{zh:"马利根与切特·贝克",life:"活跃 1952 起",country:"美国",role:"冷爵士合作",bio:"马利根‘无钢琴’四重奏中上低音萨克斯与小号的对位之美，定义了西海岸冷爵士最经典的二重唱声音。"},
  "Gerry Mulligan & Thelonious Monk":{zh:"马利根遇见蒙克",life:"录于 1957",country:"美国",role:"冷爵士／硬波普合作",bio:"冷爵士的马利根与怪才蒙克的相遇，《Mulligan Meets Monk》是两种截然不同气质的奇妙碰撞。"},
  "Gigi Gryce":{zh:"吉吉·格莱斯",born:1925,died:1983,country:"美国",role:"中音萨克斯 · 作曲",bio:"学院派出身的硬波普作曲家与中音萨克斯手，与克利福德·布朗、唐纳德·伯德合作，盛年时却毅然退出乐坛转任教师。"},
  "Gil Evans":{zh:"吉尔·埃文斯",born:1912,died:1988,country:"加拿大",role:"编曲 · 作曲",bio:"二十世纪最伟大的爵士编曲家之一，与迈尔斯合作的《Miles Ahead》《Sketches of Spain》是管弦织体的不朽典范。"},
  "Glenn Miller":{zh:"格伦·米勒",born:1904,died:1944,country:"美国",role:"大乐队领袖 · 长号",bio:"摇摆时代最畅销的乐队领袖，以单簧管领奏簧管的招牌音色风靡全美，二战中飞机失踪、遗体至今未寻获。"},
  "Globe Unity Orchestra":{zh:"环球统一乐团",life:"活跃 1966 起",country:"德国",role:"自由爵士大乐团",bio:"由钢琴家亚历山大·冯·施利彭巴赫创立的欧洲自由爵士大乐团，把集体即兴扩展到大编制，是欧陆前卫的旗舰。"},
  "Gonzalo Rubalcaba":{zh:"贡萨洛·鲁巴尔卡巴",born:1963,country:"古巴",role:"钢琴",bio:"技惊四座的古巴钢琴家，把惊人的技术、动态控制与古巴节奏结合，由查理·海登发掘走向国际，屡获格莱美。"},
  "Gotan Project":{zh:"Gotan Project（乐队）",life:"活跃 1999 起",country:"法国／阿根廷",role:"电子探戈",bio:"法–阿三人组，把探戈、电子节拍与爵士采样缝成性感的‘电子探戈’，《La Revancha del Tango》风靡全球俱乐部。"},
  "Greg Osby":{zh:"格雷格·奥斯比",born:1960,country:"美国",role:"中音萨克斯",bio:"M-Base 集体的核心成员，以错位节奏与抽象旋律探索后波普的新可能，也是 Blue Note 提携新人的伯乐。"},
  "Gregory Porter":{zh:"格雷戈里·波特",born:1971,country:"美国",role:"演唱",bio:"以温暖醇厚的男中音与福音、灵魂底色风靡全球的当代爵士歌手，《Liquid Spirit》让爵士演唱重回大众视野。"},
  "Guru":{zh:"Guru",born:1961,died:2010,country:"美国",role:"说唱",wiki:"Guru (rapper)",bio:"嘻哈组合 Gang Starr 的主唱，其《Jazzmatazz》系列把真正的爵士大师请进录音室与说唱对话，开创了爵士说唱的范式。"},
  "Hank Jones":{zh:"汉克·琼斯",born:1918,died:2010,country:"美国",role:"钢琴",bio:"优雅克制、品味无瑕的钢琴绅士（瑟德·琼斯与艾尔文·琼斯之兄），伴奏与独奏俱臻化境，活跃逾六十年直至离世。"},
  "Harold Land":{zh:"哈罗德·兰德",born:1928,died:2001,country:"美国",role:"次中音萨克斯",bio:"克利福德·布朗–马克斯·罗奇五重奏的原次中音，音色硬朗深沉，是西海岸硬波普被低估的重要声音。"},
  "Harry Connick Jr.":{zh:"哈里·康尼克",born:1967,country:"美国",role:"演唱 · 钢琴",bio:"新奥尔良出身的歌手钢琴家，凭电影《当哈利遇见莎莉》原声走红，把摇摆传统带回流行主流，亦活跃于影视。"},
  "Harry James":{zh:"哈里·詹姆斯",born:1916,died:1983,country:"美国",role:"小号 · 大乐队领袖",bio:"技术华丽、音色嘹亮的摇摆小号巨星，曾发掘青年辛纳屈，是摇摆时代最受欢迎的乐队领袖之一。"},
  "Helen Humes":{zh:"海伦·休姆斯",born:1913,died:1981,country:"美国",role:"演唱",bio:"贝西乐队的女声，能唱布鲁斯也能唱抒情慢歌，嗓音明亮甜美，活跃于摇摆与节奏布鲁斯之间。"},
  "Helen Merrill":{zh:"海伦·梅丽尔",born:1930,country:"美国",role:"演唱",bio:"气声缥缈、情感细腻的冷爵士女声，与克利福德·布朗合作的同名专辑（昆西·琼斯编曲）是抒情演唱的瑰宝。"},
  "Henry 'Red' Allen":{zh:"亨利·'瑞德'·艾伦",born:1908,died:1967,country:"美国",role:"小号 · 演唱",bio:"新奥尔良出身、富于现代感的摇摆小号手，乐句大胆、节奏自由，被前卫乐迷追认为超前时代的革新者。"},
  "Henry Threadgill":{zh:"亨利·思雷吉尔",born:1944,country:"美国",role:"萨克斯 · 长笛 · 作曲",bio:"AACM 出身的作曲大师，以奇特编制与严密结构自成体系，2016 年凭《In for a Penny, In for a Pound》获普利策音乐奖。"},
  "Herb Geller":{zh:"赫布·盖勒",born:1928,died:2013,country:"美国",role:"中音萨克斯",bio:"西海岸的比波普中音好手，音色明快流畅，后半生旅居德国，活跃于欧洲电台乐队。"},
  "Herbie Mann":{zh:"赫比·曼",born:1930,died:2003,country:"美国",role:"长笛",bio:"把长笛确立为爵士主奏乐器的先行者，勇于拥抱波萨诺瓦、放克、世界音乐，是商业上最成功的爵士长笛手。"},
  "Hermeto Pascoal":{zh:"埃尔梅托·帕斯科亚尔",born:1936,country:"巴西",role:"多乐器 · 作曲",bio:"白化症的巴西鬼才，能在茶壶、水与玩具上奏乐的‘声音巫师’，迈尔斯称他为‘世上最伟大的音乐家之一’。"},
  "Hiroshima":{zh:"Hiroshima（乐队）",life:"活跃 1974 起",country:"美国",role:"亚裔融合乐队",bio:"洛杉矶的日裔美国乐队，把日本筝（koto）、太鼓与融合爵士、节奏布鲁斯结合，是亚裔美国音乐的先声。"},
  "Howard McGhee":{zh:"霍华德·麦吉",born:1918,died:1987,country:"美国",role:"小号",bio:"连接摇摆与比波普的过渡期小号名家，曾与帕克在西海岸合作，技术华丽，1960 年代复出后宝刀未老。"},
  "Howard Rumsey":{zh:"霍华德·拉姆齐",born:1917,died:2015,country:"美国",role:"贝斯 · 乐队领袖",bio:"西海岸冷爵士的组织者，在‘灯塔’俱乐部主持‘全明星’周末爵士聚会十余年，是加州爵士场景的关键推手。"},
  "Hubert Laws":{zh:"休伯特·劳斯",born:1939,country:"美国",role:"长笛",bio:"古典与爵士双修的长笛大师，技术无懈可击，在 CTI 厂牌把爵士长笛带向交响化的优雅与流行的亲和。"},
  "ICP Orchestra":{zh:"ICP 管弦乐团",life:"活跃 1967 起",country:"荷兰",role:"自由爵士乐团",bio:"由钢琴家米沙·门格尔贝格与鼓手汉·本宁克创立的荷兰即兴乐团，把蒙克、艾灵顿与达达式的幽默自由地拼贴。"},
  "Idris Muhammad":{zh:"伊德里斯·穆罕默德",born:1939,died:2014,country:"美国",role:"鼓",bio:"新奥尔良出身、律动深沉的鼓手，灵魂爵士与爵士放克的节奏大师，《Power of Soul》是采样常客。"},
  "Illinois Jacquet":{zh:"伊利诺伊·杰凯",born:1922,died:2004,country:"美国",role:"次中音萨克斯",bio:"以《Flying Home》中嘶吼的独奏开创了节奏布鲁斯‘吼叫萨克斯’先河的摇摆名家，现场极具煽动力。"},
  "Immanuel Wilkins":{zh:"伊曼纽尔·威尔金斯",born:1997,country:"美国",role:"中音萨克斯 · 作曲",bio:"费城出身的新生代领军萨克斯手，把炽烈的灵性、福音根脉与社会关怀写成结构宏大的作品，Blue Note 的当代希望。"},
  "Incognito":{zh:"Incognito（乐队）",life:"活跃 1979 起",country:"英国",role:"酸爵士／爵士放克",bio:"由让-保罗·莫尼克领衔的英国爵士放克长青乐队，是‘酸爵士’（acid jazz）运动的旗舰之一。"},
  "Irakere":{zh:"伊拉克雷（乐队）",life:"活跃 1973 起",country:"古巴",role:"古巴融合乐队",bio:"丘乔·巴尔德斯领衔的古巴超级乐队，把afro-cuban节奏、放克、摇滚与爵士熔成炸裂的声响，是古巴现代音乐的里程碑。"},
  "J. Russel Robinson":{zh:"J·拉塞尔·罗宾逊",born:1892,died:1963,country:"美国",role:"钢琴 · 作曲",bio:"白人拉格泰姆钢琴家与流行词曲作者，曾加入‘正宗迪克西兰爵士乐队’（ODJB），也写下众多畅销曲。"},
  "J.J. Johnson":{zh:"J·J·约翰逊",born:1924,died:2001,country:"美国",role:"长号 · 作曲",bio:"把比波普语汇移植到长号上的第一人，以惊人的流畅度证明这件笨重乐器也能跟上最快的即兴，重新定义了爵士长号。"},
  "J.J. Johnson & Kai Winding":{zh:"约翰逊与温丁（双长号）",life:"活跃 1954–1956",country:"美国",role:"双长号组合",bio:"两位长号大师组成的‘Jay and Kai’双长号五重奏，音色交织默契、广受欢迎，是 1950 年代最讨喜的小组之一。"},
  "Jabbo Smith":{zh:"贾博·史密斯",born:1908,died:1991,country:"美国",role:"小号",bio:"1920 年代唯一能在技巧上叫板阿姆斯特朗的小号天才，乐句大胆冒进，却因时运与酗酒未能成名。"},
  "Jack McDuff":{zh:"杰克·麦克达夫",born:1926,died:2001,country:"美国",role:"哈蒙德风琴",bio:"灵魂爵士的招牌风琴手，律动滚烫、布鲁斯味十足，乐队曾提携青年吉他手乔治·本森。"},
  "Jack Montrose":{zh:"杰克·蒙特罗斯",born:1928,died:2006,country:"美国",role:"次中音萨克斯 · 编曲",bio:"西海岸冷爵士的萨克斯手与编曲家，以严谨的对位写作著称，是加州‘室内爵士’的代表之一。"},
  "Jack Teagarden":{zh:"杰克·蒂加登",born:1905,died:1964,country:"美国",role:"长号 · 演唱",bio:"德州出身的长号先驱，以布鲁斯味十足的滑奏和慵懒的歌声著称，被誉为爵士长号的奠基者之一。"},
  "Jacky Terrasson":{zh:"杰基·泰拉松",born:1965,country:"法国",role:"钢琴",bio:"法裔美籍钢琴家，以出人意料的重新编排与灵动的触键著称，1990 年代凭 Blue Note 首专一鸣惊人。"},
  "Jacob Collier":{zh:"雅各布·科利尔",born:1994,country:"英国",role:"多乐器 · 编曲 · 演唱",bio:"伦敦的音乐神童，以繁复的微分音和声、一人多轨的编排自成宇宙，把爵士、合唱与艺术流行熔为一炉，屡获格莱美。"},
  "Jaki Byard":{zh:"杰基·拜亚德",born:1922,died:1999,country:"美国",role:"钢琴",bio:"博学多才的‘历史百科’钢琴家，能从跨步一路弹到自由爵士，明格斯乐队的成员，也是杰出的教育家。"},
  "James P. Johnson":{zh:"詹姆斯·P·约翰逊",born:1894,died:1955,country:"美国",role:"钢琴 · 作曲",bio:"‘跨步钢琴之父’，连接拉格泰姆与摇摆的关键人物，法茨·沃勒的老师，写下《Charleston》风靡全美。"},
  "James Taylor Quartet":{zh:"詹姆斯·泰勒四重奏",life:"活跃 1987 起",country:"英国",role:"酸爵士乐队",bio:"以哈蒙德风琴主导的英国酸爵士乐队，翻奏复古电影配乐、律动火爆，是俱乐部场景的常青树。"},
  "Jamie Cullum":{zh:"杰米·卡伦",born:1979,country:"英国",role:"演唱 · 钢琴",bio:"把摇摆标准曲与流行翻唱、原创结合的英国歌手钢琴家，以充满活力的现场把爵士带给年轻一代。"},
  "Jamiroquai":{zh:"Jamiroquai（乐队）",life:"活跃 1992 起",country:"英国",role:"酸爵士／放克乐队",bio:"杰伊·凯领衔的英国放克乐队，把酸爵士、迪斯科与放克熔成商业巨大成功的舞曲，《Virtual Insanity》风靡全球。"},
  "Jan Garbarek":{zh:"扬·加巴雷克",born:1947,country:"挪威",role:"萨克斯",bio:"ECM 厂牌的标志性声音，以清冷辽阔、富于北欧民谣气质的萨克斯音色自成一派，与中世纪合唱团的合作广为流传。"},
  "Jan Hammer":{zh:"扬·哈默",born:1948,country:"捷克",role:"键盘 · 合成器",bio:"大慈悲管弦乐团的键盘手，把合成器演奏成会‘歌唱’的主奏乐器，《迈阿密风云》主题曲让他家喻户晓。"},
  "Jason Moran":{zh:"杰森·莫兰",born:1975,country:"美国",role:"钢琴 · 作曲",bio:"当代最具观念性的钢琴家之一，把嘻哈、视觉艺术与早期跨步钢琴并置，长期是后波普的实验先锋与策展人。"},
  "Jay McShann":{zh:"杰伊·麦克沙恩",born:1916,died:2006,country:"美国",role:"钢琴 · 大乐队领袖",bio:"堪萨斯城布鲁斯钢琴与大乐队的代表，他的乐队是青年查理·帕克登上录音舞台的起点。"},
  "Jazztronik":{zh:"Jazztronik",born:1971,country:"日本",role:"键盘 · 制作",bio:"野崎良太的企划，融合浩室、桑巴、古典与爵士的日本新爵士代表，舞池律动与器乐编排兼备。"},
  "Jerry Gonzalez":{zh:"杰里·冈萨雷斯",born:1949,died:2018,country:"美国",role:"小号 · 康加鼓",bio:"波多黎各裔的拉丁爵士先锋，‘Fort Apache Band’把蒙克、鲍威尔的曲目用afro-cuban节奏重塑，晚年定居马德里。"},
  "Jim Hall":{zh:"吉姆·霍尔",born:1930,died:2013,country:"美国",role:"吉他",bio:"现代爵士吉他最具诗意、最重室内乐对话的大师，音色温润、用音节制，深刻影响了梅瑟尼、弗里塞尔等后辈。"},
  "Jimmie Lunceford":{zh:"吉米·伦斯福德",born:1902,died:1947,country:"美国",role:"大乐队领袖",bio:"以精准的合奏、华丽的舞台呈现与‘two-beat’摇摆著称的乐队领袖，是 1930 年代最具娱乐性的大乐队之一。"},
  "Jimmie Noone":{zh:"吉米·努恩",born:1895,died:1944,country:"美国",role:"单簧管",bio:"新奥尔良单簧管的早期大师，音色圆润流畅，其‘顶尖俱乐部’乐队影响了本尼·古德曼等后辈。"},
  "Jimmy Dorsey":{zh:"吉米·多西",born:1904,died:1957,country:"美国",role:"中音萨克斯 · 单簧管 · 大乐队领袖",bio:"汤米·多西之兄，技艺精湛的簧管演奏家与摇摆乐队领袖，对中音萨克斯的发展影响深远。"},
  "Jimmy Heath":{zh:"吉米·希思",born:1926,died:2020,country:"美国",role:"次中音萨克斯 · 作曲",bio:"‘希思三兄弟’之一，杰出的硬波普作曲与编曲家，写下《Gingerbread Boy》等常被演奏的曲目，亦是受人爱戴的长者与教师。"},
  "Jimmy McGriff":{zh:"吉米·麦格里夫",born:1936,died:2008,country:"美国",role:"哈蒙德风琴",bio:"布鲁斯根脉极深的灵魂爵士风琴手，律动质朴有力，《I Got a Woman》是风琴爵士的舞池经典。"},
  "Jimmy Rushing":{zh:"吉米·拉欣",born:1901,died:1972,country:"美国",role:"演唱",bio:"绰号‘Mr. Five by Five’的贝西乐队布鲁斯男声，嗓音洪亮穿透力强，是大乐队布鲁斯演唱的典范。"},
  "Jo Stafford":{zh:"乔·斯塔福德",born:1917,died:2008,country:"美国",role:"演唱",bio:"音准完美、咬字清晰的摇摆与流行女声，二战中深受士兵喜爱，也以滑稽走音的恶搞专辑展现幽默一面。"},
  "Joe Armon-Jones":{zh:"乔·阿蒙-琼斯",born:1993,country:"英国",role:"键盘",bio:"伦敦新爵士场景的键盘手（Ezra Collective 成员），把dub、放克与精神爵士融成温暖迷离的独奏作品。"},
  "Joe Cuba":{zh:"乔·库巴",born:1931,died:2009,country:"美国",role:"康加鼓 · 乐队领袖",bio:"‘布加洛之父’，波多黎各裔的纽约打击乐手，《Bang! Bang!》把拉丁、灵魂与英语歌词混搭，掀起 1960 年代布加洛热潮。"},
  "Joe Farrell":{zh:"乔·法雷尔",born:1937,died:1986,country:"美国",role:"萨克斯 · 长笛",bio:"‘重返永恒’早期成员，技术全面的萨克斯与长笛手，在 CTI 厂牌留下融合与后波普兼备的优秀独奏专辑。"},
  "Joe Gordon":{zh:"乔·戈登",born:1928,died:1963,country:"美国",role:"小号",bio:"被低估的硬波普小号手，曾效力蒙克与肖蒂·罗杰斯，《Lookin' Good》展现其灵动才华，却因火灾英年早逝。"},
  "Joe Pass":{zh:"乔·帕斯",born:1929,died:1994,country:"美国",role:"吉他",bio:"独奏吉他的巅峰，以一把吉他同时演绎旋律、和声与低音，《Virtuoso》系列证明了爵士吉他无伴奏独奏的全部可能。"},
  "Joe Williams":{zh:"乔·威廉姆斯",born:1918,died:1999,country:"美国",role:"演唱",bio:"贝西乐队的男声，把布鲁斯唱得既洪亮又优雅，《Every Day I Have the Blues》是大乐队布鲁斯演唱的标杆。"},
  "Joe Zawinul":{zh:"乔·扎维努尔",born:1932,died:2007,country:"奥地利",role:"键盘 · 作曲",bio:"奥地利键盘大师，气象报告的灵魂与共同创始人，电钢琴与合成器的先驱，为阿德利写下《Mercy, Mercy, Mercy》，是融合爵士的奠基者之一。"},

  "Joel Ross":{zh:"乔尔·罗斯",born:1995,country:"美国",role:"颤音琴 · 作曲",bio:"芝加哥出身的新生代颤音琴领军人物，触键流动如水、和声当代，是 Blue Note 当下最受瞩目的青年作曲家之一。"},
  "John Lewis":{zh:"约翰·刘易斯",born:1920,died:2001,country:"美国",role:"钢琴 · 作曲",bio:"现代爵士四重奏的音乐总监与灵魂，把巴洛克的对位、赋格的严谨引入爵士，是‘第三流派’最优雅的实践者。"},
  "John Scofield":{zh:"约翰·斯科菲尔德",born:1951,country:"美国",role:"吉他",bio:"音色微带失真、乐句歪斜布鲁斯味十足的吉他大师，迈尔斯 1980 年代乐队成员，从后波普一路玩到放克 jam。"},
  "Johnny Dodds":{zh:"约翰尼·多兹",born:1892,died:1940,country:"美国",role:"单簧管",bio:"新奥尔良单簧管的代表，阿姆斯特朗‘热力五人组’的核心，音色炽烈、布鲁斯感深厚，是早期爵士的标志声音。"},
  "Johnny Hodges":{zh:"约翰尼·霍奇斯",born:1907,died:1970,country:"美国",role:"中音萨克斯",bio:"艾灵顿乐队的招牌中音，以无与伦比的滑音与丝滑甜美的抒情著称，被公认为爵士史上最美的中音萨克斯音色。"},
  "Joseph Jarman":{zh:"约瑟夫·贾曼",born:1937,died:2019,country:"美国",role:"萨克斯 · 多乐器",bio:"芝加哥艺术合奏团的成员，AACM 的元老，把诗朗诵、戏剧与多种乐器融入自由即兴，晚年成为佛教僧侣。"},
  "Julie London":{zh:"朱莉·伦敦",born:1926,died:2000,country:"美国",role:"演唱",bio:"以慵懒性感的气声闻名的冷爵士女声，《Cry Me a River》成为永恒经典，亦是当红影视明星。"},
  "Julius Hemphill":{zh:"朱利叶斯·亨普希尔",born:1938,died:1995,country:"美国",role:"中音萨克斯 · 作曲",bio:"世界萨克斯四重奏的核心作曲家，把布鲁斯根脉、放克与前卫结构熔于一炉，《Dogon A.D.》是自由爵士的杰作。"},
  "June Christy":{zh:"琼·克里斯蒂",born:1925,died:1990,country:"美国",role:"演唱",bio:"肯顿乐队走出的冷爵士女声，《Something Cool》以慵懒朦胧的音色定义了‘冷’演唱的氛围美学。"},
  "Kamaal Williams":{zh:"卡马尔·威廉姆斯",born:1989,country:"英国",role:"键盘 · 制作",bio:"伦敦新爵士的关键人物（曾用名 Henry Wu），把broken beat、放克与爵士融成性感的都市律动，Yussef Kamaal 的一半。"},
  "Kendrick Lamar":{zh:"肯德里克·拉马尔",born:1987,country:"美国",role:"说唱",bio:"当代最重要的说唱艺术家，《To Pimp a Butterfly》大量起用卡马西·华盛顿、桑德斯等爵士乐手，是嘻哈与爵士交融的里程碑，获普利策奖。"},
  "Kenny Clarke":{zh:"肯尼·克拉克",born:1914,died:1985,country:"美国",role:"鼓",bio:"比波普鼓的奠基人之一，把基本拍从底鼓移到吊镲、用底鼓打‘炸弹’重音，彻底解放了鼓的角色，后旅居巴黎。"},
  "Kenny Drew":{zh:"肯尼·德鲁",born:1928,died:1993,country:"美国",role:"钢琴",bio:"扎实优雅的硬波普钢琴家，曾参与柯川《Blue Train》，1960 年代起旅居丹麦，是欧洲爵士场景的中坚。"},
  "Kenny Kirkland":{zh:"肯尼·柯克兰",born:1955,died:1998,country:"美国",role:"钢琴",bio:"马萨利斯兄弟与斯汀乐队的键盘手，技术华丽、和声现代的后波普钢琴家，唯一的个人专辑成为绝响，四十三岁早逝。"},
  "Kid Ory":{zh:"基德·奥里",born:1886,died:1973,country:"美国",role:"长号",bio:"新奥尔良‘tailgate’长号风格的代表，早期爵士的奠基人之一，也是《Muskrat Ramble》的作者。"},
  "King Oliver":{zh:"金·奥利弗",born:1881,died:1938,country:"美国",role:"短号 · 乐队领袖",bio:"新奥尔良的短号王，‘克里奥尔爵士乐队’的领袖，提携并召来青年阿姆斯特朗，其录音是早期集体即兴的最高典范。"},
  "Koop":{zh:"Koop（乐队）",life:"活跃 1997 起",country:"瑞典",role:"Nu-Jazz 二人组",bio:"瑞典二人组，用大量原声采样拼贴出复古而摇摆的‘电子摇摆’，《Waltz for Koop》是 nu-jazz 的精致之作。"},
  "Kyoto Jazz Massive":{zh:"京都爵士盛会",life:"活跃 1992 起",country:"日本",role:"Nu-Jazz 二人组",bio:"沖野兄弟的企划，是日本俱乐部爵士与broken beat的旗帜，连接了 DJ 文化与现场爵士演奏。"},
  "Larry Young":{zh:"拉里·扬",born:1940,died:1978,country:"美国",role:"哈蒙德风琴",bio:"被誉为‘风琴上的柯川’，把调式与自由爵士引入哈蒙德风琴，《Unity》是风琴爵士最具现代意识的杰作。"},
  "Laurindo Almeida":{zh:"劳林多·阿尔梅达",born:1917,died:1995,country:"巴西",role:"吉他",bio:"旅美的巴西古典吉他大师，早在 1953 年便把巴西节奏与冷爵士结合，是波萨诺瓦风潮的预言者。"},
  "Lee Konitz & Gerry Mulligan":{zh:"科尼茨与马利根",life:"录于 1953",country:"美国",role:"冷爵士合作",bio:"中音萨克斯科尼茨与上低音萨克斯马利根在‘无钢琴’编制下的对位之作，是西海岸冷爵士室内化的典范。"},
  "Lee Ritenour":{zh:"李·里特诺",born:1952,country:"美国",role:"吉他",bio:"绰号‘Captain Fingers’的录音室吉他名家，横跨流畅爵士、融合与巴西音乐，技术全面、商业成功。"},
  "Lennie Niehaus":{zh:"伦尼·尼豪斯",born:1929,died:2020,country:"美国",role:"中音萨克斯 · 编曲",bio:"肯顿乐队的中音与编曲家，乐句明快利落，晚年成为克林特·伊斯特伍德电影（含《菜鸟帕克》）的配乐作曲家。"},
  "Lennie Tristano":{zh:"伦尼·特里斯塔诺",born:1919,died:1978,country:"美国",role:"钢琴 · 教育家",bio:"失明的冷爵士理论宗师，强调线条、对位与即兴的纯粹，1949 年便录下最早的自由即兴，门下出科尼茨、马什等高徒。"},
  "Lenny White":{zh:"伦尼·怀特",born:1949,country:"美国",role:"鼓",bio:"参与《Bitches Brew》、‘重返永恒’的核心鼓手，融合爵士节奏的奠基者之一，技术精准、律动强劲。"},
  "Leroy Jenkins":{zh:"勒罗伊·詹金斯",born:1932,died:2007,country:"美国",role:"小提琴 · 作曲",bio:"AACM 出身、把小提琴带入自由爵士前沿的大师，以即兴与当代作曲的结合拓展了弦乐的边界。"},
  "Les McCann":{zh:"莱斯·麦坎",born:1935,died:2023,country:"美国",role:"钢琴 · 演唱",bio:"灵魂爵士的标志人物，1969 年与埃迪·哈里斯在蒙特勒现场的《Compared to What》成为时代抗议金曲，律动深植福音。"},
  "Lonnie Liston Smith":{zh:"朗尼·利斯顿·史密斯",born:1940,country:"美国",role:"键盘",bio:"以‘宇宙回声’乐队闻名的精神／放克爵士键盘手，《Expansions》空灵律动，是嘻哈与浩室采样的常青源头。"},
  "Louis Prima":{zh:"路易斯·普里马",born:1910,died:1978,country:"美国",role:"小号 · 演唱",bio:"新奥尔良意裔的舞台魔王，把摇摆、跳跃布鲁斯与喜剧表演熔为一炉，拉斯维加斯的《The Wildest!》活力四射。"},
  "Lu Watters":{zh:"卢·沃特斯",born:1911,died:1989,country:"美国",role:"小号 · 乐队领袖",bio:"1940 年代迪克西兰复兴运动的旗手，‘耶尔巴布埃纳爵士乐队’忠实重现新奥尔良集体即兴的早期声音。"},
  "Luis Russell":{zh:"路易斯·拉塞尔",born:1902,died:1963,country:"巴拿马",role:"钢琴 · 大乐队领袖",bio:"巴拿马裔的早期大乐队领袖，其乐队以强劲的节奏组著称，后成为阿姆斯特朗的伴奏乐团。"},
  "Luiz Bonfa":{zh:"路易斯·邦法",born:1922,died:2001,country:"巴西",role:"吉他 · 作曲",bio:"巴西吉他与作曲大师，电影《黑色奥菲尔》的《Manhã de Carnaval》传遍世界，是波萨诺瓦最优美的旋律之一。"},
  "Lyle Mays":{zh:"莱尔·梅斯",born:1953,died:2020,country:"美国",role:"键盘 · 作曲",bio:"帕特·梅瑟尼乐队的共同作曲者与键盘手，以辽阔的音景与印象派和声塑造了那种标志性的‘电影感’当代爵士。"},
  "Ma Rainey":{zh:"玛·雷尼",born:1886,died:1939,country:"美国",role:"演唱",bio:"‘布鲁斯之母’，最早把民间布鲁斯带上舞台并录音的女歌手，影响了贝西·史密斯等整整一代布鲁斯歌者。"},
  "Machito":{zh:"马奇托",born:1908,died:1984,country:"古巴",role:"乐队领袖 · 沙球",bio:"非洲–古巴爵士的奠基人，其‘Afro-Cubans’乐队（编曲家马里奥·包扎主导）最早把古巴节奏与比波普系统融合。"},
  "Mal Waldron":{zh:"马尔·沃尔德伦",born:1925,died:2002,country:"美国",role:"钢琴 · 作曲",bio:"比莉·哈乐黛最后的伴奏者，以沉郁固执的固定音型（ostinato）著称的钢琴家，后旅居欧洲，风格愈发幽暗深邃。"},
  "Mammal Hands":{zh:"Mammal Hands（乐队）",life:"活跃 2012 起",country:"英国",role:"原声三重奏",bio:"英国 Gondwana 厂牌的萨克斯／钢琴／鼓三重奏，把极简、北欧与精神爵士融成冥想般的器乐声景。"},
  "Marc Moulin":{zh:"马克·穆兰",born:1942,died:2008,country:"比利时",role:"键盘 · 制作",bio:"比利时 nu-jazz 先驱，1970 年代乐队 Placebo 的领袖，晚年个人专辑《Top Secret》冷峻迷人，是欧陆电子爵士的代表。"},
  "Marty Paich":{zh:"马蒂·派奇",born:1925,died:1995,country:"美国",role:"编曲 · 钢琴",bio:"西海岸的编曲名家，其‘Dek-tette’小型大乐队为梅尔·托梅等操刀，写作精巧、摇摆灵动。"},
  "Mary Halvorson":{zh:"玛丽·哈尔沃森",born:1980,country:"美国",role:"吉他 · 作曲",bio:"当代最具辨识度的前卫吉他家，以滑音踏板制造的‘融化’音响自成一格，是 21 世纪新即兴音乐的领军作曲家。"},
  "Mary Lou Williams":{zh:"玛丽·卢·威廉姆斯",born:1910,died:1981,country:"美国",role:"钢琴 · 编曲 · 作曲",bio:"横跨拉格泰姆到比波普、唯一被各时代大师共同尊崇的女性巨匠，既为安迪·柯克编曲，又点拨蒙克、鲍威尔，晚年专注圣乐。"},
  "Maynard Ferguson":{zh:"梅纳德·弗格森",born:1928,died:2006,country:"加拿大",role:"小号 · 大乐队领袖",bio:"以惊人的超高音著称的小号巨匠，从肯顿乐队到自己的大乐队，《Birdland》《Rocky》主题曲让他广为人知。"},
  "McKinney's Cotton Pickers":{zh:"麦金尼的摘棉者（乐队）",life:"活跃 1926–1934",country:"美国",role:"早期大乐队",bio:"底特律的早期摇摆大乐队，在唐·雷德曼的编曲下成为 1920 年代末最精致的黑人乐队之一。"},
  "Medeski Martin & Wood":{zh:"Medeski Martin & Wood（乐队）",life:"活跃 1991 起",country:"美国",role:"爵士 jam 三重奏",bio:"风琴／贝斯／鼓三重奏，把放克、自由即兴与 jam 乐迷文化结合，是 1990 年代纽约 downtown 爵士的代表。"},
  "Melt Yourself Down":{zh:"Melt Yourself Down（乐队）",life:"活跃 2012 起",country:"英国",role:"全球爵士乐队",bio:"萨克斯手皮特·韦勒姆领衔的伦敦乐队，把北非、努比亚与朋克能量熔成炽热的舞台狂欢，是新爵士浪潮的躁动一翼。"},
  "Mezz Mezzrow":{zh:"梅兹·梅兹罗",born:1899,died:1972,country:"美国",role:"单簧管",bio:"狂热拥抱黑人文化的白人单簧管手，与贝谢合作录音，更以坦率的自传《Really the Blues》留名爵士史。"},
  "Michael Brecker":{zh:"迈克尔·布雷克",born:1949,died:2007,country:"美国",role:"次中音萨克斯",bio:"柯川之后影响最广的次中音萨克斯手，技术与情感兼备，活跃于融合、流行与原声爵士，留下无数传世独奏。"},
  "Mike Stern":{zh:"迈克·斯特恩",born:1953,country:"美国",role:"吉他",bio:"迈尔斯 1980 年代复出乐队的吉他手，把摇滚的失真与比波普的乐句结合，是融合吉他的代表声音之一。"},
  "Milford Graves":{zh:"米尔福德·格雷夫斯",born:1941,died:2021,country:"美国",role:"鼓",bio:"自由爵士打击乐的革命者，彻底抛弃固定拍、把鼓当作有机的脉搏来演奏，亦研究心律与草药的跨界奇人。"},
  "Milt Jackson":{zh:"米尔特·杰克逊",born:1923,died:1999,country:"美国",role:"颤音琴",bio:"现代爵士颤音琴的宗师，以缓慢的颤音与深厚的布鲁斯感著称，现代爵士四重奏的灵魂独奏者，绰号‘Bags’。"},
  "Misha Mengelberg":{zh:"米沙·门格尔贝格",born:1935,died:2017,country:"荷兰",role:"钢琴 · 作曲",bio:"荷兰即兴乐团 ICP 的共同创立者，把蒙克、艾灵顿与达达式的荒诞幽默熔为一体，是欧洲即兴音乐的灵魂人物。"},
  "Mondo Grosso":{zh:"Mondo Grosso",born:1967,country:"日本",role:"制作人 · 贝斯",bio:"大泽伸一的企划，从俱乐部爵士乐队起家，走向浩室与流行电子，是日本 nu-jazz／舞曲的代表制作人。"},
  "Moses Boyd":{zh:"摩西·博伊德",born:1991,country:"英国",role:"鼓 · 制作",bio:"伦敦新爵士的鼓手与制作人，把grime、dub与爵士节奏融合，《Dark Matter》获水星奖提名，是当下英伦节奏的弄潮儿。"},
  "Mr. Scruff":{zh:"Mr. Scruff",born:1972,country:"英国",role:"DJ · 制作人",bio:"以诙谐插画与海量黑胶选曲著称的曼彻斯特 DJ，把爵士、放克、嘻哈拼贴成俏皮的下游电子，《Keep It Unreal》自成一格。"},
  "Muggsy Spanier":{zh:"马格西·斯潘尼尔",born:1906,died:1967,country:"美国",role:"短号",bio:"迪克西兰复兴的代表短号手，以简练有力、布鲁斯味十足的弱音器演奏著称，1939 年的录音被奉为经典。"},
  "Muhal Richard Abrams":{zh:"穆哈尔·理查德·艾布拉姆斯",born:1930,died:2017,country:"美国",role:"钢琴 · 作曲",bio:"AACM 的创始人与精神领袖，培养了整整一代芝加哥前卫乐手，作曲横跨大乐队、室内乐与自由即兴。"},
  "Mulgrew Miller":{zh:"马尔格鲁·米勒",born:1955,died:2013,country:"美国",role:"钢琴",bio:"承袭鲍威尔、加兰传统又自成一格的硬波普钢琴大师，触键饱满、律动深厚，是 1980 年代以来最受敬重的伴奏者与教师。"},
  "Nat Adderley":{zh:"纳特·阿德利",born:1931,died:2000,country:"美国",role:"短号",bio:"加农炮·阿德利之弟，乐队的短号手与作曲者，写下灵魂爵士名曲《Work Song》，音色明亮、布鲁斯味十足。"},
  "Neal Hefti":{zh:"尼尔·赫夫提",born:1922,died:2008,country:"美国",role:"编曲 · 作曲",bio:"为贝西乐队《Atomic》操刀的编曲大师，简洁有力的摇摆写作堪称典范，也作有《蝙蝠侠》电视主题曲。"},
  "Nightmares on Wax":{zh:"Nightmares on Wax",born:1970,country:"英国",role:"制作人 · DJ",bio:"乔治·埃夫林的化名，Warp 厂牌元老，把低保真嘻哈、雷鬼与灵魂熔成慵懒的‘沙发音乐’，《Carboot Soul》是下游电子经典。"},
  "Nils Petter Molvaer":{zh:"尼尔斯·彼得·莫尔瓦尔",born:1960,country:"挪威",role:"小号 · 制作",bio:"挪威小号手，《Khmer》把 ECM 式的空灵小号与电子节拍、环境声景融合，开创了‘未来爵士’的北欧声音。"},
  "Norah Jones":{zh:"诺拉·琼斯",born:1979,country:"美国",role:"演唱 · 钢琴",bio:"以《Come Away with Me》横扫格莱美的歌手钢琴家（拉维·香卡之女），把爵士、乡村与流行融成温柔亲密的私语，全球热销。"},
  "Nucleus":{zh:"Nucleus（乐队）",life:"活跃 1969 起",country:"英国",role:"融合爵士乐队",bio:"小号手伊恩·卡尔领衔的英国融合先驱，《Elastic Rock》早于多数美国同行，是欧陆爵士摇滚的奠基之作。"},
  "Old and New Dreams":{zh:"新旧梦（乐队）",life:"活跃 1976–1987",country:"美国",role:"自由爵士四重奏",bio:"由科尔曼旧部切利、雷德曼、海登、布莱克韦尔组成的四重奏，延续并致敬奥奈特·科尔曼的‘和声旋律’精神。"},
  "Oliver Nelson":{zh:"奥利弗·纳尔逊",born:1932,died:1975,country:"美国",role:"萨克斯 · 编曲 · 作曲",bio:"杰出的编曲大师，《The Blues and the Abstract Truth》中的《Stolen Moments》成为标准曲，后转战好莱坞配乐。"},
  "Original Dixieland Jass Band":{zh:"正宗迪克西兰爵士乐队",life:"活跃 1916–1925",country:"美国",role:"早期爵士乐队",bio:"1917 年录下史上第一张爵士唱片的白人五人组，把新奥尔良的声音推向全国，引发了第一波爵士热潮（尽管争议不断）。"},
  "Oscar Peterson":{zh:"奥斯卡·彼得森",born:1925,died:2007,country:"加拿大",role:"钢琴",bio:"技术华丽到令人瞠目的钢琴巨匠，融合摇摆的律动与比波普的速度，其三重奏录音是爵士钢琴的炫技标杆。"},
  "Oscar Pettiford":{zh:"奥斯卡·佩蒂福德",born:1922,died:1960,country:"美国",role:"贝斯 · 大提琴",bio:"布莱克福特之后最重要的比波普贝斯手，把贝斯独奏推向新高度，还开创性地用大提琴演奏爵士。"},
  "Out of the Blue":{zh:"Out of the Blue（乐队）",life:"活跃 1984–1988",country:"美国",role:"硬波普乐队",bio:"Blue Note 在 1980 年代力推的青年六重奏（简称 OTB），是新古典浪潮里培养新星的摇篮之一。"},
  "Paquito D'Rivera":{zh:"帕奎托·德里维拉",born:1948,country:"古巴",role:"中音萨克斯 · 单簧管",bio:"伊拉克雷的创始成员，叛逃美国后成为拉丁爵士与古典跨界的多产巨匠，把比波普与古巴节奏熔于一炉，屡获格莱美。"},
  "Passport":{zh:"Passport（乐队）",life:"活跃 1971 起",country:"德国",role:"融合爵士乐队",bio:"萨克斯手克劳斯·杜尔丁格领衔的德国融合名团，旋律明快、欧陆气质鲜明，是欧洲爵士摇滚的常青代表。"},
  "Patrice Rushen":{zh:"帕特里斯·拉申",born:1954,country:"美国",role:"键盘",bio:"从前卫爵士起步、后转向放克与节奏布鲁斯的全才键盘手，《Forget Me Nots》是采样金曲，亦是格莱美音乐总监。"},
  "Paul Desmond":{zh:"保罗·德斯蒙德",born:1924,died:1977,country:"美国",role:"中音萨克斯",bio:"布鲁贝克四重奏的中音萨克斯，自称音色‘像干马提尼’，写下史上最畅销的爵士单曲《Take Five》，乐句轻盈机智。"},
  "Paul Whiteman":{zh:"保罗·怀特曼",born:1890,died:1967,country:"美国",role:"乐队领袖",bio:"1920 年代被冠以（争议性的）‘爵士之王’的乐队领袖，把爵士包装得交响化、商业化，并委约首演了《蓝色狂想曲》。"},
  "Pee Wee Russell":{zh:"皮·维·拉塞尔",born:1906,died:1969,country:"美国",role:"单簧管",bio:"风格古怪独特的单簧管手，音色沙哑、乐句出人意料，从迪克西兰一路演到前卫，是爵士史上的‘异类奇才’。"},
  "Pepper Adams":{zh:"佩珀·亚当斯",born:1930,died:1986,country:"美国",role:"上低音萨克斯",bio:"硬波普上低音萨克斯的代表，绰号‘手术刀’，音色粗粝、乐句凌厉，长期与唐纳德·伯德合作。"},
  "Perez Prado":{zh:"佩雷斯·普拉多",born:1916,died:1989,country:"古巴",role:"乐队领袖 · 编曲",bio:"‘曼波之王’，把曼波节奏推向全球流行的古巴乐队领袖，《Cherry Pink》《Mambo No. 5》风靡世界。"},
  "Pete Jolly":{zh:"皮特·乔利",born:1932,died:2004,country:"美国",role:"钢琴 · 手风琴",bio:"西海岸的钢琴名家，触键轻快灵动，活跃于爵士与好莱坞录音，是加州录音室场景的常客。"},
  "Pete Rugolo":{zh:"皮特·鲁戈洛",born:1915,died:2011,country:"美国",role:"编曲 · 作曲",bio:"肯顿乐队的招牌编曲家，‘前卫爵士’（progressive jazz）的设计师，后成为多产的电视电影配乐作家。"},
  "Peter Brotzmann":{zh:"彼得·布罗茨曼",born:1941,died:2023,country:"德国",role:"萨克斯",bio:"欧洲自由爵士最暴烈的呐喊者，《Machine Gun》以排山倒海的能量成为欧陆自由即兴的奠基炸弹。"},
  "Poncho Sanchez":{zh:"潘乔·桑切斯",born:1951,country:"美国",role:"康加鼓 · 乐队领袖",bio:"师承卡尔·杰德的拉丁爵士康加鼓大师，把萨尔萨、灵魂与硬波普熔成热力四射的舞曲，屡获格莱美。"},
  "Portico Quartet":{zh:"Portico Quartet（乐队）",life:"活跃 2005 起",country:"英国",role:"环境爵士四重奏",bio:"以钢片琴‘hang’营造空灵音色的伦敦四重奏，把极简、电子与爵士融成静谧的当代声景。"},
  "Preservation Hall Jazz Band":{zh:"保护厅爵士乐队",life:"活跃 1961 起",country:"美国",role:"传统爵士乐队",bio:"驻守新奥尔良‘保护厅’的传统爵士守护者，几代乐手薪火相传，把最古老的集体即兴一直延续到今天。"},
  "Pucho":{zh:"普乔",born:1938,country:"美国",role:"定音鼓 · 乐队领袖",wiki:"Pucho (musician)",bio:"‘拉丁灵魂兄弟’乐队领袖，把afro-cuban、布加洛与灵魂爵士混搭，律动火爆，是采样文化钟爱的源头。"},
  "Quantic":{zh:"Quantic",born:1980,country:"英国",role:"制作人 · 多乐器",wiki:"Quantic (musician)",bio:"威尔·霍兰德的化名，深耕哥伦比亚与拉美音乐的英国制作人，把昆比亚、灵魂与爵士采样融成温暖的世界电子。"},
  "Ralph Peterson":{zh:"拉尔夫·彼得森",born:1962,died:2021,country:"美国",role:"鼓",bio:"师承阿特·布雷基的硬波普鼓手，能量爆裂、推进力惊人，作为乐队领袖延续了爵士信使的薪火。"},
  "Ray Brown":{zh:"雷·布朗",born:1926,died:2002,country:"美国",role:"贝斯",bio:"史上最伟大的行走低音大师之一，音色饱满、律动如磐石，长期坐镇奥斯卡·彼得森三重奏，是无数经典的节奏基石。"},
  "Red Nichols":{zh:"瑞德·尼科尔斯",born:1905,died:1965,country:"美国",role:"短号",bio:"1920 年代多产的白人短号手，乐队‘五分镍币’录音量惊人，是早期爵士商业化的活跃推手。"},
  "Red Rodney":{zh:"瑞德·罗德尼",born:1927,died:1994,country:"美国",role:"小号",bio:"帕克五重奏中唯一的白人小号手（艺名‘Albino Red’随团演出），晚年复出焕发第二春，是比波普的忠实传人。"},
  "Rex Stewart":{zh:"雷克斯·斯图尔特",born:1907,died:1967,country:"美国",role:"短号",bio:"艾灵顿乐队的短号手，以‘半按键’制造的独特人声化音色著称，《Boy Meets Horn》是其招牌。"},
  "Richie Kamuca":{zh:"里奇·卡穆卡",born:1930,died:1977,country:"美国",role:"次中音萨克斯",bio:"莱斯特·扬一脉的冷爵士次中音，音色温柔流畅，活跃于西海岸乐队与录音室，四十六岁因癌症早逝。"},
  "Roscoe Mitchell":{zh:"罗斯科·米切尔",born:1940,country:"美国",role:"萨克斯 · 作曲",bio:"芝加哥艺术合奏团的核心，AACM 元老，《Sound》开创了以静默与音色为主角的前卫美学，是当代即兴的思想家。"},
  "Roy Ayers Ubiquity":{zh:"罗伊·艾尔斯与 Ubiquity",life:"活跃 1970s",country:"美国",role:"爵士放克／颤音琴",bio:"颤音琴手罗伊·艾尔斯领衔的爵士放克乐队，《Everybody Loves the Sunshine》慵懒迷人，是 neo-soul 与嘻哈采样的圣典。"},
  "Roy Eldridge":{zh:"罗伊·埃尔德里奇",born:1911,died:1989,country:"美国",role:"小号",bio:"连接阿姆斯特朗与吉莱斯皮的‘失落环节’，绰号‘Little Jazz’，以炽热的高音与火力推动了摇摆向比波普的过渡。"},
  "Roy Hargrove's Crisol":{zh:"哈格罗夫的 Crisol 乐队",life:"录于 1997",country:"美国",role:"afro-cuban 爵士",bio:"小号手罗伊·哈格罗夫的拉丁项目，《Habana》集结古美两地名家，把硬波普与afro-cuban节奏熔铸，获格莱美。"},
  "Ruby Braff":{zh:"鲁比·布拉夫",born:1927,died:2003,country:"美国",role:"短号",bio:"逆潮流坚守摇摆传统的短号大师，音色温暖抒情，在比波普盛行的年代里把主流摇摆延续得优雅动人。"},
  "Russ Freeman":{zh:"拉斯·弗里曼",born:1926,died:2002,country:"美国",role:"钢琴",bio:"切特·贝克乐队的钢琴搭档，西海岸冷爵士的可靠键盘手与作曲者，伴奏机敏、律动轻盈。"},
  "Sabu Martinez":{zh:"萨布·马丁内斯",born:1930,died:1979,country:"美国",role:"康加鼓",bio:"波多黎各裔的非洲–古巴打击乐手，《Palo Congo》把古巴宗教节奏原汁原味地带入唱片，狂野而虔诚。"},
  "Sade":{zh:"莎黛",born:1959,country:"英国",role:"演唱",wiki:"Sade (singer)",bio:"莎黛·阿杜领衔的同名乐队，以冷静克制、爵士化的灵魂声音风靡全球，《Diamond Life》定义了一种优雅的‘成人’都市情调。"},
  "Scott Hamilton":{zh:"斯科特·汉密尔顿",born:1954,country:"美国",role:"次中音萨克斯",bio:"在融合当道的 1970 年代逆流而上、复兴霍金斯／韦伯斯特式摇摆次中音的年轻人，音色醇厚、抒情大方。"},
  "Serge Chaloff":{zh:"塞尔吉·查洛夫",born:1923,died:1957,country:"美国",role:"上低音萨克斯",bio:"伍迪·赫尔曼‘四兄弟’之一，比波普上低音萨克斯的奠基者，《Blue Serge》抒情深沉，三十三岁因瘫痪早逝。"},
  "Shabaka and the Ancestors":{zh:"沙巴卡与祖先们",life:"活跃 2016 起",country:"英国／南非",role:"精神爵士乐队",bio:"萨克斯手沙巴卡·哈钦斯与南非乐手组成的乐队，把约翰内斯堡的灵性与伦敦的能量熔铸成炽热宽广的精神爵士。"},
  "Shai Maestro":{zh:"沙伊·马埃斯特罗",born:1987,country:"以色列",role:"钢琴 · 作曲",bio:"以色列钢琴家，阿维沙伊·科恩三重奏出身，触键诗意、动态细腻，是 ECM 麾下当代三重奏的重要声音。"},
  "Shakti":{zh:"Shakti（乐队）",life:"活跃 1973 起",country:"英国／印度",role:"印度融合乐队",bio:"约翰·麦克劳克林与印度大师（小提琴 L.Shankar、塔布拉 Zakir Hussain）组成的原声乐队，把印度古典与爵士即兴深度融合。"},
  "Shelly Manne":{zh:"谢利·曼恩",born:1920,died:1984,country:"美国",role:"鼓 · 乐队领袖",bio:"西海岸冷爵士最具旋律感的鼓手，敏感细腻、善于‘对话’，也参与了大量好莱坞配乐与录音。"},
  "Shelly Manne & André Previn":{zh:"曼恩与普列文",life:"录于 1956",country:"美国",role:"冷爵士合作",bio:"鼓手曼恩与钢琴家普列文用爵士三重奏改编音乐剧《窈窕淑女》，《My Fair Lady》意外成为畅销爵士唱片。"},
  "Shirley Scott":{zh:"雪莉·斯科特",born:1934,died:2002,country:"美国",role:"哈蒙德风琴",bio:"绰号‘风琴女王’，触键优雅、布鲁斯味醇厚的灵魂爵士风琴手，常与次中音萨克斯（含丈夫特伦廷）搭档。"},
  "Sister Rosetta Tharpe":{zh:"罗塞塔·萨普修女",born:1915,died:1973,country:"美国",role:"演唱 · 吉他",bio:"福音摇摆的先驱，以失真电吉他与炽热演唱预告了摇滚乐的到来，被誉为‘摇滚教母’，影响了无数后辈。"},
  "Slim Gaillard":{zh:"斯利姆·盖拉德",born:1916,died:1991,country:"美国",role:"演唱 · 吉他 · 钢琴",bio:"自创‘Vout’胡言乱语的喜剧爵士艺人，以滑稽的拟声与即兴段子风靡一时，被克鲁亚克写进《在路上》。"},
  "Soft Machine":{zh:"软机器（乐队）",life:"活跃 1966 起",country:"英国",role:"坎特伯雷融合乐队",bio:"英国‘坎特伯雷之声’的旗舰，从迷幻摇滚一路演化为复杂的器乐融合爵士，《Third》是英伦爵士摇滚的里程碑。"},
  "Sonny Criss":{zh:"桑尼·克里斯",born:1927,died:1977,country:"美国",role:"中音萨克斯",bio:"帕克一脉的洛杉矶中音萨克斯手，音色明亮、乐句炽烈而抒情，是西海岸被低估的比波普声音。"},
  "Sonny Red":{zh:"桑尼·瑞德",born:1932,died:1981,country:"美国",role:"中音萨克斯",bio:"底特律出身的硬波普中音萨克斯手，音色干净、乐句利落，在 Blue Note 与 Jazzland 留下扎实的录音。"},
  "Sonny Sharrock":{zh:"桑尼·沙罗克",born:1940,died:1994,country:"美国",role:"吉他",bio:"自由爵士吉他的暴烈先知，以滑棒与噪音把吉他推向撕裂的极限，晚年凭《Ask the Ages》迎来迟到的认可。"},
  "Soulive":{zh:"Soulive（乐队）",life:"活跃 1999 起",country:"美国",role:"灵魂爵士三重奏",bio:"风琴／吉他／鼓三重奏，把放克、灵魂爵士与嘻哈律动结合，是 2000 年代 jam／酸爵士场景的人气乐队。"},
  "Stan Getz & Charlie Byrd":{zh:"盖茨与查理·伯德",life:"录于 1962",country:"美国",role:"波萨诺瓦合作",bio:"萨克斯手盖茨与吉他手伯德的《Jazz Samba》是把巴西波萨诺瓦引爆北美的开山之作，《Desafinado》登上流行榜。"},
  "Stan Kenton":{zh:"斯坦·肯顿",born:1911,died:1979,country:"美国",role:"钢琴 · 大乐队领袖",bio:"‘前卫爵士’的雄心家，以庞大编制、铜管的厚墙与交响化野心著称，既被推崇又具争议，培养了大批西海岸乐手。"},
  "Stephen Scott":{zh:"斯蒂芬·斯科特",born:1969,country:"美国",role:"钢琴",bio:"1990 年代新生代硬波普钢琴家，曾效力贝蒂·卡特与桑尼·罗林斯，触键扎实、和声丰富。"},
  "Steps Ahead":{zh:"Steps Ahead（乐队）",life:"活跃 1979 起",country:"美国",role:"融合爵士乐队",bio:"颤音琴手麦克·梅尼里与萨克斯手迈克尔·布雷克领衔的超级乐队，从原声后波普走向电气融合，技术华丽。"},
  "Steve Coleman":{zh:"史蒂夫·科尔曼",born:1956,country:"美国",role:"中音萨克斯 · 作曲",bio:"M-Base 运动的理论核心，以复杂的循环节奏与几何化结构重塑了后波普，深刻影响了当代爵士的节奏思维。"},
  "Stuff":{zh:"Stuff（乐队）",life:"活跃 1976 起",country:"美国",role:"放克／录音室乐队",bio:"由纽约顶尖录音室乐手组成的爵士放克乐队，律动滑顺扎实，是 1970 年代节奏组的标杆。"},
  "Stuff Smith":{zh:"斯塔夫·史密斯",born:1909,died:1967,country:"美国",role:"小提琴",bio:"摇摆爵士最粗犷有力的小提琴手，最早使用电扩音的弦乐手之一，乐句炽烈、不拘一格。"},
  "Sunny Murray":{zh:"桑尼·默里",born:1936,died:2017,country:"美国",role:"鼓",bio:"自由爵士打击乐的奠基者之一，与塞西尔·泰勒、艾勒合作，彻底打破固定节拍，让鼓成为连绵的能量之流。"},
  "Sy Oliver":{zh:"赛·奥利弗",born:1910,died:1988,country:"美国",role:"编曲 · 小号",bio:"为吉米·伦斯福德与汤米·多西操刀的摇摆编曲名家，‘two-beat’的律动设计让乐队既精致又好跳舞。"},
  "Tadd Dameron":{zh:"塔德·达梅隆",born:1917,died:1965,country:"美国",role:"作曲 · 编曲 · 钢琴",bio:"比波普最重要的作曲家，写下《Hot House》《Good Bait》《If You Could See Me Now》，为这场革命提供了最优美的旋律。"},
  "Teddy Charles":{zh:"特迪·查尔斯",born:1928,died:2012,country:"美国",role:"颤音琴 · 作曲",bio:"勇于实验的颤音琴手与作曲家，1950 年代便探索无调性与现代古典手法，是‘第三流派’的先行者之一。"},
  "Teo Macero":{zh:"特奥·马塞罗",born:1925,died:2008,country:"美国",role:"制作 · 萨克斯",bio:"迈尔斯多张里程碑（含《Bitches Brew》）的制作人，以剪辑磁带重塑录音的开创者，是录音室作为乐器的先驱。"},
  "Terrace Martin":{zh:"特勒斯·马丁",born:1978,country:"美国",role:"萨克斯 · 制作",bio:"洛杉矶的多面手，连接爵士、新灵魂与嘻哈，深度参与肯德里克·拉马尔《To Pimp a Butterfly》的制作。"},
  "The Blackbyrds":{zh:"The Blackbyrds（乐队）",life:"活跃 1973 起",country:"美国",role:"爵士放克乐队",bio:"由唐纳德·伯德的学生组成的爵士放克乐队，《Walking in Rhythm》律动甜美，是采样文化的常青源头。"},
  "The Brand New Heavies":{zh:"The Brand New Heavies（乐队）",life:"活跃 1985 起",country:"英国",role:"酸爵士／放克乐队",bio:"英国酸爵士运动的旗舰乐队，以扎实的现场放克律动与灵魂女声把‘acid jazz’推向商业成功。"},
  "The Brecker Brothers":{zh:"布雷克兄弟（乐队）",life:"活跃 1975 起",country:"美国",role:"爵士放克乐队",bio:"萨克斯手迈克尔与小号手兰迪·布雷克兄弟的乐队，把硬朗的放克与高难即兴结合，是融合爵士最炫技的组合之一。"},
  "The Comet Is Coming":{zh:"The Comet Is Coming（乐队）",life:"活跃 2013 起",country:"英国",role:"爵士电子三重奏",bio:"萨克斯手沙巴卡·哈钦斯参与的三重奏，把萨克斯、合成器与鼓融成宇宙感的迷幻爵士电子，能量爆裂。"},
  "The Crusaders":{zh:"The Crusaders（乐队）",life:"活跃 1961 起",country:"美国",role:"爵士放克乐队",bio:"从硬波普‘Jazz Crusaders’演化而来的爵士放克名团，《Street Life》大获成功，把灵魂爵士带上流行榜。"},
  "The Greyboy Allstars":{zh:"The Greyboy Allstars（乐队）",life:"活跃 1993 起",country:"美国",role:"酸爵士／放克乐队",bio:"圣迭戈的爵士放克乐队，复兴布加洛与灵魂爵士的现场律动，是美国 jam／酸爵士场景的代表。"},
  "The Quintet":{zh:"五重奏（梅西音乐厅）",life:"录于 1953",country:"美国",role:"比波普全明星",bio:"帕克、吉莱斯皮、鲍威尔、明格斯、罗奇在多伦多梅西音乐厅的传奇同台，被誉为‘史上最伟大的爵士音乐会’。"},
  "The Roots":{zh:"The Roots（乐队）",life:"活跃 1987 起",country:"美国",role:"嘻哈乐队",bio:"以真乐器现场演奏著称的嘻哈乐队，把爵士、灵魂与说唱深度融合，《Things Fall Apart》是新灵魂时代的杰作。"},
  "Theon Cross":{zh:"西恩·克罗斯",born:1992,country:"英国",role:"大号",bio:"把大号（tuba）变成低音主奏的伦敦新爵士革新者，Sons of Kemet 成员，《Fyah》律动澎湃、根植加勒比。"},
  "Thievery Corporation":{zh:"Thievery Corporation（乐队）",life:"活跃 1995 起",country:"美国",role:"下游电子二人组",bio:"华盛顿特区二人组，把巴西、印度、雷鬼与爵士采样缝成慵懒世界电子，是‘chill-out’与 nu-jazz 的代表。"},
  "Thundercat":{zh:"雷猫",born:1984,country:"美国",role:"电贝斯 · 演唱",wiki:"Thundercat (musician)",bio:"师承雅科血脉的洛杉矶贝斯怪杰，把融合爵士的繁复、放克与新灵魂熔成迷幻私语，深度参与拉马尔等人的创作。"},
  "Tigran Hamasyan":{zh:"蒂格兰·哈玛西扬",born:1987,country:"亚美尼亚",role:"钢琴 · 作曲",bio:"亚美尼亚钢琴奇才，把祖国的民谣旋律与前卫金属的力量、复杂节拍融入爵士，自成一种炽烈而神秘的语言。"},
  "Tito Rodriguez":{zh:"蒂托·罗德里格斯",born:1923,died:1973,country:"美国",role:"演唱 · 定音鼓",bio:"与普恩特齐名的‘曼波三巨头’之一，波多黎各裔的歌手与乐队领袖，嗓音优雅、节奏炽热，纽约曼波黄金期的台柱。"},
  "Tom Misch":{zh:"汤姆·米施",born:1995,country:"英国",role:"吉他 · 制作 · 演唱",bio:"伦敦的吉他手兼制作人，把低保真嘻哈节拍、放克吉他与新灵魂熔成阳光慵懒的都市之声，深受新生代喜爱。"},
  "Tom Scott":{zh:"汤姆·斯科特",born:1948,country:"美国",role:"萨克斯",bio:"洛杉矶顶级录音室萨克斯手，乐队 L.A. Express 是爵士放克标杆，也为无数流行唱片与影视配乐吹奏。"},
  "Tom Turpin":{zh:"汤姆·特平",born:1873,died:1922,country:"美国",role:"作曲 · 钢琴",bio:"圣路易斯的拉格泰姆先驱，《Harlem Rag》是首批由非裔作曲家出版的拉格泰姆之一，比乔普林的成名更早。"},
  "Tommy Dorsey":{zh:"汤米·多西",born:1905,died:1956,country:"美国",role:"长号 · 大乐队领袖",bio:"绰号‘摇摆界的多情绅士’，以丝滑绵长的长号气息著称，其乐队是青年辛纳屈成名的舞台。"},
  "Tommy Flanagan":{zh:"汤米·弗拉纳根",born:1930,died:2001,country:"美国",role:"钢琴",bio:"品味无瑕的伴奏与独奏钢琴家，参与了《Giant Steps》《Saxophone Colossus》等里程碑，长期是埃拉·菲茨杰拉德的音乐总监。"},
  "Tony Bennett":{zh:"托尼·班尼特",born:1926,died:2023,country:"美国",role:"演唱",bio:"美国歌本最忠实的守护者之一，以温暖真挚的演唱跨越半个多世纪，晚年与 Lady Gaga 合作焕发第二春，深受同行敬重。"},
  "Tony Scott":{zh:"托尼·斯科特",born:1921,died:2007,country:"美国",role:"单簧管",bio:"技艺出众的比波普单簧管手，后游历东方、把禅与印度音乐融入即兴，《Music for Zen Meditation》是世界融合的先声。"},
  "Tony Williams Lifetime":{zh:"托尼·威廉姆斯的 Lifetime（乐队）",life:"活跃 1969 起",country:"美国",role:"融合爵士乐队",bio:"鼓手托尼·威廉姆斯创立的电气三重奏（麦克劳克林、拉里·扬在列），《Emergency!》是最早、最狂野的融合爵士宣言之一。"},
  "Tosca":{zh:"Tosca（乐队）",life:"活跃 1994 起",country:"奥地利",role:"下游电子二人组",bio:"维也纳的理查德·多夫迈斯特与鲁伯特·胡贝尔二人组，以慵懒的 downtempo 与爵士、dub 采样营造迷离夜色。"},
  "Truby Trio":{zh:"Truby Trio（乐队）",life:"活跃 1997 起",country:"德国",role:"Nu-Jazz 制作组",bio:"德国 Compost 厂牌的制作组，把broken beat、桑巴与浩室爵士融合，是欧陆 nu-jazz 舞池的代表。"},
  "Turk Murphy":{zh:"特克·墨菲",born:1915,died:1987,country:"美国",role:"长号 · 乐队领袖",bio:"旧金山迪克西兰复兴的旗手，长期驻演传统爵士，把新奥尔良的集体即兴一直延续到 1980 年代。"},
  "UK":{zh:"UK（乐队）",life:"活跃 1977–1980",country:"英国",role:"前卫融合乐队",bio:"由布鲁福德、霍兹沃思等名家组成的英国前卫融合超级乐队，把前卫摇滚的复杂与融合爵士的技术结合，影响深远。"},
  "United Future Organization":{zh:"United Future Organization（乐队）",life:"活跃 1990 起",country:"日本",role:"酸爵士／DJ 组合",bio:"日本三人 DJ／制作组合，是 1990 年代俱乐部爵士的国际代表，把波萨诺瓦、放克与拼贴美学融为时髦的酸爵士。"},
  "Us3":{zh:"Us3（乐队）",life:"活跃 1992 起",country:"英国",role:"爵士说唱组合",bio:"获 Blue Note 授权采样其经典曲库的英国组合，《Cantaloop》把汉考克的《Cantaloupe Island》变成嘻哈热单。"},
  "V.S.O.P.":{zh:"V.S.O.P.（乐队）",life:"活跃 1976 起",country:"美国",role:"原声后波普乐队",bio:"赫比·汉考克召集迈尔斯第二伟大五重奏旧部（以哈伯德替小号）的重聚乐队，是 1970 年代原声爵士复兴的标志。"},
  "Vic Dickenson":{zh:"维克·迪肯森",born:1906,died:1984,country:"美国",role:"长号",bio:"以幽默诙谐的滑奏与‘说话式’乐句著称的摇摆长号手，是主流摇摆即兴的可爱代表。"},
  "Wallace Roney":{zh:"华莱士·罗尼",born:1960,died:2020,country:"美国",role:"小号",bio:"迈尔斯亲自指点的唯一‘传人’，音色与气质深得其神髓，是新古典浪潮的重要小号手，因新冠离世。"},
  "Walter Bishop Jr.":{zh:"沃尔特·毕晓普",born:1927,died:1998,country:"美国",role:"钢琴",bio:"帕克五重奏的钢琴手，扎实流畅的比波普伴奏者，《Speak Low》展现了他作为领班的优雅一面。"},
  "Walter Wanderley":{zh:"沃尔特·万德利",born:1932,died:1986,country:"巴西",role:"哈蒙德风琴",bio:"巴西风琴手，《Rain Forest》中的《Summer Samba》以轻快的风琴波萨诺瓦风靡北美，是‘鸡尾酒爵士’的代表。"},
  "Warren Vache":{zh:"沃伦·瓦谢",born:1951,country:"美国",role:"短号",bio:"与斯科特·汉密尔顿并肩复兴主流摇摆的年轻短号手，音色温暖抒情，证明了传统语言在当代依然鲜活。"},
  "Washboard Rhythm Kings":{zh:"搓衣板节奏王（乐队）",life:"活跃 1931–1935",country:"美国",role:"早期爵士乐队",bio:"以搓衣板打击乐为特色的早期爵士／杂耍乐队，活泼诙谐，是大萧条年代廉价娱乐的鲜活记录。"},
  "Weldon Irvine":{zh:"韦尔登·欧文",born:1943,died:2002,country:"美国",role:"键盘 · 作曲",bio:"精神／放克爵士的键盘手与作曲家，写下《Young, Gifted and Black》，其放克律动后来成为嘻哈采样的富矿。"},
  "Wild Bill Davison":{zh:"狂野比尔·戴维森",born:1906,died:1989,country:"美国",role:"短号",bio:"迪克西兰复兴的炽烈短号手，演奏热情奔放、富戏剧张力，是 Commodore 厂牌经典录音的台柱。"},
  "Willie 'The Lion' Smith":{zh:"威利·'狮子'·史密斯",born:1893,died:1973,country:"美国",role:"钢琴",bio:"哈莱姆跨步钢琴的三巨头之一，性格张扬、戴礼帽叼雪茄，触键华丽而抒情，深深影响了艾灵顿。"},
  "Willie Bobo":{zh:"威利·博博",born:1934,died:1983,country:"美国",role:"定音鼓 · 邦戈鼓",bio:"波多黎各裔的拉丁爵士打击乐手，《Spanish Grease》把afro-cuban、布加洛与灵魂混搭，律动俏皮，是采样常客。"},
  "Woody Herman":{zh:"伍迪·赫尔曼",born:1913,died:1987,country:"美国",role:"单簧管 · 大乐队领袖",bio:"以一连串‘Herd’（牧群）乐队不断更新阵容的常青领班，从摇摆一路拥抱比波普与融合，培养了无数名家。"},
  "Woody Shaw":{zh:"伍迪·肖",born:1944,died:1989,country:"美国",role:"小号 · 作曲",bio:"后波普小号的最后一位重要革新者，以宽音程与调式思维拓展了小号语言，却在四十四岁因事故与失明早逝。"},
  "World Saxophone Quartet":{zh:"世界萨克斯四重奏",life:"活跃 1976 起",country:"美国",role:"无伴奏萨克斯四重奏",bio:"四把萨克斯无节奏组的革命性编制，把自由爵士、布鲁斯与放克编织成丰满的复调，海明菲尔、默里在列。"},
  "Wynton Kelly":{zh:"温顿·凯利",born:1931,died:1971,country:"美国",role:"钢琴",bio:"律动摇摆、触键明快的硬波普钢琴家，《Kind of Blue》中《Freddie Freeloader》一曲的钢琴即出自他手，是迈尔斯钟爱的伴奏者。"},
  "Yellowjackets":{zh:"Yellowjackets（乐队）",life:"活跃 1977 起",country:"美国",role:"融合爵士乐队",bio:"以紧密的编排与流畅旋律著称的当代融合长青乐队，多次斩获格莱美，是融合与流畅爵士之间的优雅一极。"},
  "Yussef Dayes":{zh:"优素福·达耶斯",born:1993,country:"英国",role:"鼓",bio:"伦敦新爵士的鼓手，律动深植非洲与加勒比节奏，从 Yussef Kamaal 到个人作品，是当下英伦最受瞩目的鼓手之一。"},
  "Yussef Kamaal":{zh:"Yussef Kamaal（二人组）",life:"活跃 2015–2017",country:"英国",role:"爵士／broken beat",bio:"鼓手优素福·达耶斯与键盘手卡马尔·威廉姆斯的二人组，《Black Focus》以原声 broken beat 点燃伦敦新爵士浪潮，虽短暂却影响深远。"}
};
