// 1001 Jazz — 曲库数据
// 合法原则：不存放音乐文件，只用平台搜索/跳转链接；封面用 CSS 程序化生成。
// 试听链接由 app.js 根据 artist + title 生成（Spotify / Apple Music / YouTube 搜索）。

window.ERAS = [
  { key: "ragtime",   name: "Ragtime / 前爵士",            years: "1890s–1910s", keywords: "切分节奏 · 钢琴 · 进行曲",
    desc: "爵士乐的源头。拉格泰姆把进行曲的左手节奏与切分的右手旋律结合，在钢琴上预演了后来摇摆的脉搏。它还不是即兴的音乐，却第一次让黑人音乐语言走进美国客厅。" },
  { key: "neworleans",name: "New Orleans / Dixieland",     years: "1910s–1920s", keywords: "集体即兴 · 铜管 · 热爵士",
    desc: "在新奥尔良的街头与酒馆里，铜管、单簧管与节奏组围成一圈集体即兴，爵士第一次成为‘一起说话’的音乐。路易斯·阿姆斯特朗在此把独奏推上历史舞台。" },
  { key: "swing",     name: "Swing / Big Band",            years: "1930s–1940s", keywords: "舞曲 · 大乐队 · 编曲",
    desc: "摇摆时代是爵士最流行的黄金期。大乐队、编曲与舞池让爵士成为全民流行乐，艾灵顿与贝西把黑人乐队的声音变成美国的声音。" },
  { key: "bebop",     name: "Bebop",                       years: "1940s–1950s", keywords: "高速 · 复杂和声 · 炫技",
    desc: "比波普把爵士从舞厅夺回到夜店与音乐家手中。小组合、极快的速度、复杂的和声替换，让爵士第一次明确成为‘听’的艺术而非‘跳’的伴奏。" },
  { key: "cool",      name: "Cool Jazz / West Coast",      years: "1950s",       keywords: "克制 · 清爽 · 室内乐感",
    desc: "对比波普的火热，冷爵士选择克制与编曲，吸收古典室内乐的质感。声音变轻、变慢、变得有空间，西海岸阳光下的爵士显得格外干净。" },
  { key: "hardbop",   name: "Hard Bop / Soul Jazz",        years: "1950s–1960s", keywords: "蓝调 · 福音 · 强律动",
    desc: "硬波普把蓝调、福音和 R&B 的体温带回比波普。强烈的律动、教堂式的呼应、城市黑人的生活经验，让这一支成为最‘好听’也最有根的爵士。" },
  { key: "modal",     name: "Modal Jazz",                  years: "1958–1960s",  keywords: "调式 · 少和弦 · 长线条",
    desc: "调式爵士不再围着快速变化的和弦转，而是把一两个调式拉长，给独奏更大的呼吸空间。《Kind of Blue》是它的圣经，也是史上最畅销的爵士唱片。" },
  { key: "free",      name: "Free Jazz / Avant-garde",     years: "1960s–1970s", keywords: "无固定和声 · 集体即兴 · 声音实验",
    desc: "自由爵士拆掉了和声与节拍的框架，把音乐还原为纯粹的声音与情绪。它常被误解为噪音，却是民权年代最激烈、最诚实的黑人艺术宣言。" },
  { key: "latin",     name: "Latin Jazz / Bossa Nova",     years: "1950s–1970s", keywords: "古巴 · 巴西 · 非洲节奏",
    desc: "当爵士遇上古巴的克拉维节奏与巴西的波萨诺瓦，便有了拉丁爵士。它把非洲的根重新接回美洲音乐，让摇摆多出一层热带的摆动。" },
  { key: "fusion",    name: "Fusion / Jazz-rock",          years: "1970s–1980s", keywords: "电声 · 摇滚 · 放克 · 合成器",
    desc: "融合爵士插上电:电钢、合成器、放克贝斯与摇滚鼓点。迈尔斯的《Bitches Brew》打开闸门，爵士与摇滚、放克在能量与音量上正面相遇。" },
  { key: "neobop",    name: "Neo-bop / Straight-ahead",    years: "1980s–1990s", keywords: "回归传统 · 学院化 · 现代硬波普",
    desc: "在融合与流行之后，温顿·马萨利斯一代回到原声、回到传统,把爵士史变成可以学习、演奏与传承的经典。学院化让爵士活了下来，也引发关于‘活力’的争论。" },
  { key: "acid",      name: "Acid / Nu / Smooth Jazz",     years: "1990s–2010s", keywords: "舞曲 · 电子 · R&B · 都市感",
    desc: "酸爵士与新爵士把采样、浩室、嘻哈和 R&B 接进爵士,让它重新出现在俱乐部与都市夜晚。Blue Note 的老唱片在这里被重新切片成新的节拍。" },
  { key: "newlondon", name: "New London / Global Revival", years: "2010s–2020s", keywords: "全球化 · 嘻哈 · 新灵性",
    desc: "新一代爵士在伦敦、洛杉矶与全球开花,接上嘻哈、非洲节奏与精神性追寻。卡马西、莎芭卡们让爵士重新成为年轻人、舞池与抗争的音乐。" }
];

// instruments(乐器) / moods(心情) 用中文标签，便于浏览筛选
window.SONGS = [
  // ── 1. Ragtime / 前爵士 ──────────────────────────────
  { id:"0001", title:"Maple Leaf Rag", artist:"Scott Joplin", composer:"Scott Joplin", year:1899, album:"Sheet Music / Stark", label:"Stark", era:"ragtime",
    genres:["ragtime","piano"], instruments:["钢琴"], moods:["工作","咖啡馆"],
    reason:"拉格泰姆的奠基之作，也是史上最畅销的钢琴乐谱之一。左手稳定的进行曲低音托着右手不断切分的旋律，那种‘踉跄却前进’的摆动，正是爵士节奏的胚胎。听它就是听爵士还没成形时的心跳。" },
  { id:"0002", title:"The Entertainer", artist:"Scott Joplin", composer:"Scott Joplin", year:1902, album:"Sheet Music / Stark", label:"Stark", era:"ragtime",
    genres:["ragtime","piano"], instruments:["钢琴"], moods:["咖啡馆","工作"],
    reason:"因电影《骗中骗》而家喻户晓的拉格泰姆名曲。明亮、俏皮、结构工整如一篇小品文。它证明黑人音乐语言早在爵士诞生前，就能写出让全世界记住的旋律。" },
  { id:"0003", title:"King Porter Stomp", artist:"Jelly Roll Morton", composer:"Jelly Roll Morton", year:1923, album:"Early Recordings", label:"Gennett", era:"ragtime",
    genres:["ragtime","early jazz","piano"], instruments:["钢琴"], moods:["兴奋"],
    reason:"莫顿自称‘爵士的发明者’，这首曲子横跨拉格泰姆与摇摆，后来被弗莱彻·亨德森改编成大乐队金曲。它是从独奏钢琴通往大乐队摇摆的一座桥。" },
  { id:"0004", title:"Castle House Rag", artist:"James Reese Europe", composer:"James Reese Europe", year:1914, album:"Society Orchestra", label:"Victor", era:"ragtime",
    genres:["ragtime","early jazz"], instruments:["小号","鼓"], moods:["兴奋"],
    reason:"在爵士唱片出现之前，黑人指挥詹姆斯·里斯·尤罗普已把切分节奏带进纽约上流舞厅。这段录音速度飞快、能量惊人，是‘前爵士’最接近爵士的一刻。" },
  { id:"0005", title:"Charleston Rag", artist:"Eubie Blake", composer:"Eubie Blake", year:1917, album:"Piano Rolls", label:"Ampico", era:"ragtime",
    genres:["ragtime","piano"], instruments:["钢琴"], moods:["咖啡馆"],
    reason:"尤比·布雷克活了一百岁，这首他二十岁前写下的曲子用了大胆的低音行进与半音和声。它让你听到拉格泰姆里其实藏着后来爵士钢琴的全部野心。" },

  // ── 2. New Orleans / Dixieland ───────────────────────
  { id:"0006", title:"West End Blues", artist:"Louis Armstrong", composer:"King Oliver", year:1928, album:"Hot Five & Hot Seven", label:"Okeh", era:"neworleans",
    genres:["early jazz","trumpet"], instruments:["小号","人声"], moods:["夜晚","孤独"],
    reason:"开篇那段无伴奏小号华彩，被公认为爵士独奏语言真正成熟的标志。阿姆斯特朗用十几秒证明:爵士可以是一个人的艺术。这是入门爵士史绕不开的第一块里程碑。" },
  { id:"0007", title:"Black Bottom Stomp", artist:"Jelly Roll Morton", composer:"Jelly Roll Morton", year:1926, album:"The Red Hot Peppers", label:"Victor", era:"neworleans",
    genres:["early jazz"], instruments:["钢琴","小号"], moods:["兴奋"],
    reason:"莫顿的红辣椒乐队把集体即兴写成了精密的编曲范本:独奏、合奏、停顿、呼应层层推进。它告诉你新奥尔良爵士并非乱奏，而是高度组织的热闹。" },
  { id:"0008", title:"Dipper Mouth Blues", artist:"King Oliver", composer:"King Oliver / Louis Armstrong", year:1923, album:"Creole Jazz Band", label:"Gennett", era:"neworleans",
    genres:["early jazz","blues"], instruments:["小号"], moods:["夜晚"],
    reason:"奥利弗的克里奥尔乐队是阿姆斯特朗的起点，这段加弱音器的短号独奏成了无数乐手模仿的范本。听它就是听爵士的师徒传承在唱片上第一次定格。" },
  { id:"0009", title:"Livery Stable Blues", artist:"Original Dixieland Jass Band", composer:"ODJB", year:1917, album:"First Jazz Record", label:"Victor", era:"neworleans",
    genres:["early jazz","dixieland"], instruments:["单簧管","小号"], moods:["兴奋"],
    reason:"史上第一张以‘Jass’命名发行的唱片。乐器模仿马嘶鸡叫，今天听来滑稽，却是爵士进入大众媒介的起点——也提醒我们历史的第一名常常并非最好的。" },
  { id:"0010", title:"Summertime", artist:"Sidney Bechet", composer:"George Gershwin", year:1939, album:"Sidney Bechet", label:"Blue Note", era:"neworleans",
    genres:["early jazz","ballad"], instruments:["萨克斯"], moods:["夜晚","孤独","雨天"],
    reason:"贝谢用高音萨克斯把格什温的摇篮曲吹得宽颤而炽热，这也是 Blue Note 厂牌最早的名作之一。新奥尔良的热情在这里慢了下来,化成挥之不去的乡愁。" },
  { id:"0011", title:"Singin' the Blues", artist:"Bix Beiderbecke", composer:"Robinson / Conrad", year:1927, album:"With Frankie Trumbauer", label:"Okeh", era:"neworleans",
    genres:["early jazz","cool"], instruments:["小号"], moods:["孤独","夜晚"],
    reason:"白人短号手比克斯吹出一种内敛、抒情、近乎忧郁的音色，与阿姆斯特朗的炽热相对。这段独奏预告了二十多年后‘冷爵士’的气质，是爵士抒情传统的源头之一。" },

  // ── 3. Swing / Big Band ──────────────────────────────
  { id:"0012", title:"Take the \"A\" Train", artist:"Duke Ellington", composer:"Billy Strayhorn", year:1941, album:"Ellington Orchestra", label:"Victor", era:"swing",
    genres:["swing","big band"], instruments:["钢琴","小号"], moods:["开车","兴奋"],
    reason:"艾灵顿乐队的招牌曲，写的是搭地铁去哈林。斯特雷霍恩的编曲明快优雅，是摇摆时代最完美的名片。想感受大乐队的光泽,从这趟 A 线列车上车准没错。" },
  { id:"0013", title:"One O'Clock Jump", artist:"Count Basie", composer:"Count Basie", year:1937, album:"Basie Orchestra", label:"Decca", era:"swing",
    genres:["swing","big band","blues"], instruments:["钢琴"], moods:["兴奋","开车"],
    reason:"贝西乐队的主题曲，建立在最朴素的蓝调上，靠节奏组的轻盈律动与铜管的层层堆叠点燃舞池。它示范了什么叫‘以少胜多’的摇摆——简单,却让人坐不住。" },
  { id:"0014", title:"Sing, Sing, Sing", artist:"Benny Goodman", composer:"Louis Prima", year:1937, album:"Carnegie Hall 1938", label:"Victor", era:"swing",
    genres:["swing","big band"], instruments:["单簧管","鼓"], moods:["兴奋"],
    reason:"古德曼乐队的狂欢，金·克鲁帕的部落式鼓点是早期最著名的鼓独奏。1938 年它把摇摆带进卡内基音乐厅,标志爵士第一次以‘高雅艺术’的身份登堂入室。" },
  { id:"0015", title:"In the Mood", artist:"Glenn Miller", composer:"Joe Garland", year:1939, album:"Glenn Miller Orchestra", label:"Bluebird", era:"swing",
    genres:["swing","big band"], instruments:["萨克斯"], moods:["开车","兴奋"],
    reason:"二战年代最家喻户晓的摇摆金曲，那段一问一答的萨克斯段落几乎人人会哼。它是摇摆作为‘全民流行乐’的极致代表,也是那个年代的集体记忆。" },
  { id:"0016", title:"It Don't Mean a Thing (If It Ain't Got That Swing)", artist:"Duke Ellington", composer:"Duke Ellington", year:1932, album:"Ellington Orchestra", label:"Brunswick", era:"swing",
    genres:["swing","big band","vocal"], instruments:["人声","钢琴"], moods:["兴奋"],
    reason:"标题本身就是一句宣言:没有摇摆,一切都没有意义。这首曲子在‘摇摆’成为一个时代名字之前就喊出了它。Ivie Anderson 的‘嘟哇’唱段是史上最早的著名拟声唱。" },
  { id:"0017", title:"A-Tisket, A-Tasket", artist:"Ella Fitzgerald", composer:"Ella Fitzgerald / Van Alexander", year:1938, album:"With Chick Webb", label:"Decca", era:"swing",
    genres:["swing","vocal"], instruments:["人声"], moods:["咖啡馆","兴奋"],
    reason:"二十一岁的艾拉用一首童谣一夜成名。轻盈、俏皮、咬字清亮如珠落玉盘,这首歌让你听到‘爵士第一夫人’最初的甜与灵。摇摆不只属于乐队,也属于歌声。" },

  // ── 4. Bebop ─────────────────────────────────────────
  { id:"0018", title:"Ko-Ko", artist:"Charlie Parker", composer:"Charlie Parker", year:1945, album:"Savoy Sessions", label:"Savoy", era:"bebop",
    genres:["bebop","alto sax"], instruments:["萨克斯"], moods:["兴奋","失眠"],
    reason:"比波普的爆炸宣言。帕克在飞快的速度上重组和声、抛出令人眩晕的乐句，宣告爵士进入炫技与个人表达的新纪元。第一次听可能跟不上,但这正是革命的声音。" },
  { id:"0019", title:"A Night in Tunisia", artist:"Dizzy Gillespie", composer:"Dizzy Gillespie", year:1946, album:"Dizzy Gillespie Sextet", label:"RCA Victor", era:"bebop",
    genres:["bebop","latin","trumpet"], instruments:["小号"], moods:["夜晚","兴奋"],
    reason:"吉莱斯皮把拉丁节奏写进比波普，那段著名的‘间奏华彩’是无数乐手的试金石。异国的鼓点加上高速的独奏,让比波普第一次有了画面感与色彩。" },
  { id:"0020", title:"Now's the Time", artist:"Charlie Parker", composer:"Charlie Parker", year:1945, album:"Savoy Sessions", label:"Savoy", era:"bebop",
    genres:["bebop","blues","alto sax"], instruments:["萨克斯"], moods:["工作"],
    reason:"帕克证明比波普并没离开蓝调的根——这是一首十二小节蓝调,旋律却被后来抄成了节奏布鲁斯热单。复杂与朴素在他手里从不矛盾。入门比波普的好起点。" },
  { id:"0021", title:"'Round Midnight", artist:"Thelonious Monk", composer:"Thelonious Monk", year:1947, album:"Genius of Modern Music", label:"Blue Note", era:"bebop",
    genres:["bebop","ballad","piano"], instruments:["钢琴"], moods:["夜晚","孤独","失眠"],
    reason:"史上被翻奏最多的爵士曲之一。蒙克古怪的和声与停顿，把午夜写成一种迷离又庄严的情绪。它孤僻、深邃,像一个人在深夜独自思考。爵士钢琴绕不开的名字。" },
  { id:"0022", title:"Un Poco Loco", artist:"Bud Powell", composer:"Bud Powell", year:1951, album:"The Amazing Bud Powell", label:"Blue Note", era:"bebop",
    genres:["bebop","latin","piano"], instruments:["钢琴"], moods:["兴奋","失眠"],
    reason:"波威尔是把帕克的语言搬上钢琴的人。这首带拉丁节奏的曲子紧张、灼热、近乎癫狂，被乐评人盛赞为爵士钢琴的顶峰之一。标题‘有点疯’,恰如其分。" },
  { id:"0023", title:"Ornithology", artist:"Charlie Parker", composer:"Charlie Parker / Benny Harris", year:1946, album:"Dial Sessions", label:"Dial", era:"bebop",
    genres:["bebop","alto sax"], instruments:["萨克斯"], moods:["工作","兴奋"],
    reason:"曲名玩的是帕克外号‘Bird(鸟)’的双关。它把流行曲《How High the Moon》的和声换上全新旋律——这种‘旧和声、新主题’的写法正是比波普的核心手艺。" },

  // ── 5. Cool Jazz / West Coast ────────────────────────
  { id:"0024", title:"Boplicity", artist:"Miles Davis", composer:"Miles Davis / Gil Evans", year:1949, album:"Birth of the Cool", label:"Capitol", era:"cool",
    genres:["cool","arranged"], instruments:["小号"], moods:["夜晚","阅读"],
    reason:"《冷爵士的诞生》里最优雅的一首。迈尔斯与编曲大师吉尔·埃文斯用九重奏写出柔和、缓慢、富层次的声响,正面回应比波普的火热。冷爵士的整套美学从这里起步。" },
  { id:"0025", title:"Take Five", artist:"Dave Brubeck", composer:"Paul Desmond", year:1959, album:"Time Out", label:"Columbia", era:"cool",
    genres:["cool","west coast"], instruments:["钢琴","萨克斯"], moods:["咖啡馆","工作","开车"],
    reason:"史上最畅销的爵士单曲之一,用罕见的 5/4 拍却轻盈得像散步。德斯蒙德的萨克斯干净如干马提尼。它证明实验性的节拍也能成为最受欢迎的旋律。必听入门曲。" },
  { id:"0026", title:"My Funny Valentine", artist:"Chet Baker", composer:"Richard Rodgers", year:1954, album:"Chet Baker Sings", label:"Pacific Jazz", era:"cool",
    genres:["cool","vocal","ballad"], instruments:["小号","人声"], moods:["夜晚","孤独","雨天"],
    reason:"贝克又吹又唱,声音脆弱、慵懒、略带破碎,是西海岸冷爵士最迷人的形象。这首情歌在他口中没有甜腻,只有一种欲言又止的伤感。深夜独处时的完美配乐。" },
  { id:"0027", title:"Bernie's Tune", artist:"Gerry Mulligan", composer:"Bernie Miller", year:1952, album:"Gerry Mulligan Quartet", label:"Pacific Jazz", era:"cool",
    genres:["cool","west coast"], instruments:["萨克斯","小号"], moods:["咖啡馆","开车"],
    reason:"马利根的无钢琴四重奏是冷爵士的标志性编制:重音琴只剩低音与鼓,让上低音萨克斯与小号像对话一样彼此缠绕。简约、透气,是西海岸阳光的声音。" },
  { id:"0028", title:"Moonlight in Vermont", artist:"Stan Getz", composer:"Suessdorf / Blackburn", year:1952, album:"Stan Getz Plays", label:"Clef", era:"cool",
    genres:["cool","ballad"], instruments:["萨克斯"], moods:["夜晚","阅读","孤独"],
    reason:"盖茨被称为‘The Sound(那个音色)’——温暖、圆润、丝绸般的次中音萨克斯。这首抒情曲是欣赏纯粹音色之美的最佳样本:几乎没有炫技,全是呼吸与歌唱。" },
  { id:"0029", title:"Django", artist:"Modern Jazz Quartet", composer:"John Lewis", year:1954, album:"Django", label:"Prestige", era:"cool",
    genres:["cool","chamber jazz"], instruments:["颤音琴","钢琴"], moods:["阅读","夜晚"],
    reason:"为吉他大师姜戈·莱因哈特写的挽歌。MJQ 把爵士装进室内乐的精致框架,颤音琴与钢琴对位如巴赫。它代表了冷爵士最知性、最古典化的那一面。" },

  // ── 6. Hard Bop / Soul Jazz ──────────────────────────
  { id:"0030", title:"Moanin'", artist:"Art Blakey & The Jazz Messengers", composer:"Bobby Timmons", year:1958, album:"Moanin'", label:"Blue Note", era:"hardbop",
    genres:["hard bop","soul jazz","gospel"], instruments:["鼓","钢琴"], moods:["兴奋","工作"],
    reason:"硬波普的招牌:开头那段一呼一应的旋律直接来自黑人教堂。布雷基的鼓像鞭子一样驱动全队。听这首,你会立刻明白硬波普为什么比比波普更‘好听’、更有体温。" },
  { id:"0031", title:"Song for My Father", artist:"Horace Silver", composer:"Horace Silver", year:1965, album:"Song for My Father", label:"Blue Note", era:"hardbop",
    genres:["hard bop","soul jazz","latin"], instruments:["钢琴"], moods:["咖啡馆","开车"],
    reason:"西尔弗献给葡裔父亲的曲子,带着波萨诺瓦的摇摆。那条贝斯线后来被 Steely Dan 直接借用。温暖、上口、律动迷人,是硬波普里最容易爱上的一首。" },
  { id:"0032", title:"Mercy, Mercy, Mercy", artist:"Cannonball Adderley", composer:"Joe Zawinul", year:1966, album:"Mercy, Mercy, Mercy!", label:"Capitol", era:"hardbop",
    genres:["soul jazz","gospel"], instruments:["萨克斯"], moods:["兴奋","咖啡馆"],
    reason:"现场录音里你能听到观众的喝彩。扎维努尔写的这条福音式旋律配上电钢,是‘灵魂爵士’打进流行榜的代表作。爵士在这里几乎变成了让人摇摆的福音乐。" },
  { id:"0033", title:"The Sidewinder", artist:"Lee Morgan", composer:"Lee Morgan", year:1964, album:"The Sidewinder", label:"Blue Note", era:"hardbop",
    genres:["hard bop","soul jazz","boogaloo"], instruments:["小号"], moods:["开车","兴奋"],
    reason:"摩根这条慵懒摇摆的‘布加洛’律动意外成了 Blue Note 的畅销冠军,救活了厂牌的财务。它好听到曾被用作汽车广告。硬波普如何变成流行,这就是答案。" },
  { id:"0034", title:"St. Thomas", artist:"Sonny Rollins", composer:"Sonny Rollins", year:1956, album:"Saxophone Colossus", label:"Prestige", era:"hardbop",
    genres:["hard bop","calypso"], instruments:["萨克斯"], moods:["开车","兴奋","咖啡馆"],
    reason:"罗林斯把加勒比的卡利普索童谣变成爵士经典,阳光、活泼、过耳难忘。它展示了他天马行空的即兴叙事能力:从一个简单旋律里能讲出整个故事。" },
  { id:"0035", title:"Watermelon Man", artist:"Herbie Hancock", composer:"Herbie Hancock", year:1962, album:"Takin' Off", label:"Blue Note", era:"hardbop",
    genres:["hard bop","soul jazz","funk"], instruments:["钢琴"], moods:["开车","兴奋"],
    reason:"汉考克二十二岁的处女作单曲,灵感来自他童年记忆里卖西瓜小贩的吆喝。蓝调与放克的律动让它大卖,也预告了这位巨匠日后从硬波普一路走向放克的轨迹。" },

  // ── 7. Modal Jazz ────────────────────────────────────
  { id:"0036", title:"So What", artist:"Miles Davis", composer:"Miles Davis", year:1959, album:"Kind of Blue", label:"Columbia", era:"modal",
    genres:["modal"], instruments:["小号","萨克斯"], moods:["夜晚","阅读","工作"],
    reason:"史上最畅销爵士唱片《Kind of Blue》的开场。它几乎只用两个调式,却给了独奏者前所未有的自由。冷静、辽阔、永不过时——如果只听一首爵士,很多人会选它。" },
  { id:"0037", title:"My Favorite Things", artist:"John Coltrane", composer:"Richard Rodgers", year:1961, album:"My Favorite Things", label:"Atlantic", era:"modal",
    genres:["modal","ballad"], instruments:["萨克斯"], moods:["夜晚","失眠","阅读"],
    reason:"科尔特兰把《音乐之声》里的圆舞曲变成长达十几分钟的调式冥想,高音萨克斯如念咒般盘旋。熟悉的旋律被拆解、重复、推向出神,是通往他后期精神之旅的入口。" },
  { id:"0038", title:"Flamenco Sketches", artist:"Miles Davis", composer:"Miles Davis / Bill Evans", year:1959, album:"Kind of Blue", label:"Columbia", era:"modal",
    genres:["modal","ballad"], instruments:["小号","钢琴"], moods:["夜晚","孤独","雨天"],
    reason:"《Kind of Blue》的收尾,五个调式像五个房间,每位独奏者自由停留。比尔·埃文斯的钢琴铺出印象派般的色彩。这是整张专辑最静、最美、最适合深夜独听的一刻。" },
  { id:"0039", title:"Acknowledgement (A Love Supreme Pt.1)", artist:"John Coltrane", composer:"John Coltrane", year:1965, album:"A Love Supreme", label:"Impulse!", era:"modal",
    genres:["modal","spiritual"], instruments:["萨克斯"], moods:["夜晚","孤独","失眠"],
    reason:"科尔特兰献给神的组曲开篇,那段四音动机最终化作人声反复吟唱‘A Love Supreme’。它把爵士提升为一种祈祷与朝圣,是‘精神爵士’的奠基之作,听来庄严而震撼。" },
  { id:"0040", title:"Peace Piece", artist:"Bill Evans", composer:"Bill Evans", year:1958, album:"Everybody Digs Bill Evans", label:"Riverside", era:"modal",
    genres:["modal","impressionist","piano"], instruments:["钢琴"], moods:["夜晚","阅读","雨天","失眠"],
    reason:"埃文斯在一个固定的左手和声上即兴漂浮,近乎德彪西的印象派钢琴。没有鼓、没有低音,只有纯粹的静谧。失眠或想安静下来时,这是最温柔的爵士。" },
  { id:"0041", title:"Passion Dance", artist:"McCoy Tyner", composer:"McCoy Tyner", year:1967, album:"The Real McCoy", label:"Blue Note", era:"modal",
    genres:["modal","piano"], instruments:["钢琴"], moods:["兴奋","工作"],
    reason:"泰纳是科尔特兰四重奏的钢琴手,这首曲子把调式爵士推向汹涌澎湃。他用四度叠置的厚重和弦敲出排山倒海的能量,是调式钢琴最有力量感的范本。" },

  // ── 8. Free Jazz / Avant-garde ───────────────────────
  { id:"0042", title:"Lonely Woman", artist:"Ornette Coleman", composer:"Ornette Coleman", year:1959, album:"The Shape of Jazz to Come", label:"Atlantic", era:"free",
    genres:["free jazz","ballad"], instruments:["萨克斯"], moods:["孤独","夜晚","雨天"],
    reason:"自由爵士的开篇,标题就是‘孤独的女人’。它抛开固定和声,却有一段哀恸到令人心碎的旋律。证明自由不等于混乱:科尔曼只是想让情感不被和弦束缚。入门自由爵士的最佳一首。" },
  { id:"0043", title:"Ghosts", artist:"Albert Ayler", composer:"Albert Ayler", year:1964, album:"Spiritual Unity", label:"ESP-Disk", era:"free",
    genres:["free jazz","spiritual"], instruments:["萨克斯"], moods:["孤独","失眠"],
    reason:"艾勒用近乎军号与圣歌的简单主题,再把它撕裂成嘶吼与泛音的风暴。天真的旋律与狂暴的音色并置,是自由爵士里最极端、也最动人的精神宣泄。" },
  { id:"0044", title:"Hat and Beard", artist:"Eric Dolphy", composer:"Eric Dolphy", year:1964, album:"Out to Lunch!", label:"Blue Note", era:"free",
    genres:["free jazz","avant-garde"], instruments:["单簧管","萨克斯"], moods:["失眠","工作"],
    reason:"献给蒙克的曲子(标题指他的帽子与胡子)。多尔菲用低音单簧管吹出跳跃、断裂、充满棱角的乐句。它游走在调性边缘,是前卫爵士里结构最迷人的一张唱片。" },
  { id:"0045", title:"Haitian Fight Song", artist:"Charles Mingus", composer:"Charles Mingus", year:1957, album:"The Clown", label:"Atlantic", era:"free",
    genres:["avant-garde","blues","gospel"], instruments:["贝斯"], moods:["兴奋","孤独"],
    reason:"明格斯从一段独奏贝斯开始,层层堆叠成福音式的怒吼。他说这首曲子关乎民权抗争。结构在自由与蓝调间游走,情绪从低语推到嘶喊,是爵士作为政治呐喊的典范。" },
  { id:"0046", title:"Bulbs", artist:"Cecil Taylor", composer:"Cecil Taylor", year:1961, album:"New York City R&B", label:"Candid", era:"free",
    genres:["free jazz","avant-garde","piano"], instruments:["钢琴"], moods:["失眠","工作"],
    reason:"泰勒把钢琴当成打击乐,用密集的音块与爆发的能量重写演奏的定义。他的音乐艰深、不妥协,是自由爵士里最纯粹的声音实验。挑战耳朵,也拓宽耳朵的边界。" },
  { id:"0047", title:"Ascension (Edit)", artist:"John Coltrane", composer:"John Coltrane", year:1965, album:"Ascension", label:"Impulse!", era:"free",
    genres:["free jazz","spiritual"], instruments:["萨克斯"], moods:["失眠"],
    reason:"科尔特兰召集十一位乐手集体即兴,声音如海啸般层层涌起。它把《至爱》的精神性推向无调性的极限。这是爵士史上最具争议也最壮观的一次集体出神,需要耐心,但回报惊人。" },

  // ── 9. Latin Jazz / Bossa Nova ───────────────────────
  { id:"0048", title:"The Girl from Ipanema", artist:"Stan Getz & João Gilberto", composer:"Antônio Carlos Jobim", year:1964, album:"Getz/Gilberto", label:"Verve", era:"latin",
    genres:["bossa nova","latin"], instruments:["萨克斯","人声","吉他"], moods:["咖啡馆","阅读","开车"],
    reason:"史上最著名的波萨诺瓦,让阿斯特鲁德·吉尔贝托一夜成名。盖茨慵懒的萨克斯、轻声细语的葡语,营造出海滩午后的微醺。它把巴西的摇摆带向全世界,至今仍是咖啡馆的标配。" },
  { id:"0049", title:"Desafinado", artist:"Antônio Carlos Jobim", composer:"Antônio Carlos Jobim", year:1962, album:"Jazz Samba", label:"Verve", era:"latin",
    genres:["bossa nova","latin"], instruments:["吉他","萨克斯"], moods:["咖啡馆","阅读"],
    reason:"标题意为‘走音’,却是波萨诺瓦最精巧的和声练习。乔宾用看似随性的旋律藏起复杂的转调。它温柔、慵懒,是理解波萨诺瓦‘简约外表下的精致’的入门曲。" },
  { id:"0050", title:"Manteca", artist:"Dizzy Gillespie", composer:"Dizzy Gillespie / Chano Pozo", year:1947, album:"Afro-Cuban", label:"RCA Victor", era:"latin",
    genres:["latin","afro-cuban","bebop"], instruments:["小号","鼓"], moods:["兴奋","开车"],
    reason:"古巴鼓手查诺·波佐与吉莱斯皮合写,是‘非洲-古巴爵士’的开山之作。强悍的克拉维节奏第一次正面撞进比波普。听它就是听拉丁爵士诞生的那一声炸响。" },
  { id:"0051", title:"Oye Como Va", artist:"Tito Puente", composer:"Tito Puente", year:1963, album:"El Rey Bravo", label:"Tico", era:"latin",
    genres:["latin","mambo"], instruments:["鼓","钢琴"], moods:["兴奋","开车"],
    reason:"普恩特的曼波金曲,后被桑塔纳改成摇滚名曲而再度爆红。那条循环的钢琴‘蒙图诺’让人无法不摇摆。它是拉丁爵士最具感染力的舞曲面孔。" },
  { id:"0052", title:"Chega de Saudade", artist:"João Gilberto", composer:"Antônio Carlos Jobim", year:1959, album:"Chega de Saudade", label:"Odeon", era:"latin",
    genres:["bossa nova"], instruments:["吉他","人声"], moods:["夜晚","孤独","咖啡馆"],
    reason:"公认的第一首波萨诺瓦录音。吉尔贝托轻得几乎听不见的嗓音与他独创的切分吉他,定义了整个流派的私语美学。波萨诺瓦的故事,就从这首歌开始。" },
  { id:"0053", title:"Soul Sauce (Guachi Guaro)", artist:"Cal Tjader", composer:"Dizzy Gillespie / Chano Pozo", year:1964, album:"Soul Sauce", label:"Verve", era:"latin",
    genres:["latin","soul jazz"], instruments:["颤音琴"], moods:["咖啡馆","兴奋"],
    reason:"加州颤音琴手塔德把拉丁爵士做得轻盈又时髦,这首曲子带着一句‘¡Sauce!’的吆喝成为热门。它代表了 60 年代拉丁爵士与灵魂爵士交融的都会摩登感。" },

  // ── 10. Fusion / Jazz-rock ───────────────────────────
  { id:"0054", title:"Bitches Brew", artist:"Miles Davis", composer:"Miles Davis", year:1970, album:"Bitches Brew", label:"Columbia", era:"fusion",
    genres:["fusion","jazz-rock"], instruments:["小号","电子键盘"], moods:["失眠","开车"],
    reason:"融合爵士的开闸之作。迈尔斯插上电,把摇滚的能量、放克的律动与录音室的剪辑变成一锅幽暗翻腾的声音浓汤。它分裂了爵士界,也开辟了全新的版图。听它需要沉浸,而非跟唱。" },
  { id:"0055", title:"Birdland", artist:"Weather Report", composer:"Joe Zawinul", year:1977, album:"Heavy Weather", label:"Columbia", era:"fusion",
    genres:["fusion","jazz-rock"], instruments:["电子键盘","贝斯"], moods:["开车","兴奋"],
    reason:"以传奇爵士俱乐部命名,是融合爵士最朗朗上口的金曲。扎维努尔的合成器与雅科·帕斯托留斯的电贝斯交织出明亮的层次。它证明融合也能既复杂又流行,是入门 fusion 的首选。" },
  { id:"0056", title:"Chameleon", artist:"Herbie Hancock", composer:"Herbie Hancock", year:1973, album:"Head Hunters", label:"Columbia", era:"fusion",
    genres:["fusion","funk"], instruments:["电子键盘"], moods:["开车","工作","兴奋"],
    reason:"那条合成器贝斯线是放克爵士的教科书。汉考克彻底拥抱放克,做出史上最畅销的爵士唱片之一,也被后世嘻哈无数次采样。爵士与放克的联姻,从这条 riff 开始。" },
  { id:"0057", title:"Birds of Fire", artist:"Mahavishnu Orchestra", composer:"John McLaughlin", year:1973, album:"Birds of Fire", label:"Columbia", era:"fusion",
    genres:["fusion","jazz-rock"], instruments:["吉他","鼓"], moods:["兴奋","开车"],
    reason:"麦克劳克林把印度音乐的复杂节拍、摇滚的失真吉他与爵士的即兴熔于一炉。速度与音量都推到极限,是融合爵士最炽烈、最具技术冲击力的一面。" },
  { id:"0058", title:"Spain", artist:"Chick Corea / Return to Forever", composer:"Chick Corea", year:1972, album:"Light as a Feather", label:"Polydor", era:"fusion",
    genres:["fusion","latin"], instruments:["电子键盘"], moods:["开车","兴奋","咖啡馆"],
    reason:"以罗德里戈的《阿兰胡埃斯协奏曲》开场,科里亚把西班牙色彩、拉丁律动与电钢的明亮揉在一起。旋律灿烂、节奏轻快,是融合爵士里最阳光、最受欢迎的曲目之一。" },
  { id:"0059", title:"Are You Going with Me?", artist:"Pat Metheny Group", composer:"Pat Metheny / Lyle Mays", year:1982, album:"Offramp", label:"ECM", era:"fusion",
    genres:["fusion","contemporary"], instruments:["吉他"], moods:["开车","夜晚","阅读"],
    reason:"梅瑟尼用吉他合成器吹出如人声般绵长的独奏,在缓缓堆叠中走向辽阔的高潮。这是融合爵士抒情、电影感的一面,适合长途夜路与独自出神。" },

  // ── 11. Neo-bop / Straight-ahead ─────────────────────
  { id:"0060", title:"Black Codes (From the Underground)", artist:"Wynton Marsalis", composer:"Wynton Marsalis", year:1985, album:"Black Codes (From the Underground)", label:"Columbia", era:"neobop",
    genres:["neo-bop","straight-ahead"], instruments:["小号"], moods:["工作","兴奋"],
    reason:"马萨利斯一代回归原声、回归传统的旗帜之作。技术精湛、结构严谨,既向 60 年代迈尔斯五重奏致敬,又有当代的锋利。新波普‘把爵士当经典传承’的雄心,在此一览无余。" },
  { id:"0061", title:"The Köln Concert (Part I)", artist:"Keith Jarrett", composer:"Keith Jarrett", year:1975, album:"The Köln Concert", label:"ECM", era:"neobop",
    genres:["solo piano","improvisation"], instruments:["钢琴"], moods:["夜晚","阅读","雨天","失眠"],
    reason:"史上最畅销的独奏钢琴唱片。贾勒特在一架状态不佳的钢琴上即兴出整场音乐会,旋律如泉水般自然涌出。它纯净、抒情、近乎冥想,是无数人爱上爵士钢琴的起点。" },
  { id:"0062", title:"Mo' Better Blues", artist:"Branford Marsalis", composer:"Bill Lee", year:1990, album:"Mo' Better Blues (OST)", label:"Columbia", era:"neobop",
    genres:["neo-bop","ballad"], instruments:["萨克斯"], moods:["夜晚","咖啡馆","雨天"],
    reason:"为斯派克·李同名电影所作的主题,布兰福德的次中音萨克斯把都市的忧郁吹得温润动人。它让原声爵士在 90 年代重新走进大银幕与年轻听众,优雅而入耳。" },
  { id:"0063", title:"Lush Life", artist:"Joe Henderson", composer:"Billy Strayhorn", year:1991, album:"Lush Life", label:"Verve", era:"neobop",
    genres:["neo-bop","ballad"], instruments:["萨克斯"], moods:["夜晚","孤独","失眠"],
    reason:"亨德森向斯特雷霍恩致敬的专辑同名曲。这首关于纸醉金迷与幻灭的歌和声极难,他却吹得从容而苍凉。成熟乐手如何对待经典曲目,这是一堂示范课。" },
  { id:"0064", title:"Blackbird", artist:"Brad Mehldau", composer:"Lennon / McCartney", year:1998, album:"The Art of the Trio Vol. 3", label:"Warner", era:"neobop",
    genres:["neo-bop","piano trio"], instruments:["钢琴"], moods:["夜晚","阅读","雨天"],
    reason:"梅尔道把披头士的歌变成绵长的钢琴沉思,左右手各行其是又彼此缠绕。他这一代用流行曲拓展爵士曲库,内省、细腻,是当代钢琴三重奏的代表声音。" },
  { id:"0065", title:"Strasbourg / St. Denis", artist:"Roy Hargrove", composer:"Roy Hargrove", year:2008, album:"Earfood", label:"Emarcy", era:"neobop",
    genres:["straight-ahead","hard bop"], instruments:["小号"], moods:["咖啡馆","开车","兴奋"],
    reason:"哈格罗夫这条朗朗上口的律动让原声硬波普在新世纪重新好听起来,成了无数年轻乐手的派对常备曲。它证明回归传统不必学究,也可以热血、上口、充满生命力。" },

  // ── 12. Acid / Nu / Smooth Jazz ──────────────────────
  { id:"0066", title:"Rose Rouge", artist:"St Germain", composer:"Ludovic Navarre", year:2000, album:"Tourist", label:"Blue Note", era:"acid",
    genres:["acid jazz","house","nu jazz"], instruments:["电子键盘","萨克斯"], moods:["咖啡馆","工作","夜晚"],
    reason:"法国制作人圣日耳曼把浩室节拍、采样的爵士独奏与 Marlena Shaw 的人声切片缝在一起。它在 Blue Note 厂牌发行,象征老唱片在俱乐部时代的重生。都市夜晚的完美背景乐。" },
  { id:"0067", title:"Afro Blue", artist:"Robert Glasper Experiment", composer:"Mongo Santamaría", year:2012, album:"Black Radio", label:"Blue Note", era:"acid",
    genres:["nu jazz","neo-soul"], instruments:["钢琴","人声"], moods:["夜晚","咖啡馆","阅读"],
    reason:"格拉斯帕请来 Erykah Badu 重唱这首拉丁爵士经典,把爵士、新灵魂与嘻哈节拍融为一体。专辑《Black Radio》拿下格莱美,标志爵士与当代黑人流行乐的全面对话。" },
  { id:"0068", title:"Cantaloop (Flip Fantasia)", artist:"Us3", composer:"Herbie Hancock", year:1993, album:"Hand on the Torch", label:"Blue Note", era:"acid",
    genres:["acid jazz","hip-hop"], instruments:["小号"], moods:["开车","兴奋","工作"],
    reason:"直接采样汉考克《Cantaloupe Island》的嘻哈爵士热单,是第一张拿到金唱片的 Blue Note 专辑。它让人意识到:爵士的老库存可以变成新一代的节拍源泉。" },
  { id:"0069", title:"Virtual Insanity", artist:"Jamiroquai", composer:"Jay Kay / Toby Smith", year:1996, album:"Travelling Without Moving", label:"Sony Soho2", era:"acid",
    genres:["acid jazz","funk"], instruments:["电子键盘","人声"], moods:["开车","兴奋","工作"],
    reason:"酸爵士走向主流流行的代表。放克贝斯、电钢、迪斯科的律动加上那支著名 MV,让 Jamiroquai 红遍全球。它提醒我们爵士的基因如何渗进 90 年代的流行舞曲。" },
  { id:"0070", title:"Common Free Style", artist:"The RH Factor", composer:"Roy Hargrove", year:2003, album:"Hard Groove", label:"Verve", era:"acid",
    genres:["nu jazz","funk","soul"], instruments:["小号"], moods:["开车","工作","兴奋"],
    reason:"哈格罗夫的另一面:用小号领衔一支放克-灵魂大队,请来 D'Angelo、Common 等新灵魂与嘻哈名手。它是 2000 年代爵士与 neo-soul 跨界最酣畅的一张唱片。" },
  { id:"0071", title:"Songbird", artist:"Kenny G", composer:"Kenny Gorelick", year:1986, album:"Duotones", label:"Arista", era:"acid",
    genres:["smooth jazz"], instruments:["萨克斯"], moods:["咖啡馆","工作","阅读"],
    reason:"无论乐评如何争论,肯尼·基这首高音萨克斯小品是 smooth jazz 走进千家万户的标志。它柔顺、抒情、毫无攻击性,代表了爵士作为‘都市背景音乐’最商业、也最普及的一支。" },

  // ── 13. New London / Global Revival ──────────────────
  { id:"0072", title:"Change of the Guard", artist:"Kamasi Washington", composer:"Kamasi Washington", year:2015, album:"The Epic", label:"Brainfeeder", era:"newlondon",
    genres:["spiritual jazz","global"], instruments:["萨克斯"], moods:["兴奋","夜晚","开车"],
    reason:"洛杉矶萨克斯手卡马西用合唱团、弦乐与狂潮般的独奏,让精神爵士在新世纪复活。这首近十三分钟的开场曲气势磅礴,把科尔特兰的衣钵交给了嘻哈一代的听众。" },
  { id:"0073", title:"My Queen Is Harriet Tubman", artist:"Sons of Kemet", composer:"Shabaka Hutchings", year:2018, album:"Your Queen Is a Reptile", label:"Impulse!", era:"newlondon",
    genres:["spiritual jazz","afrobeat","global"], instruments:["萨克斯","鼓"], moods:["兴奋","开车"],
    reason:"伦敦新爵士的旗手莎芭卡,用双鼓、大号与萨克斯打造出狂热的非洲-加勒比律动。专辑以黑人女性英雄命名,把爵士重新变成抗争与舞蹈的音乐。能量惊人,不容错过。" },
  { id:"0074", title:"Source", artist:"Nubya Garcia", composer:"Nubya Garcia", year:2020, album:"Source", label:"Concord", era:"newlondon",
    genres:["spiritual jazz","global"], instruments:["萨克斯"], moods:["夜晚","开车","阅读"],
    reason:"伦敦萨克斯手努比亚把雷鬼、库比亚与精神爵士织成一条十二分钟的长河。沉稳、深邃、根系深厚,代表了当代英伦爵士对身份与传承的探索。新一代爵士的女性面孔。" },
  { id:"0075", title:"Hopopono", artist:"GoGo Penguin", composer:"GoGo Penguin", year:2014, album:"v2.0", label:"Gondwana", era:"newlondon",
    genres:["nu jazz","electronica","piano trio"], instruments:["钢琴","贝斯","鼓"], moods:["工作","阅读","开车"],
    reason:"曼彻斯特钢琴三重奏把电子乐与 Aphex Twin 式的节拍翻译成原声乐器。机械感的律动配上抒情旋律,是 21 世纪爵士三重奏最受年轻听众欢迎的新声音。专注工作时的绝佳配乐。" },
  { id:"0076", title:"Diaspora", artist:"Christian Scott aTunde Adjuah", composer:"Christian Scott", year:2017, album:"Diaspora", label:"Stretch Music", era:"newlondon",
    genres:["spiritual jazz","global","fusion"], instruments:["小号"], moods:["夜晚","阅读","孤独"],
    reason:"新奥尔良小号手斯科特自创‘伸展音乐’,把嘻哈、西非节奏与电子织进爵士。他柔化的小号音色独树一帜。这首曲子关乎离散与寻根,是当代爵士与全球黑人经验的对话。" },
  { id:"0077", title:"Lingus", artist:"Snarky Puppy", composer:"Michael League", year:2014, album:"We Like It Here", label:"GroundUP", era:"newlondon",
    genres:["fusion","jazz-funk","collective"], instruments:["电子键盘","贝斯"], moods:["兴奋","开车","工作"],
    reason:"这支大型集体乐队的现场名曲,以 Cory Henry 一段令观众失控欢呼的合成器独奏闻名(那段视频有上亿播放)。它让器乐爵士-放克在 YouTube 时代重新点燃年轻人的热情。" }
];

// 锚点曲(spec 第七节首批锚点)与重点人物,供首页‘按人物进入’
window.FEATURED_ARTISTS = [
  "Louis Armstrong","Duke Ellington","Charlie Parker","Thelonious Monk","Miles Davis",
  "John Coltrane","Bill Evans","Ornette Coleman","Charles Mingus","Herbie Hancock",
  "Sonny Rollins","Ella Fitzgerald","Keith Jarrett","Kamasi Washington"
];

window.MOODS = ["夜晚","雨天","咖啡馆","阅读","开车","工作","孤独","兴奋","失眠"];
window.INSTRUMENTS = ["小号","萨克斯","钢琴","贝斯","鼓","吉他","人声","单簧管","颤音琴","电子键盘"];
